import {SeededRandom} from './random.ts';
import type {BuildingKind,BuildingState,FactionId,FactionState,GameCommand,GameState,MapDefinition,Point,ResourceKind,UnitKind,UnitState} from '../shared/protocol.ts';

const UNIT:Record<UnitKind,{hp:number,speed:number,damage:number,range:number,sight:number,cost:[number,number,number]}>= {
 villager:{hp:70,speed:88,damage:3,range:24,sight:210,cost:[0,50,0]},soldier:{hp:120,speed:100,damage:18,range:38,sight:240,cost:[0,60,30]},archer:{hp:78,speed:94,damage:14,range:165,sight:290,cost:[0,45,45]},cavalry:{hp:165,speed:138,damage:23,range:44,sight:270,cost:[0,80,70]}
};
const BUILDING:Record<BuildingKind,{hp:number,radius:number,cost:[number,number,number]}>= {town:{hp:1200,radius:68,cost:[0,0,0]},house:{hp:450,radius:42,cost:[80,0,0]},barracks:{hp:700,radius:56,cost:[140,0,0]}};
const FOUR_PLAYER_STARTS:Point[]=[{x:500,y:450},{x:3100,y:450},{x:500,y:1950},{x:3100,y:1950}];
const TWO_PLAYER_STARTS:Point[]=[{x:420,y:760},{x:2000,y:760}];
type Order={type:'move'|'attack'|'gather'|'build';target?:Point;targetId?:number;path?:Point[];pathTarget?:Point;repathAt?:number;returning?:boolean};

export class GameEngine{
 state:GameState; private nextId=1;private eventId=1;private orders=new Map<number,Order>();private rng:SeededRandom;private starts:Point[]=[];
 constructor(roomId:string,seed:number,factions:Array<{id?:FactionId;name:string;kind:'human'|'cpu'}>){this.rng=new SeededRandom(seed);this.starts=factions.length===2?TWO_PLAYER_STARTS:FOUR_PLAYER_STARTS;const map=this.generateMap(seed,this.starts);this.state={roomId,seed,tick:0,timeMs:0,phase:'countdown',startAt:Date.now()+3000,factions:factions.map((f,i)=>{const id=f.id??i as FactionId;return{id,name:f.name,color:['blue','red','green','yellow'][id],kind:f.kind,wood:260,food:500,gold:260,popCap:10,age:1,attackBonus:0,gatherBonus:0,armorBonus:0,research:[],defeated:false}}),units:[],buildings:[],map,events:[],fog:{}};for(const f of this.state.factions)this.spawnFaction(f.id);this.updateFog()}
 static restore(saved:GameState|{state:GameState;orders?:Array<[number,Order]>}){const state='state'in saved?saved.state:saved,engine=Object.create(GameEngine.prototype) as GameEngine;engine.state=state;engine.nextId=Math.max(0,...state.units.map(x=>x.id),...state.buildings.map(x=>x.id),...state.map.resources.map(x=>x.id))+1;engine.eventId=Math.max(0,...state.events.map(x=>x.id))+1;engine.orders=new Map('state'in saved?saved.orders??[]:[]);engine.rng=new SeededRandom(state.seed+state.tick);engine.starts=state.factions.length===2?TWO_PLAYER_STARTS:FOUR_PLAYER_STARTS;return engine}
 snapshot(){return{state:structuredClone(this.state),orders:[...this.orders.entries()].map(([id,order])=>[id,structuredClone(order)] as [number,Order])}}
 private generateMap(seed:number,starts:Point[]):MapDefinition{const random=new SeededRandom(seed),resources:MapDefinition['resources']=[],width=starts.length===2?2400:3600,height=starts.length===2?1600:2400;let id=100000;for(const start of starts)for(const [kind,count,dist] of [['wood',starts.length===2?8:14,300],['food',starts.length===2?6:9,220],['gold',starts.length===2?5:7,370]] as [ResourceKind,number,number][]){for(let i=0;i<count;i++){const a=(i/count)*Math.PI*2+random.between(-.16,.16),d=dist+random.between(-55,55);resources.push({id:id++,kind,x:Math.max(70,Math.min(width-70,start.x+Math.cos(a)*d)),y:Math.max(90,Math.min(height-70,start.y+Math.sin(a)*d)),amount:kind==='wood'?520:380})}}const extras=starts.length===2?22:50;for(let i=0;i<extras;i++)resources.push({id:id++,kind:random.pick<ResourceKind>(['wood','food','gold']),x:random.between(starts.length===2?760:1000,width-(starts.length===2?760:1000)),y:random.between(starts.length===2?300:650,height-(starts.length===2?300:650)),amount:450});return{seed,width,height,resources}}
 private spawnFaction(id:FactionId){const index=this.state.factions.findIndex(f=>f.id===id),p=this.starts[index]??FOUR_PLAYER_STARTS[id];this.addBuilding(id,'town',p.x,p.y,1);const offsets=this.starts.length===2?(index===0?[[80,-60],[85,0],[80,60],[145,-25],[145,35]]:[[-100,-70],[-100,-5],[-100,60],[-40,90],[-40,30]]):[[100,-80],[145,-42],[100,-4],[145,34],[100,72]];for(const [dx,dy] of offsets)this.addUnit(id,'villager',p.x+dx,p.y+dy)}
 private addUnit(factionId:FactionId,kind:UnitKind,x:number,y:number){const s=UNIT[kind];this.state.units.push({id:this.nextId++,factionId,kind,x,y,hp:s.hp,maxHp:s.hp,state:'idle',nextAttackAt:0})}
 private addBuilding(factionId:FactionId,kind:BuildingKind,x:number,y:number,progress:number){const s=BUILDING[kind];const b:BuildingState={id:this.nextId++,factionId,kind,x,y,hp:s.hp*(progress||.1),maxHp:s.hp,progress,state:progress>=1?'idle':'building'};this.state.buildings.push(b);return b}
 command(factionId:FactionId,command:GameCommand):{ok:true}|{ok:false;reason:string}{if(this.state.phase!=='playing')return{ok:false,reason:'GAME_NOT_PLAYING'};const f=this.state.factions.find(x=>x.id===factionId);if(!f||f.defeated)return{ok:false,reason:'INVALID_FACTION'};const owned=(ids:number[])=>{if(ids.length<1||ids.length>50)return[];return this.state.units.filter(u=>ids.includes(u.id)&&u.factionId===factionId)};if(command.type==='MOVE'){const units=owned(command.unitIds);if(units.length!==new Set(command.unitIds).size||!this.validPoint(command.target))return{ok:false,reason:'INVALID_MOVE'};units.forEach((u,i)=>this.orders.set(u.id,{type:'move',target:{x:command.target.x+(i%6)*28,y:command.target.y+Math.floor(i/6)*28}}));return{ok:true}}
  if(command.type==='STOP'){const units=owned(command.unitIds);if(units.length!==new Set(command.unitIds).size)return{ok:false,reason:'INVALID_UNITS'};units.forEach(u=>{this.orders.delete(u.id);u.state='idle'});return{ok:true}}
  if(command.type==='ATTACK'){const units=owned(command.unitIds),target=this.entity(command.targetId);if(units.length!==new Set(command.unitIds).size||!target||target.factionId===factionId)return{ok:false,reason:'INVALID_ATTACK'};units.forEach(u=>this.orders.set(u.id,{type:'attack',targetId:target.id}));return{ok:true}}
  if(command.type==='GATHER'){const units=owned(command.unitIds).filter(u=>u.kind==='villager'),resource=this.state.map.resources.find(r=>r.id===command.targetId&&r.amount>0);if(!resource||units.length!==new Set(command.unitIds).size)return{ok:false,reason:'INVALID_GATHER'};units.forEach(u=>this.orders.set(u.id,{type:'gather',targetId:resource.id}));return{ok:true}}
  if(command.type==='BUILD'){const builders=owned(command.builderIds).filter(u=>u.kind==='villager'),spec=BUILDING[command.building];if(builders.length!==new Set(command.builderIds).size||!this.validPoint(command)||!this.canPlace(command.x,command.y,spec.radius)||!this.pay(f,spec.cost))return{ok:false,reason:'INVALID_BUILD'};const b=this.addBuilding(factionId,command.building,command.x,command.y,0);builders.forEach(u=>this.orders.set(u.id,{type:'build',targetId:b.id}));return{ok:true}}
  if(command.type==='CONTINUE_BUILD'){const builders=owned(command.builderIds).filter(u=>u.kind==='villager'),building=this.state.buildings.find(b=>b.id===command.buildingId&&b.factionId===factionId&&b.progress<1);if(!building||builders.length!==new Set(command.builderIds).size)return{ok:false,reason:'INVALID_CONSTRUCTION'};builders.forEach(u=>this.orders.set(u.id,{type:'build',targetId:building.id}));return{ok:true}}
  const b=this.state.buildings.find(x=>x.id===command.buildingId&&x.factionId===factionId&&x.progress>=1);if(!b)return{ok:false,reason:'INVALID_BUILDING'};
  if(command.type==='TRAIN'){if((command.unit==='villager'&&b.kind!=='town')||(command.unit!=='villager'&&b.kind!=='barracks'))return{ok:false,reason:'WRONG_BUILDING'};const requiredAge=command.unit==='archer'?2:command.unit==='cavalry'?3:1,spec=UNIT[command.unit];if(f.age<requiredAge||this.population(factionId)>=f.popCap||!this.pay(f,spec.cost))return{ok:false,reason:'CANNOT_TRAIN'};this.addUnit(factionId,command.unit,b.x+BUILDING[b.kind].radius+45,b.y);this.emit('train',factionId,b.id);return{ok:true}}
  if(command.type==='ADVANCE_AGE'){const costs:[[number,number,number],[number,number,number],[number,number,number]]=[[0,300,150],[0,500,300],[0,800,500]];if(b.kind!=='town'||f.age>=4||!this.pay(f,costs[f.age-1]))return{ok:false,reason:'CANNOT_ADVANCE'};f.age++;this.emit('age',factionId,b.id);return{ok:true}}
  if(command.type==='RESEARCH'){const costs:{[k:string]:[number,number,number]}={attack:[150,0,100],economy:[120,100,0],armor:[180,0,140]},required=command.tech==='armor'?3:2,correctBuilding=command.tech==='economy'?b.kind==='town':b.kind==='barracks';if(!correctBuilding||f.age<required||f.research.includes(command.tech)||!this.pay(f,costs[command.tech]))return{ok:false,reason:'CANNOT_RESEARCH'};f.research.push(command.tech);if(command.tech==='attack')f.attackBonus+=.2;if(command.tech==='economy')f.gatherBonus+=.25;if(command.tech==='armor')f.armorBonus+=.15;this.emit('research',factionId,b.id);return{ok:true}}
  return{ok:false,reason:'UNKNOWN_COMMAND'}
 }
 tick(dtMs=100){if(this.state.phase==='countdown'&&Date.now()>=this.state.startAt)this.state.phase='playing';if(this.state.phase!=='playing')return;const dt=Math.min(dtMs,250)/1000;this.state.tick++;this.state.timeMs+=dtMs;this.state.events=[];for(const u of [...this.state.units])this.updateUnit(u,dt);this.separate();this.updateFog();this.checkVictory()}
 private updateUnit(u:UnitState,dt:number){let o=this.orders.get(u.id);if(!o){const enemy=this.nearestEnemy(u,Math.min(UNIT[u.kind].sight,260));if(enemy){o={type:'attack',targetId:enemy.id};this.orders.set(u.id,o)}else{u.state='idle';return}}if(o.type==='move'&&o.target){u.state='moving';if(this.navigate(u,o,o.target,dt)<5){this.orders.delete(u.id);u.state='idle'};return}if(o.type==='attack'){const t=this.entity(o.targetId!);if(!t||t.factionId===u.factionId){this.orders.delete(u.id);return}const reach=UNIT[u.kind].range+(this.isBuilding(t)?BUILDING[t.kind].radius:15),d=this.distance(u,t);if(d>reach){u.state='moving';const approach=this.approach(u,t,Math.max(18,reach-5));this.navigate(u,o,approach,dt,true);return}u.state='attacking';o.path=undefined;if(this.state.timeMs>=u.nextAttackAt){u.nextAttackAt=this.state.timeMs+(u.kind==='archer'?900:u.kind==='villager'?1050:700);const faction=this.faction(u.factionId);t.hp-=UNIT[u.kind].damage*(1+faction.attackBonus)*(1-this.faction(t.factionId).armorBonus);this.emit('hit',u.factionId,t.id,t.x,t.y);if(t.hp<=0)this.kill(t)}return}
  if(o.type==='gather'){const r=this.state.map.resources.find(x=>x.id===o.targetId),town=this.state.buildings.find(x=>x.factionId===u.factionId&&x.kind==='town'&&x.progress>=1);if(!r||!town||r.amount<=0&&!u.cargo){this.orders.delete(u.id);u.cargo=0;u.cargoKind=undefined;return}if(o.returning){if(this.distance(u,town)>145){u.state='moving';this.navigate(u,o,this.approach(u,town,138),dt,true);return}if(u.cargoKind)this.faction(u.factionId)[u.cargoKind]+=u.cargo??0;u.cargo=0;u.cargoKind=undefined;o.returning=false;o.path=undefined;if(r.amount<=0)this.orders.delete(u.id);return}if(this.distance(u,r)>48){u.state='moving';this.navigate(u,o,this.approach(u,r,42),dt,true);return}u.state='gathering';o.path=undefined;const cargo=u.cargo??0,qty=Math.min(r.amount,8*(1+this.faction(u.factionId).gatherBonus)*dt,20-cargo);r.amount-=qty;u.cargo=cargo+qty;u.cargoKind=r.kind;if(u.cargo>=19.9||r.amount<=0){o.returning=true;o.path=undefined}return}
  if(o.type==='build'){const b=this.state.buildings.find(x=>x.id===o.targetId);if(!b||b.progress>=1){this.orders.delete(u.id);return}if(this.distance(u,b)>BUILDING[b.kind].radius+25){u.state='moving';this.navigate(u,o,this.approach(u,b,BUILDING[b.kind].radius+20),dt,true);return}u.state='building';o.path=undefined;b.progress=Math.min(1,b.progress+dt/16);b.hp=Math.max(b.hp,b.maxHp*b.progress);if(b.progress>=1){b.state='idle';if(b.kind==='house')this.faction(b.factionId).popCap+=5;this.emit('build',b.factionId,b.id,b.x,b.y)}}
 }
 private navigate(u:UnitState,o:Order,target:Point,dt:number,dynamic=false){const changed=!o.pathTarget||this.distance(o.pathTarget,target)>36;if(!o.path?.length||changed||(dynamic&&this.state.timeMs>=(o.repathAt??0))){o.path=this.findPath(u,target);o.pathTarget={...target};o.repathAt=this.state.timeMs+500}while(o.path.length>1&&this.distance(u,o.path[0])<20)o.path.shift();const next=o.path[0]??target,remaining=this.move(u,next,dt);if(remaining<5&&o.path.length)o.path.shift();return this.distance(u,target)}
 private move(u:UnitState,p:Point,dt:number){const dx=p.x-u.x,dy=p.y-u.y,d=Math.hypot(dx,dy);if(d<.001)return 0;const step=Math.min(d,UNIT[u.kind].speed*dt),w=this.state.map.width,h=this.state.map.height;u.x=Math.max(15,Math.min(w-15,u.x+dx/d*step));u.y=Math.max(70,Math.min(h-15,u.y+dy/d*step));return d-step}
 private findPath(from:Point,to:Point){const cell=48,w=this.state.map.width,h=this.state.map.height,cols=Math.ceil(w/cell),rows=Math.ceil(h/cell),key=(x:number,y:number)=>y*cols+x,point=(x:number,y:number)=>({x:Math.min(w-15,x*cell+cell/2),y:Math.max(70,Math.min(h-15,y*cell+cell/2))}),sx=Math.max(0,Math.min(cols-1,Math.floor(from.x/cell))),sy=Math.max(1,Math.min(rows-1,Math.floor(from.y/cell))),gx=Math.max(0,Math.min(cols-1,Math.floor(to.x/cell))),gy=Math.max(1,Math.min(rows-1,Math.floor(to.y/cell))),blocked=(x:number,y:number)=>{if(x===gx&&y===gy)return false;const p=point(x,y);return this.state.buildings.some(b=>b.progress>.05&&this.distance(p,b)<BUILDING[b.kind].radius+18)};if(!blocked(gx,gy)&&!this.state.buildings.some(b=>this.segmentHitsBuilding(from,to,b)))return[{...to}];const open:[number,number,number][]=[[Math.hypot(gx-sx,gy-sy),sx,sy]],came=new Map<number,number>(),cost=new Map<number,number>([[key(sx,sy),0]]),seen=new Set<number>();while(open.length){open.sort((a,b)=>a[0]-b[0]);const[,x,y]=open.shift()!,k=key(x,y);if(seen.has(k))continue;seen.add(k);if(x===gx&&y===gy){const path:Point[]=[{...to}];let cur=k;while(cur!==key(sx,sy)){const cx=cur%cols,cy=Math.floor(cur/cols);path.push(point(cx,cy));cur=came.get(cur)!}path.reverse();return this.simplifyPath(from,path)}for(const[dx,dy]of[[1,0],[-1,0],[0,1],[0,-1],[1,1],[1,-1],[-1,1],[-1,-1]]){const nx=x+dx,ny=y+dy,nk=key(nx,ny);if(nx<0||ny<1||nx>=cols||ny>=rows||blocked(nx,ny))continue;if(dx&&dy&&(blocked(x+dx,y)||blocked(x,y+dy)))continue;const nc=(cost.get(k)??0)+(dx&&dy?1.414:1);if(nc<(cost.get(nk)??Infinity)){cost.set(nk,nc);came.set(nk,k);open.push([nc+Math.hypot(gx-nx,gy-ny),nx,ny])}}}return[{...to}]}
 private simplifyPath(from:Point,path:Point[]){const result:Point[]=[],lineStart={...from};let anchor=lineStart;for(let i=0;i<path.length;i++){const candidate=path[i];if(this.state.buildings.some(b=>this.segmentHitsBuilding(anchor,candidate,b))){const previous=path[Math.max(0,i-1)];result.push(previous);anchor=previous}}result.push(path[path.length-1]);return result.filter((p,i,a)=>i===0||this.distance(p,a[i-1])>2)}
 private segmentHitsBuilding(a:Point,b:Point,building:BuildingState){if(building.progress<=.05)return false;const vx=b.x-a.x,vy=b.y-a.y,len2=vx*vx+vy*vy,t=len2?Math.max(0,Math.min(1,((building.x-a.x)*vx+(building.y-a.y)*vy)/len2)):0,px=a.x+t*vx,py=a.y+t*vy;return Math.hypot(building.x-px,building.y-py)<BUILDING[building.kind].radius+18}
 private approach(from:Point,target:Point,distance:number){const dx=from.x-target.x,dy=from.y-target.y,d=Math.hypot(dx,dy)||1;return{x:target.x+dx/d*distance,y:target.y+dy/d*distance}}
 private nearestEnemy(u:UnitState,radius:number){let best:UnitState|BuildingState|undefined,bestD=radius;for(const e of [...this.state.units,...this.state.buildings]){if(e.factionId===u.factionId||this.faction(e.factionId).defeated)continue;const d=this.distance(u,e);if(d<bestD){best=e;bestD=d}}return best}
 private separate(){const us=this.state.units,cell=36,buckets=new Map<string,UnitState[]>(),offset=new Map<number,Point>(),w=this.state.map.width,h=this.state.map.height;for(const u of us){const k=`${Math.floor(u.x/cell)}:${Math.floor(u.y/cell)}`;(buckets.get(k)??(buckets.set(k,[]),buckets.get(k)!)).push(u);offset.set(u.id,{x:0,y:0})}for(const a of us){const cx=Math.floor(a.x/cell),cy=Math.floor(a.y/cell);for(let yy=cy-1;yy<=cy+1;yy++)for(let xx=cx-1;xx<=cx+1;xx++)for(const b of buckets.get(`${xx}:${yy}`)??[]){if(a.id>=b.id)continue;const dx=b.x-a.x,dy=b.y-a.y,d=Math.hypot(dx,dy),min=28;if(d>=min)continue;const angle=d>.1?Math.atan2(dy,dx):((a.id*31+b.id*17)%360)*Math.PI/180,nx=d>.1?dx/d:Math.cos(angle),ny=d>.1?dy/d:Math.sin(angle),push=Math.min(2.5,(min-Math.max(d,.1))*.18),oa=offset.get(a.id)!,ob=offset.get(b.id)!;oa.x-=nx*push;oa.y-=ny*push;ob.x+=nx*push;ob.y+=ny*push}}for(const u of us){const o=offset.get(u.id)!;u.x=Math.max(15,Math.min(w-15,u.x+o.x));u.y=Math.max(70,Math.min(h-15,u.y+o.y))}}
 private kill(e:UnitState|BuildingState){if(this.isBuilding(e)){this.state.buildings=this.state.buildings.filter(x=>x.id!==e.id);if(e.kind==='town'){const f=this.faction(e.factionId);f.defeated=true;this.emit('defeat',e.factionId,e.id)}}else this.state.units=this.state.units.filter(x=>x.id!==e.id);this.orders.delete(e.id);this.emit('death',e.factionId,e.id,e.x,e.y)}
 private checkVictory(){const alive=this.state.factions.filter(f=>!f.defeated);if(alive.length===1&&this.state.factions.length>1){this.state.phase='ended';this.state.winner=alive[0].id;this.emit('victory',alive[0].id)}}
 visibleState(factionId:FactionId):GameState{const ownUnits=this.state.units.filter(u=>u.factionId===factionId),ownBuildings=this.state.buildings.filter(b=>b.factionId===factionId),visible=(p:Point)=>ownUnits.some(u=>this.distance(u,p)<=UNIT[u.kind].sight)||ownBuildings.some(b=>this.distance(b,p)<=300),explored=new Set(this.state.fog[factionId]??[]),wasExplored=(p:Point)=>explored.has(this.fogKey(p.x,p.y));return{...structuredClone(this.state),units:this.state.units.filter(u=>u.factionId===factionId||visible(u)).map(x=>({...x})),buildings:this.state.buildings.filter(b=>b.factionId===factionId||visible(b)).map(x=>({...x})),map:{...this.state.map,resources:this.state.map.resources.filter(r=>wasExplored(r)).map(x=>({...x}))},fog:{[factionId]:[...explored]}}}
 private updateFog(){const w=this.state.map.width,h=this.state.map.height;for(const faction of this.state.factions){const explored=new Set(this.state.fog[faction.id]??[]),scouts=[...this.state.units.filter(u=>u.factionId===faction.id),...this.state.buildings.filter(b=>b.factionId===faction.id&&b.progress>=1)];for(const scout of scouts){const sight='kind'in scout&&'nextAttackAt'in scout?UNIT[scout.kind].sight:300,minX=Math.floor((scout.x-sight)/120),maxX=Math.ceil((scout.x+sight)/120),minY=Math.floor((scout.y-sight)/120),maxY=Math.ceil((scout.y+sight)/120);for(let y=minY;y<=maxY;y++)for(let x=minX;x<=maxX;x++){const px=x*120+60,py=y*120+60;if(px>=0&&py>=0&&px<w&&py<h&&Math.hypot(px-scout.x,py-scout.y)<=sight)explored.add(`${x}:${y}`)}}this.state.fog[faction.id]=[...explored]}}
 private fogKey(x:number,y:number){return`${Math.floor(x/120)}:${Math.floor(y/120)}`}
 private entity(id:number){return this.state.units.find(x=>x.id===id)||this.state.buildings.find(x=>x.id===id)}
 private isBuilding(x:UnitState|BuildingState):x is BuildingState{return'progress'in x}
 private distance(a:Point,b:Point){return Math.hypot(a.x-b.x,a.y-b.y)}
 private population(id:FactionId){return this.state.units.filter(x=>x.factionId===id).length}
 private faction(id:FactionId){const faction=this.state.factions.find(x=>x.id===id);if(!faction)throw new Error(`Unknown faction ${id}`);return faction}
 private validPoint(p:Point){return Number.isFinite(p.x)&&Number.isFinite(p.y)&&p.x>=0&&p.x<=this.state.map.width&&p.y>=60&&p.y<=this.state.map.height}
 private canPlace(x:number,y:number,r:number){return!this.state.buildings.some(b=>this.distance({x,y},b)<r+BUILDING[b.kind].radius+20)&&!this.state.map.resources.some(n=>n.amount>0&&this.distance({x,y},n)<r+30)}
 private pay(f:FactionState,c:[number,number,number]){if(f.wood<c[0]||f.food<c[1]||f.gold<c[2])return false;f.wood-=c[0];f.food-=c[1];f.gold-=c[2];return true}
 private emit(type:any,factionId?:FactionId,entityId?:number,x?:number,y?:number){this.state.events.push({id:this.eventId++,type,factionId,entityId,x,y})}
}
