import type {FactionId,GameCommand,ResourceKind} from '../shared/protocol.ts';
import {GameEngine} from '../engine/game-engine.ts';

export class CpuController{
 private nextThink=0;
 constructor(public factionId:FactionId){}
 update(engine:GameEngine){const s=engine.state;if(s.timeMs<this.nextThink||s.phase!=='playing'||s.factions.find(f=>f.id===this.factionId)!.defeated)return;this.nextThink=s.timeMs+1200;const f=s.factions.find(f=>f.id===this.factionId)!,workers=s.units.filter(u=>u.factionId===this.factionId&&u.kind==='villager'),army=s.units.filter(u=>u.factionId===this.factionId&&u.kind!=='villager'),town=s.buildings.find(b=>b.factionId===this.factionId&&b.kind==='town'),queued=s.buildings.filter(b=>b.factionId===this.factionId).flatMap(b=>b.trainingQueue??[]),barracks=s.buildings.find(b=>b.factionId===this.factionId&&b.kind==='barracks'&&b.progress>=1);for(const worker of workers){const kind:ResourceKind=f.food<250?'food':f.wood<220?'wood':'gold',r=s.map.resources.filter(x=>x.kind===kind&&x.amount>0).sort((a,b)=>Math.hypot(a.x-worker.x,a.y-worker.y)-Math.hypot(b.x-worker.x,b.y-worker.y))[0];if(r)this.send(engine,{type:'GATHER',unitIds:[worker.id],targetId:r.id})}if(town&&workers.length+queued.filter(x=>x.kind==='villager').length<8&&s.units.filter(u=>u.factionId===this.factionId).length<f.popCap)this.send(engine,{type:'TRAIN',buildingId:town.id,unit:'villager'});if(f.popCap-s.units.filter(u=>u.factionId===this.factionId).length<3&&f.wood>=80&&workers[0])this.send(engine,{type:'BUILD',builderIds:[workers[0].id],building:'house',x:town!.x+170,y:town!.y+((s.tick/10)%3)*100-100});if(!barracks&&f.wood>=140&&workers[1])this.send(engine,{type:'BUILD',builderIds:[workers[1].id],building:'barracks',x:town!.x,y:town!.y+190});if(barracks&&army.length+queued.filter(x=>x.kind!=='villager').length<12)this.send(engine,{type:'TRAIN',buildingId:barracks.id,unit:f.age>=2?'archer':'soldier'});if(army.length>=3){const target=s.buildings.filter(b=>b.factionId!==this.factionId&&!s.factions.find(f=>f.id===b.factionId)?.defeated).sort((a,b)=>Math.hypot(a.x-army[0].x,a.y-army[0].y)-Math.hypot(b.x-army[0].x,b.y-army[0].y))[0];if(target)this.send(engine,{type:'ATTACK',unitIds:army.map(x=>x.id),targetId:target.id})}}
 private send(engine:GameEngine,command:GameCommand){engine.command(this.factionId,command)}
}
