import {GameEngine} from '../src/engine/game-engine';
import {CpuController} from '../src/ai/cpu-controller';
import {PROTOCOL_VERSION,type ClientMessage,type FactionId,type LobbySlot,type LobbyState,type ServerMessage,type SlotKind} from '../src/shared/protocol';

interface Env {GAME_ROOMS:DurableObjectNamespace}
interface Attachment {playerId:string;sessionToken:string;factionId:FactionId}
interface Session {playerId:string;sessionToken:string;factionId:FactionId;lastSeen:number;cpuTaken:boolean;lastSequence:number}
const ALLOWED_ORIGINS=['https://frontier-command.pages.dev','http://localhost:5173','http://127.0.0.1:5173'];
const json=(body:unknown,status=200,origin?:string)=>new Response(JSON.stringify(body),{status,headers:{'content-type':'application/json','access-control-allow-origin':origin&&ALLOWED_ORIGINS.includes(origin)?origin:ALLOWED_ORIGINS[0],'vary':'Origin'}});
const roomCode=()=>{const chars='23456789ABCDEFGHJKLMNPQRSTUVWXYZ',bytes=crypto.getRandomValues(new Uint8Array(6));return Array.from(bytes,b=>chars[b%chars.length]).join('')};

export default {async fetch(request:Request,env:Env){const url=new URL(request.url),origin=request.headers.get('Origin')??'';if(request.method==='OPTIONS')return new Response(null,{headers:{'access-control-allow-origin':ALLOWED_ORIGINS.includes(origin)?origin:ALLOWED_ORIGINS[0],'access-control-allow-methods':'GET,POST,OPTIONS','access-control-allow-headers':'content-type'}});if(!ALLOWED_ORIGINS.includes(origin)&&origin)return json({error:'ORIGIN_NOT_ALLOWED'},403);if(request.method==='POST'&&url.pathname==='/rooms'){const code=roomCode(),id=env.GAME_ROOMS.idFromName(code),stub=env.GAME_ROOMS.get(id);await stub.fetch(new Request(`https://room.internal/init?room=${code}`,{method:'POST'}));return json({roomId:code},201,origin)}const match=url.pathname.match(/^\/rooms\/([A-Z2-9]{6})$/);if(!match)return json({error:'NOT_FOUND'},404,origin);const id=env.GAME_ROOMS.idFromName(match[1]),stub=env.GAME_ROOMS.get(id);return stub.fetch(new Request(`https://room.internal/connect?room=${match[1]}`,request))}};

export class GameRoom{
 private roomId='';private lobby!:LobbyState;private sessions=new Map<string,Session>();private engine?:GameEngine;private cpus:CpuController[]=[];private loop?:ReturnType<typeof setInterval>;private lastTick=Date.now();private lastSnapshot=0;private metrics={total:0,worst:0,count:0};private rates=new Map<string,{at:number,count:number,strikes:number}>();
 constructor(private ctx:DurableObjectState){ctx.blockConcurrencyWhile(async()=>{const saved=await ctx.storage.get<any>('room');if(saved){this.roomId=saved.roomId;this.lobby=saved.lobby;this.sessions=new Map(saved.sessions??[]);for(const session of this.sessions.values())session.lastSequence??=0;if(saved.game)this.engine=GameEngine.restore(saved.game);if(this.engine){this.cpus=this.engine.state.factions.filter(f=>f.kind==='cpu').map(f=>new CpuController(f.id));if(this.engine.state.phase==='countdown'||this.engine.state.phase==='playing')this.startLoop()}}for(const ws of ctx.getWebSockets()){const a=ws.deserializeAttachment() as Attachment|undefined;if(a)this.markConnected(a.playerId,true)}})}
 async fetch(request:Request){const url=new URL(request.url);if(request.method==='POST'&&url.pathname==='/init'){if(!this.roomId){this.roomId=url.searchParams.get('room')!;this.lobby={roomId:this.roomId,phase:'lobby',mapSeed:crypto.getRandomValues(new Uint32Array(1))[0],slots:[0,1,2,3].map(i=>({index:i as FactionId,kind:'OPEN',ready:false,host:false,connected:false}))};await this.save()}return json({ok:true})}if(request.headers.get('Upgrade')!=='websocket'||!this.roomId)return json({error:'ROOM_NOT_FOUND'},404);const pair=new WebSocketPair(),client=pair[0],server=pair[1];this.ctx.acceptWebSocket(server);return new Response(null,{status:101,webSocket:client})}
 async webSocketMessage(ws:WebSocket,data:string|ArrayBuffer){if(typeof data!=='string'||data.length>16384){ws.close(1009,'Payload too large');return}let msg:ClientMessage;try{msg=JSON.parse(data)}catch{this.error(ws,'INVALID_JSON','不正な通信です。');return}if(msg.version!==PROTOCOL_VERSION){this.error(ws,'VERSION_MISMATCH','ゲームが更新されました。ページを再読み込みしてください。');return}if(msg.roomId!==this.roomId){this.error(ws,'ROOM_MISMATCH','ルームが一致しません。');return}if(msg.type==='HELLO'){await this.hello(ws,msg);return}const a=ws.deserializeAttachment() as Attachment|undefined;if(!a||a.playerId!==msg.playerId){this.error(ws,'NOT_AUTHENTICATED','再接続してください。');return}if(!this.allow(a.playerId)){this.error(ws,'RATE_LIMIT','操作が多すぎます。');return}const session=this.sessions.get(a.playerId);if(!session||session.sessionToken!==a.sessionToken)return;
  if(msg.sequence<=session.lastSequence){this.error(ws,'STALE_SEQUENCE','古い操作は無視されました。');return}session.lastSequence=msg.sequence;
  if(msg.type==='READY'&&this.lobby.phase==='lobby'){const slot=this.lobby.slots[a.factionId];slot.ready=!!msg.ready;await this.save();this.broadcastLobby();return}
  if(msg.type==='SET_SLOT'&&this.lobby.phase==='lobby'&&this.isHost(a.playerId)){const slot=this.lobby.slots[msg.slot];if(slot.kind==='HUMAN')return;slot.kind=msg.kind;slot.name=msg.kind==='CPU'?'CPU':undefined;slot.ready=msg.kind==='CPU';this.resetReady();await this.save();this.broadcastLobby();return}
  if(msg.type==='START'&&this.lobby.phase==='lobby'&&this.isHost(a.playerId)){const active=this.lobby.slots.filter(s=>s.kind==='HUMAN'||s.kind==='CPU');if(active.length<2||this.lobby.slots.some(s=>s.kind==='HUMAN'&&!s.host&&!s.ready)){this.error(ws,'NOT_READY','2勢力以上かつ全参加者のREADYが必要です。');return}this.startGame();return}
  if(msg.type==='COMMAND'&&this.engine){const result=this.engine.command(a.factionId,msg.command);if(!result.ok){console.log('COMMAND_REJECT',this.roomId,a.factionId,result.reason);this.error(ws,'COMMAND_REJECT',result.reason)}}
 }
 async webSocketClose(ws:WebSocket){const a=ws.deserializeAttachment() as Attachment|undefined;if(!a)return;const replaced=this.ctx.getWebSockets().some(other=>other!==ws&&(other.deserializeAttachment() as Attachment|undefined)?.playerId===a.playerId);if(replaced)return;this.markConnected(a.playerId,false);const s=this.sessions.get(a.playerId);if(s)s.lastSeen=Date.now();console.log('PLAYER_LEAVE',this.roomId,a.factionId);if(this.lobby.phase==='lobby'){this.removeLobbyPlayer(a.playerId);await this.save();this.broadcastLobby()}else await this.save()}
 webSocketError(ws:WebSocket,error:unknown){console.log('WEBSOCKET_ERROR',this.roomId,String(error));ws.close(1011,'WebSocket error')}
 private async hello(ws:WebSocket,msg:Extract<ClientMessage,{type:'HELLO'}>){const name=this.cleanName(msg.name);if(!name){this.error(ws,'INVALID_NAME','名前を1〜16文字で入力してください。');return}let session=[...this.sessions.values()].find(s=>s.sessionToken===msg.sessionToken&&!s.cpuTaken);if(session){for(const old of this.ctx.getWebSockets()){const a=old.deserializeAttachment() as Attachment|undefined;if(a?.playerId===session.playerId&&old!==ws){this.send(old,{version:PROTOCOL_VERSION,type:'KICKED',message:'別の画面から再接続されました。'});old.close(4001,'Replaced')}}console.log('RECONNECT',this.roomId,session.factionId)}else{if(this.lobby.phase!=='lobby'){this.error(ws,'GAME_STARTED','この対戦はすでに開始しています。');ws.close(4003,'Game started');return}const slot=this.lobby.slots.find(s=>s.kind==='OPEN');if(!slot){this.error(ws,'ROOM_FULL','このルームは満員です。');ws.close(4004,'Full');return}const playerId=crypto.randomUUID(),sessionToken=Array.from(crypto.getRandomValues(new Uint8Array(24)),b=>b.toString(16).padStart(2,'0')).join('');session={playerId,sessionToken,factionId:slot.index,lastSeen:Date.now(),cpuTaken:false,lastSequence:0};this.sessions.set(playerId,session);slot.kind='HUMAN';slot.playerId=playerId;slot.name=name;slot.connected=true;slot.host=!this.lobby.slots.some(s=>s.host);console.log('PLAYER_JOIN',this.roomId,slot.index)}session.lastSequence=msg.sequence;ws.serializeAttachment({playerId:session.playerId,sessionToken:session.sessionToken,factionId:session.factionId} satisfies Attachment);this.markConnected(session.playerId,true);this.send(ws,{version:PROTOCOL_VERSION,type:'WELCOME',roomId:this.roomId,playerId:session.playerId,sessionToken:session.sessionToken,factionId:session.factionId,lobby:this.lobby});if(this.engine)this.send(ws,{version:PROTOCOL_VERSION,type:'SNAPSHOT',state:this.engine.visibleState(session.factionId),you:session.factionId});await this.save();this.broadcastLobby()}
 private startGame(){const active=this.lobby.slots.filter(s=>s.kind==='HUMAN'||s.kind==='CPU');this.engine=new GameEngine(this.roomId,this.lobby.mapSeed,active.map(s=>({id:s.index,name:s.name??'CPU',kind:s.kind==='CPU'?'cpu':'human'})));this.lobby.phase='countdown';this.lobby.startAt=this.engine.state.startAt;this.cpus=active.flatMap(s=>s.kind==='CPU'?[new CpuController(s.index)]:[]);console.log('GAME_START',this.roomId,active.length);this.broadcastLobby();this.startLoop();void this.save()}
 private startLoop(){if(this.loop)return;this.lastTick=Date.now();this.loop=setInterval(()=>{if(!this.engine)return;const started=performance.now(),now=Date.now(),dt=Math.min(250,now-this.lastTick);this.lastTick=now;this.engine.tick(dt);for(const cpu of this.cpus)cpu.update(this.engine);this.takeoverDisconnected(now);if(this.engine.state.tick%2===0)this.broadcastState();if(now-this.lastSnapshot>=10000){this.lastSnapshot=now;void this.save()}const elapsed=performance.now()-started;this.metrics.total+=elapsed;this.metrics.count++;this.metrics.worst=Math.max(this.metrics.worst,elapsed);if(this.engine.state.tick%600===0)console.log('TICK_METRICS',this.roomId,{avg:this.metrics.total/this.metrics.count,worst:this.metrics.worst,entities:this.engine.state.units.length+this.engine.state.buildings.length,connections:this.ctx.getWebSockets().length});if(this.engine.state.phase==='ended'){this.lobby.phase='ended';console.log('GAME_END',this.roomId,this.engine.state.winner);clearInterval(this.loop);this.loop=undefined;void this.save()}},100)}
 private takeoverDisconnected(now:number){if(!this.engine)return;for(const s of this.sessions.values())if(!s.cpuTaken&&now-s.lastSeen>30000&&!this.lobby.slots[s.factionId].connected){s.cpuTaken=true;this.engine.state.factions.find(f=>f.id===s.factionId)!.kind='cpu';this.cpus.push(new CpuController(s.factionId));console.log('CPU_TAKEOVER',this.roomId,s.factionId)}}
 private broadcastState(){if(!this.engine)return;for(const ws of this.ctx.getWebSockets()){const a=ws.deserializeAttachment() as Attachment|undefined;if(a)this.send(ws,{version:PROTOCOL_VERSION,type:'STATE',state:this.engine.visibleState(a.factionId),you:a.factionId})}}
 private broadcastLobby(){for(const ws of this.ctx.getWebSockets())this.send(ws,{version:PROTOCOL_VERSION,type:'LOBBY',lobby:this.lobby})}
 private send(ws:WebSocket,msg:ServerMessage){try{ws.send(JSON.stringify(msg))}catch(error){console.log('WEBSOCKET_ERROR',this.roomId,String(error))}}
 private error(ws:WebSocket,code:string,message:string){this.send(ws,{version:PROTOCOL_VERSION,type:'ERROR',code,message})}
 private isHost(playerId:string){return this.lobby.slots.some(s=>s.playerId===playerId&&s.host)}
 private resetReady(){for(const s of this.lobby.slots)if(s.kind==='HUMAN'&&!s.host)s.ready=false}
 private markConnected(playerId:string,connected:boolean){const slot=this.lobby?.slots.find(s=>s.playerId===playerId);if(slot)slot.connected=connected;const session=this.sessions.get(playerId);if(session&&connected)session.lastSeen=Date.now()}
 private removeLobbyPlayer(playerId:string){const slot=this.lobby.slots.find(s=>s.playerId===playerId);if(!slot)return;const wasHost=slot.host;Object.assign(slot,{kind:'OPEN',playerId:undefined,name:undefined,ready:false,host:false,connected:false} satisfies Partial<LobbySlot>);this.sessions.delete(playerId);if(wasHost){const next=this.lobby.slots.find(s=>s.kind==='HUMAN');if(next)next.host=true}}
 private cleanName(value:string){return String(value??'').replace(/[<>\u0000-\u001f]/g,'').trim().slice(0,16)}
 private allow(playerId:string){const now=Date.now(),r=this.rates.get(playerId)??{at:now,count:0,strikes:0};if(now-r.at>=1000){r.at=now;r.count=0}r.count++;if(r.count>30)r.strikes++;this.rates.set(playerId,r);return r.count<=30}
 private async save(){await this.ctx.storage.put('room',{roomId:this.roomId,lobby:this.lobby,sessions:[...this.sessions.entries()],game:this.engine?.snapshot()})}
}
