import Phaser from 'phaser';
import './style.css';

type Owner='player'|'enemy';
type UnitType='villager'|'soldier'|'archer'|'cavalry';
type ResourceKind='wood'|'food'|'gold';
type BuildingKind='town'|'house'|'barracks';
type Tech='attack'|'economy'|'armor';
interface Faction{wood:number;food:number;gold:number;popCap:number;age:number;attackBonus:number;gatherBonus:number;armorBonus:number;researched:Set<Tech>}
interface Unit{id:number;owner:Owner;type:UnitType;x:number;y:number;hp:number;maxHp:number;speed:number;damage:number;range:number;sight:number;selected:boolean;target?:{x:number;y:number};resource?:ResourceNode;returning:boolean;cargoKind?:ResourceKind;cargo:number;attack?:AttackTarget;build?:Building;nextAttack:number;shape:Phaser.GameObjects.Container;ring:Phaser.GameObjects.Arc;hpBack:Phaser.GameObjects.Rectangle;hpBar:Phaser.GameObjects.Rectangle;label:Phaser.GameObjects.Text}
interface ResourceNode{id:number;kind:ResourceKind;x:number;y:number;amount:number;shape:Phaser.GameObjects.Container;label:Phaser.GameObjects.Text}
interface Building{id:number;owner:Owner;kind:BuildingKind;x:number;y:number;hp:number;maxHp:number;progress:number;shape:Phaser.GameObjects.Container;label:Phaser.GameObjects.Text;hpBack:Phaser.GameObjects.Rectangle;hpBar:Phaser.GameObjects.Rectangle}
type AttackTarget=Unit|Building;
const WORLD_W=2400,WORLD_H=1600,UI_TOP=58;
const ages=['暗黒の時代','領主の時代','城主の時代','帝王の時代'];
const player:Faction={wood:260,food:500,gold:260,popCap:10,age:1,attackBonus:0,gatherBonus:0,armorBonus:0,researched:new Set()};
const enemy:Faction={wood:240,food:420,gold:220,popCap:10,age:1,attackBonus:0,gatherBonus:0,armorBonus:0,researched:new Set()};

document.querySelector<HTMLDivElement>('#app')!.innerHTML=`
<div id="topbar"><div class="brand">FRONTIER COMMAND</div><div class="age"><span id="age">暗黒の時代</span></div><div class="res wood"><i></i>木 <span id="wood">0</span></div><div class="res food"><i></i>食 <span id="food">0</span></div><div class="res gold"><i></i>金 <span id="gold">0</span></div><div class="res pop"><i></i>人口 <span id="pop">0</span></div></div>
<div id="help"><span class="desktopHelp">左ドラッグ：範囲選択　右クリック：移動 / 採集 / 攻撃<br>WASD・画面端：カメラ移動　ホイール：拡大縮小</span><span class="mobileHelp">味方をタップして選択 → 地面・資源・敵をタップ<br>画面ドラッグ：移動　＋/－：拡大縮小</span></div>
<div id="objective"><strong>目標</strong><span id="goal">経済を育て、敵の軍を倒す</span></div><div id="status"></div>
<div id="zoom"><button type="button" id="zoomOut" aria-label="縮小">−</button><output id="zoomValue">85%</output><button type="button" id="zoomIn" aria-label="拡大">＋</button></div>
<div id="actions"><button id="villager"><b class="actionIcon">農</b>町人を生産<small>食料 50</small></button><button id="house"><b class="actionIcon">家</b>家を建てる<small>木材 80 / 人口 +5</small></button><button id="barracks"><b class="actionIcon">営</b>兵舎を建てる<small>木材 140</small></button><button id="soldier"><b class="actionIcon">槍</b>槍兵を生産<small>食60・金30</small></button><button id="archer"><b class="actionIcon">弓</b>弓兵を生産<small>領主 / 食45・金45</small></button><button id="cavalry"><b class="actionIcon">騎</b>騎兵を生産<small>城主 / 食80・金70</small></button><button id="advance"><b class="actionIcon">代</b>時代進化<small id="advanceCost">食300・金150</small></button><button id="attackTech"><b class="actionIcon">攻</b>武器研究<small>領主 / 木150・金100</small></button><button id="economyTech"><b class="actionIcon">採</b>採集研究<small>領主 / 木120・食100</small></button><button id="armorTech"><b class="actionIcon">防</b>防具研究<small>城主 / 木180・金140</small></button></div>
<div id="resultOverlay" aria-hidden="true"><section id="resultCard"><div id="resultBadge">戦闘終了</div><h1 id="resultTitle">勝利</h1><p id="resultWinner"></p><dl><div><dt>経過時間</dt><dd id="resultTime">00:00</dd></div><div><dt>到達時代</dt><dd id="resultAge">暗黒の時代</dd></div></dl><button type="button" id="restart">もう一度プレイする</button></section></div>`;

class GameScene extends Phaser.Scene{
 units:Unit[]=[];resources:ResourceNode[]=[];buildings:Building[]=[];fog:Phaser.GameObjects.Rectangle[]=[];nextId=1;selectStart?:Phaser.Math.Vector2;selectBox?:Phaser.GameObjects.Rectangle;placing?:BuildingKind;keys!:Record<string,Phaser.Input.Keyboard.Key>;lastFog=0;lastAi=0;lastAuto=0;startTime=0;result='';statusTimer?:number;touchStart?:{sx:number;sy:number;wx:number;wy:number;cx:number;cy:number;moved:boolean};pinch?:{distance:number;zoom:number;worldX:number;worldY:number};suppressTouch=false;
 create(){this.startTime=this.time.now;this.cameras.main.setBounds(0,0,WORLD_W,WORLD_H).setZoom(.85);this.input.mouse?.disableContextMenu();this.input.addPointer(2);this.drawMap();this.addBuilding('town','player',420,760,1);[[500,700],[505,760],[500,820],[565,735],[565,795]].forEach(p=>this.addUnit('villager','player',p[0],p[1]));this.addBuilding('town','enemy',2000,760,1);[[1900,690],[1900,755],[1900,820],[1960,850]].forEach(p=>this.addUnit('villager','enemy',p[0],p[1]));for(let i=0;i<20;i++)this.addResource('wood',650+Math.random()*1100,150+Math.random()*430);for(let i=0;i<14;i++)this.addResource('food',620+Math.random()*1200,880+Math.random()*500);for(let i=0;i<12;i++)this.addResource('gold',950+Math.random()*900,560+Math.random()*760);this.keys=this.input.keyboard!.addKeys('W,A,S,D,UP,DOWN,LEFT,RIGHT') as Record<string,Phaser.Input.Keyboard.Key>;this.input.on('pointerdown',(p:Phaser.Input.Pointer)=>this.onDown(p));this.input.on('pointermove',(p:Phaser.Input.Pointer)=>this.onMove(p));this.input.on('pointerup',(p:Phaser.Input.Pointer)=>this.onUp(p));this.input.on('wheel',(_p:Phaser.Input.Pointer,_o:unknown,_dx:number,dy:number)=>this.setZoom(this.cameras.main.zoom-dy*.0005));const click=(id:string,fn:()=>void)=>document.querySelector(id)!.addEventListener('click',e=>{e.stopPropagation();fn()});click('#villager',()=>this.train('villager','player'));click('#house',()=>this.beginPlace('house'));click('#barracks',()=>this.beginPlace('barracks'));click('#soldier',()=>this.train('soldier','player'));click('#archer',()=>this.train('archer','player'));click('#cavalry',()=>this.train('cavalry','player'));click('#advance',()=>this.advanceAge());click('#attackTech',()=>this.research('attack'));click('#economyTech',()=>this.research('economy'));click('#armorTech',()=>this.research('armor'));click('#restart',()=>window.location.reload());this.bindZoom('#zoomIn',.1);this.bindZoom('#zoomOut',-.1);this.createFog();this.updateFog();this.setZoom(.85);this.time.delayedCall(160,()=>{const c=this.cameras.main;c.scrollX=Math.max(0,550-this.scale.width/(2*c.zoom));c.scrollY=Math.max(0,720-this.scale.height/(2*c.zoom))});this.refreshUi();if(['localhost','127.0.0.1'].includes(location.hostname)){const params=new URLSearchParams(location.search);if(params.has('showResult'))this.time.delayedCall(150,()=>this.finish('player'));if(params.has('testCombat')){for(let i=0;i<6;i++)this.addUnit('soldier','player',650,760);const town=this.buildings.find(b=>b.owner==='player'&&b.kind==='town')!;town.hp=town.maxHp*.42;this.syncBuilding(town)}}}
 drawMap(){const g=this.add.graphics().setDepth(-20);g.fillStyle(0x91a966).fillRect(0,0,WORLD_W,WORLD_H);g.fillStyle(0x839b5c,.75);for(let y=40;y<WORLD_H;y+=90)for(let x=40;x<WORLD_W;x+=90)if((x+y)%270)g.fillCircle(x+Math.random()*35,y+Math.random()*35,10+Math.random()*20);g.lineStyle(170,0x4e91ad,1);new Phaser.Curves.Path(-100,215).splineTo([new Phaser.Math.Vector2(420,265),new Phaser.Math.Vector2(910,185),new Phaser.Math.Vector2(1460,260),new Phaser.Math.Vector2(1960,165),new Phaser.Math.Vector2(2500,235)]).draw(g,80);g.lineStyle(116,0x69acc2,.8);new Phaser.Curves.Path(-100,215).splineTo([new Phaser.Math.Vector2(420,265),new Phaser.Math.Vector2(910,185),new Phaser.Math.Vector2(1460,260),new Phaser.Math.Vector2(1960,165),new Phaser.Math.Vector2(2500,235)]).draw(g,80);g.lineStyle(62,0xb99b68,.72);new Phaser.Curves.Path(120,1320).splineTo([new Phaser.Math.Vector2(430,760),new Phaser.Math.Vector2(900,780),new Phaser.Math.Vector2(1430,690),new Phaser.Math.Vector2(1970,760),new Phaser.Math.Vector2(2300,1180)]).draw(g,70);g.lineStyle(34,0xd1b57d,.7);new Phaser.Curves.Path(120,1320).splineTo([new Phaser.Math.Vector2(430,760),new Phaser.Math.Vector2(900,780),new Phaser.Math.Vector2(1430,690),new Phaser.Math.Vector2(1970,760),new Phaser.Math.Vector2(2300,1180)]).draw(g,70);g.fillStyle(0x6e8753,.6);for(let i=0;i<120;i++)g.fillCircle(Math.random()*WORLD_W,340+Math.random()*(WORLD_H-340),2+Math.random()*5)}
 faction(o:Owner){return o==='player'?player:enemy}
 makeUnitVisual(type:UnitType,owner:Owner,x:number,y:number){const team=owner==='player'?0x3978bd:0xb8473f,trim=owner==='player'?0xd7e9f5:0xf1c2aa,parts:Phaser.GameObjects.GameObject[]=[];parts.push(this.add.ellipse(0,13,type==='cavalry'?42:28,10,0x203022,.28));if(type==='cavalry'){parts.push(this.add.ellipse(-2,3,34,18,0x765037).setStrokeStyle(2,0x3e2c24),this.add.rectangle(-11,13,4,13,0x4b3528),this.add.rectangle(8,13,4,13,0x4b3528),this.add.circle(15,-1,7,0x765037));parts.push(this.add.rectangle(-4,-8,14,17,team).setStrokeStyle(2,0x26313a),this.add.circle(-4,-19,7,0xe2b88a),this.add.rectangle(6,-13,3,30,trim).setRotation(-.45))}else{parts.push(this.add.rectangle(-5,8,5,12,0x3d332b),this.add.rectangle(5,8,5,12,0x3d332b),this.add.rectangle(0,-1,type==='villager'?16:19,22,team).setStrokeStyle(2,0x29362c),this.add.circle(0,-16,7,0xe4b98a));if(type==='villager')parts.push(this.add.ellipse(0,-20,20,6,0xc69a52),this.add.rectangle(11,0,3,25,0x6f4b2d).setRotation(.55),this.add.rectangle(16,-9,11,6,0x99a7a0).setRotation(.55));if(type==='soldier')parts.push(this.add.triangle(0,-21,-9,7,9,7,0,-7,0xaeb9b8),this.add.rectangle(11,-2,3,38,trim).setRotation(-.25));if(type==='archer')parts.push(this.add.arc(8,-2,11,-78,78,false,0,0).setStrokeStyle(3,0xd4b16f),this.add.rectangle(7,-2,2,23,0xd9c59b).setRotation(-.05))}return this.add.container(x,y,parts).setDepth(10)}
 addUnit(type:UnitType,owner:Owner,x:number,y:number){const stats={villager:[70,88,3,22,180],soldier:[120,100,18,38,235],archer:[78,94,14,155,280],cavalry:[165,138,23,42,260]}[type];const ring=this.add.circle(x,y,type==='cavalry'?25:20).setStrokeStyle(3,0xffe27a).setVisible(false).setDepth(9);const shape=this.makeUnitVisual(type,owner,x,y),hpBack=this.add.rectangle(x,y-31,32,6,0x251d1b,.9).setOrigin(0,.5).setDepth(11).setVisible(type!=='villager'),hpBar=this.add.rectangle(x,y-31,32,4,owner==='player'?0x56c65e:0xe35d52).setOrigin(0,.5).setDepth(12).setVisible(type!=='villager');const names={villager:'町',soldier:'槍',archer:'弓',cavalry:'騎'};const label=this.add.text(x,y+20,names[type],{fontSize:'9px',color:'#fff',stroke:'#111',strokeThickness:2}).setOrigin(.5,0).setDepth(11);this.units.push({id:this.nextId++,owner,type,x,y,hp:stats[0],maxHp:stats[0],speed:stats[1],damage:stats[2],range:stats[3],sight:stats[4],selected:false,returning:false,cargo:0,nextAttack:0,shape,ring,hpBack,hpBar,label})}
 addResource(kind:ResourceKind,x:number,y:number){const parts:Phaser.GameObjects.GameObject[]=[this.add.ellipse(0,15,42,13,0x203022,.22)];if(kind==='wood')parts.push(this.add.rectangle(0,8,10,31,0x704628),this.add.circle(-11,-7,16,0x376b3b).setStrokeStyle(2,0x294c2c),this.add.circle(10,-10,18,0x447c43).setStrokeStyle(2,0x294c2c),this.add.circle(0,-23,15,0x4d884b).setStrokeStyle(2,0x294c2c));if(kind==='food')parts.push(this.add.ellipse(0,5,37,25,0x507f3d).setStrokeStyle(2,0x34562d),this.add.circle(-9,0,4,0xd94e3e),this.add.circle(4,-5,4,0xe56a43),this.add.circle(11,5,4,0xd94e3e));if(kind==='gold')parts.push(this.add.triangle(-9,5,-14,13,0,-15,12,13,0xd9af42).setStrokeStyle(2,0x7d6329),this.add.triangle(10,7,-12,12,0,-12,12,12,0xf0c85c).setStrokeStyle(2,0x7d6329));const shape=this.add.container(x,y,parts).setDepth(3);const label=this.add.text(x,y+28,kind==='wood'?'木':kind==='food'?'食':'金',{fontSize:'10px',color:'#fff8df',backgroundColor:'#172018cc',padding:{x:4,y:2}}).setOrigin(.5,0).setDepth(4);this.resources.push({id:this.nextId++,kind,x,y,amount:kind==='wood'?520:380,shape,label})}
 addBuilding(kind:BuildingKind,owner:Owner,x:number,y:number,progress=0){const size=kind==='town'?124:kind==='barracks'?104:76,friendly=owner==='player',team=friendly?0x3978bd:0xb8473f,wall=kind==='town'?0xc4b58d:0xd0bd91,roof=friendly?0x35689d:0x8f4038,maxHp=kind==='town'?1200:kind==='barracks'?700:450,parts:Phaser.GameObjects.GameObject[]=[];parts.push(this.add.ellipse(0,size*.28,size*1.1,size*.28,0x263126,.27),this.add.rectangle(0,5,size,size*.58,wall).setStrokeStyle(3,0x5b4a35),this.add.rectangle(0,-size*.24,size*1.08,size*.24,roof).setStrokeStyle(3,0x3e352e),this.add.rectangle(0,size*.13,size*.17,size*.3,0x533923),this.add.rectangle(-size*.28,4,size*.13,size*.16,0x83b7ce).setStrokeStyle(2,0xf0d991),this.add.rectangle(size*.3,4,size*.12,size*.16,0x83b7ce).setStrokeStyle(2,0xf0d991));if(kind==='town')parts.push(this.add.rectangle(0,-size*.27,size*.28,size*.46,wall).setStrokeStyle(3,0x5b4a35),this.add.rectangle(0,-size*.51,size*.34,size*.15,roof).setStrokeStyle(2,0x3e352e),this.add.rectangle(size*.18,-size*.28,8,34,team));if(kind==='barracks')parts.push(this.add.rectangle(size*.28,-5,8,42,team),this.add.circle(size*.28,-28,6,team));const shape=this.add.container(x,y,parts).setDepth(5).setAlpha(progress<1?.42:1);const names={town:'町の中心',house:'家',barracks:'兵舎'},label=this.add.text(x,y+size*.35,names[kind],{fontSize:'12px',fontStyle:'bold',color:'#fff4d3',backgroundColor:'#172018bb',padding:{x:5,y:2},stroke:'#201a13',strokeThickness:2}).setOrigin(.5).setDepth(6),hpBack=this.add.rectangle(x-size*.42,y-size*.55,size*.84,7,0x251d1b,.9).setOrigin(0,.5).setDepth(7),hpBar=this.add.rectangle(x-size*.42,y-size*.55,size*.84,5,friendly?0x69c56d:0xdc5a50).setOrigin(0,.5).setDepth(8);const b:Building={id:this.nextId++,owner,kind,x,y,hp:progress<1?1:maxHp,maxHp,progress,shape,label,hpBack,hpBar};this.buildings.push(b);this.syncBuilding(b);return b}
 createFog(){for(let y=60;y<WORLD_H;y+=100)for(let x=50;x<WORLD_W;x+=100)this.fog.push(this.add.rectangle(x,y,100,100,0x080c09,.91).setDepth(50))}
 bindZoom(selector:string,step:number){document.querySelector(selector)!.addEventListener('pointerdown',e=>{e.preventDefault();e.stopPropagation();this.setZoom(this.cameras.main.zoom+step)})}
 setZoom(z:number,snap=true){const zoom=Phaser.Math.Clamp(snap?Math.round(z*20)/20:z,.55,1.25);this.cameras.main.setZoom(zoom);const value=document.querySelector<HTMLOutputElement>('#zoomValue');if(value)value.value=`${Math.round(zoom*100)}%`}
 activeTouches(){return this.input.manager.pointers.filter(pointer=>pointer.isDown&&pointer.wasTouch)}
 beginPinch(touches:Phaser.Input.Pointer[]){const [a,b]=touches,midX=(a.x+b.x)/2,midY=(a.y+b.y)/2,world=this.cameras.main.getWorldPoint(midX,midY);this.pinch={distance:Math.max(1,Phaser.Math.Distance.Between(a.x,a.y,b.x,b.y)),zoom:this.cameras.main.zoom,worldX:world.x,worldY:world.y};this.touchStart=undefined;this.suppressTouch=true}
 onDown(p:Phaser.Input.Pointer){if(p.y<UI_TOP)return;const w=new Phaser.Math.Vector2(p.worldX,p.worldY);if(p.wasTouch){const touches=this.activeTouches();if(touches.length>=2){this.beginPinch(touches);return}if(this.suppressTouch)return;const c=this.cameras.main;this.touchStart={sx:p.x,sy:p.y,wx:w.x,wy:w.y,cx:c.scrollX,cy:c.scrollY,moved:false};return}if(p.rightButtonDown()){this.command(w.x,w.y);return}if(this.placing){this.place(w.x,w.y);return}this.selectStart=w;this.selectBox=this.add.rectangle(w.x,w.y,1,1,0x8fb7d0,.18).setStrokeStyle(2,0xd3e9f5).setOrigin(0).setDepth(45)}
 onMove(p:Phaser.Input.Pointer){if(p.wasTouch){const touches=this.activeTouches();if(touches.length>=2){if(!this.pinch)this.beginPinch(touches);const [a,b]=touches,midX=(a.x+b.x)/2,midY=(a.y+b.y)/2,c=this.cameras.main;this.setZoom(this.pinch!.zoom*Phaser.Math.Distance.Between(a.x,a.y,b.x,b.y)/this.pinch!.distance,false);const world=c.getWorldPoint(midX,midY);c.scrollX+=this.pinch!.worldX-world.x;c.scrollY+=this.pinch!.worldY-world.y;return}if(this.suppressTouch)return}if(this.touchStart&&p.isDown){const t=this.touchStart,dx=p.x-t.sx,dy=p.y-t.sy;if(Math.hypot(dx,dy)>9)t.moved=true;if(t.moved){const c=this.cameras.main;c.scrollX=t.cx-dx/c.zoom;c.scrollY=t.cy-dy/c.zoom}return}if(!this.selectStart||!this.selectBox)return;const w=new Phaser.Math.Vector2(p.worldX,p.worldY),x=Math.min(w.x,this.selectStart.x),y=Math.min(w.y,this.selectStart.y);this.selectBox.setPosition(x,y).setSize(Math.abs(w.x-this.selectStart.x),Math.abs(w.y-this.selectStart.y))}
 onUp(p:Phaser.Input.Pointer){if(p.wasTouch&&(this.pinch||this.suppressTouch)){this.pinch=undefined;this.touchStart=undefined;if(this.activeTouches().length===0)this.suppressTouch=false;return}if(this.touchStart){const t=this.touchStart;this.touchStart=undefined;if(!t.moved)this.handleTap(t.wx,t.wy);return}if(!this.selectStart)return;const w=new Phaser.Math.Vector2(p.worldX,p.worldY),d=Phaser.Math.Distance.Between(w.x,w.y,this.selectStart.x,this.selectStart.y);this.units.filter(u=>u.owner==='player').forEach(u=>{u.selected=d<8?Phaser.Math.Distance.Between(u.x,u.y,w.x,w.y)<25:u.x>=Math.min(w.x,this.selectStart!.x)&&u.x<=Math.max(w.x,this.selectStart!.x)&&u.y>=Math.min(w.y,this.selectStart!.y)&&u.y<=Math.max(w.y,this.selectStart!.y);u.ring.setVisible(u.selected)});this.selectStart=undefined;this.selectBox?.destroy();this.selectBox=undefined}
 handleTap(x:number,y:number){if(this.placing){this.place(x,y);return}const own=this.units.find(u=>u.owner==='player'&&Phaser.Math.Distance.Between(u.x,u.y,x,y)<28);if(own){this.units.filter(u=>u.owner==='player').forEach(u=>{u.selected=u===own;u.ring.setVisible(u.selected)});this.say(`${this.unitName(own.type)}を選択`);return}if(this.units.some(u=>u.selected&&u.owner==='player'))this.command(x,y)}
 command(x:number,y:number){const selected=this.units.filter(u=>u.selected&&u.owner==='player');if(!selected.length)return;const foe=this.units.find(u=>u.owner==='enemy'&&Phaser.Math.Distance.Between(u.x,u.y,x,y)<32),enemyBuilding=this.buildings.find(b=>b.owner==='enemy'&&Phaser.Math.Distance.Between(b.x,b.y,x,y)<(b.kind==='town'?82:b.kind==='barracks'?68:55)),res=this.resources.find(r=>Phaser.Math.Distance.Between(r.x,r.y,x,y)<38),attack=foe??enemyBuilding;selected.forEach((u,i)=>{u.build=undefined;u.attack=attack;u.resource=!attack&&u.type==='villager'?res:undefined;u.returning=false;if(!res){u.cargo=0;u.cargoKind=undefined}const t=attack??res;u.target=t?{x:t.x,y:t.y}:{x:x+(i%4)*30,y:y+Math.floor(i/4)*30}});this.say(attack?`${'kind'in attack?'敵の建物':'敵'}を攻撃します`:res?`${this.resourceName(res.kind)}を採集して町へ運びます`:'移動します')}
 beginPlace(kind:BuildingKind){const cost=kind==='house'?80:140;if(player.wood<cost){this.say('木材が足りません');return}if(!this.units.some(u=>u.selected&&u.owner==='player'&&u.type==='villager')){this.say('建設する町人を選択してください');return}this.placing=kind;this.say('建設場所をタップしてください')}
 place(x:number,y:number){const kind=this.placing!,cost=kind==='house'?80:140;if(x<80||y<110||x>WORLD_W-80||y>WORLD_H-80)return;player.wood-=cost;const b=this.addBuilding(kind,'player',x,y,0);this.units.filter(u=>u.selected&&u.type==='villager'&&u.owner==='player').forEach((u,i)=>{u.attack=undefined;u.resource=undefined;u.build=b;u.target={x:x+((i%3)-1)*24,y:y+55+Math.floor(i/3)*22}});this.placing=undefined;this.refreshUi();this.say(`${kind==='house'?'家':'兵舎'}の建設を開始します`)}
 train(type:UnitType,owner:Owner){const f=this.faction(owner),town=this.buildings.find(b=>b.owner===owner&&b.kind==='town'&&b.progress>=1),barracks=this.buildings.find(b=>b.owner===owner&&b.kind==='barracks'&&b.progress>=1),costs={villager:[0,50,0],soldier:[0,60,30],archer:[0,45,45],cavalry:[0,80,70]}[type],required=type==='archer'?2:type==='cavalry'?3:1,source=type==='villager'?town:barracks;if(f.age<required){if(owner==='player')this.say(`${ages[required-1]}が必要です`);return}if(!source){if(owner==='player')this.say(type==='villager'?'町の中心が必要です':'完成した兵舎が必要です');return}if(f.wood<costs[0]||f.food<costs[1]||f.gold<costs[2]){if(owner==='player')this.say('資源が足りません');return}if(this.units.filter(u=>u.owner===owner).length>=f.popCap){if(owner==='player')this.say('人口上限です。家を建ててください');return}f.wood-=costs[0];f.food-=costs[1];f.gold-=costs[2];if(owner==='player')this.say(`${this.unitName(type)}を訓練中…`);this.time.delayedCall(type==='cavalry'?3300:2300,()=>{if(!this.buildings.includes(source))return;this.addUnit(type,owner,source.x+(owner==='player'?75:-75),source.y+45);this.refreshUi();if(owner==='player')this.say(`${this.unitName(type)}が完成しました`)})}
 advanceAge(){if(player.age>=4){this.say('すでに帝王の時代です');return}const costs=[[300,150],[500,300],[800,500]][player.age-1];if(player.food<costs[0]||player.gold<costs[1]){this.say('時代進化に必要な資源が足りません');return}player.food-=costs[0];player.gold-=costs[1];player.age++;this.refreshUi();this.say(`${ages[player.age-1]}へ進化しました`)}
 research(tech:Tech){if(player.researched.has(tech)){this.say('研究済みです');return}const req=tech==='armor'?3:2;if(player.age<req){this.say(`${ages[req-1]}が必要です`);return}const costs={attack:[150,0,100],economy:[120,100,0],armor:[180,0,140]}[tech];if(player.wood<costs[0]||player.food<costs[1]||player.gold<costs[2]){this.say('研究に必要な資源が足りません');return}player.wood-=costs[0];player.food-=costs[1];player.gold-=costs[2];player.researched.add(tech);if(tech==='attack')player.attackBonus=.2;if(tech==='economy')player.gatherBonus=.25;if(tech==='armor'){player.armorBonus=.18;for(const u of this.units.filter(u=>u.owner==='player')){u.maxHp*=1.2;u.hp*=1.2}}this.refreshUi();this.say(`${tech==='attack'?'武器':tech==='economy'?'採集':'防具'}研究が完了しました`)}
 update(time:number,delta:number){if(this.result)return;const dt=Math.min(delta/1000,.05);this.moveCamera(dt);this.updateBuildings(dt);this.updateUnits(time,dt);if(time-this.lastAuto>450){this.autoAcquire();this.lastAuto=time}if(time-this.lastFog>240){this.updateFog();this.lastFog=time}if(time-this.lastAi>1800){this.enemyAi(time);this.lastAi=time}if(!this.buildings.some(b=>b.owner==='enemy'&&b.kind==='town'))this.finish('player');if(!this.buildings.some(b=>b.owner==='player'&&b.kind==='town'))this.finish('enemy');this.refreshUi()}
 moveCamera(dt:number){if(this.touchStart||this.pinch||this.suppressTouch)return;const c=this.cameras.main,p=this.input.activePointer,s=520*dt/c.zoom,edge=!p.wasTouch&&p.x>0&&p.y>0;let dx=0,dy=0;if(this.keys.A.isDown||this.keys.LEFT.isDown||(edge&&p.x<8))dx=-s;if(this.keys.D.isDown||this.keys.RIGHT.isDown||(edge&&p.x>this.scale.width-8))dx=s;if(this.keys.W.isDown||this.keys.UP.isDown||(edge&&p.y<UI_TOP+4))dy=-s;if(this.keys.S.isDown||this.keys.DOWN.isDown||(edge&&p.y>this.scale.height-8))dy=s;c.scrollX+=dx;c.scrollY+=dy}
 updateBuildings(dt:number){for(const b of this.buildings){if(b.progress<1){const builders=this.units.filter(u=>u.owner===b.owner&&u.type==='villager'&&u.build===b&&Phaser.Math.Distance.Between(u.x,u.y,b.x,b.y)<88);if(builders.length){b.progress=Math.min(1,b.progress+dt*.18*Math.min(builders.length,3));b.hp=Math.max(b.hp,b.maxHp*b.progress);b.shape.setAlpha(.38+.62*b.progress);b.label.setText(`${b.kind==='house'?'家':'兵舎'} ${Math.floor(b.progress*100)}%`);if(b.progress>=1){b.label.setText(b.kind==='house'?'家':'兵舎');if(b.kind==='house')this.faction(b.owner).popCap+=5;for(const u of builders){u.build=undefined;u.target=undefined}if(b.owner==='player')this.say(`${b.kind==='house'?'家':'兵舎'}が完成しました${b.kind==='house'?'。人口上限 +5':''}`)}}}this.syncBuilding(b)}}
 targetAlive(t:AttackTarget){return'type'in t?this.units.includes(t):this.buildings.includes(t)}
 targetRadius(t:AttackTarget){return'type'in t?0:t.kind==='town'?55:t.kind==='barracks'?46:34}
 updateUnits(time:number,dt:number){for(const u of [...this.units]){if(!this.units.includes(u))continue;if(u.attack&&!this.targetAlive(u.attack)){u.attack=undefined;u.target=undefined}if(u.resource&&!this.resources.includes(u.resource)&&!u.returning)u.resource=undefined;if(u.resource)this.updateGatherOrder(u,dt);if(u.attack)u.target={x:u.attack.x,y:u.attack.y};const action=u.attack??u.resource;if(u.target){const dist=Phaser.Math.Distance.Between(u.x,u.y,u.target.x,u.target.y),stop=u.attack?u.range+this.targetRadius(u.attack):u.resource?(u.returning?58:32):u.build?58:4;if(dist>stop){const a=Phaser.Math.Angle.Between(u.x,u.y,u.target.x,u.target.y);u.x+=Math.cos(a)*u.speed*dt;u.y+=Math.sin(a)*u.speed*dt}else if(!action&&!u.build)u.target=undefined}if(u.attack&&Phaser.Math.Distance.Between(u.x,u.y,u.attack.x,u.attack.y)<=u.range+this.targetRadius(u.attack)&&time>=u.nextAttack){u.nextAttack=time+(u.type==='archer'?900:u.type==='villager'?1050:700);this.dealDamage(u,u.attack)}}this.separateUnits();for(const u of this.units)this.syncUnit(u)}
 updateGatherOrder(u:Unit,dt:number){const r=u.resource!,town=this.buildings.find(b=>b.owner===u.owner&&b.kind==='town'&&b.progress>=1);if(!town){u.resource=undefined;return}if(u.returning){u.target={x:town.x,y:town.y};if(Phaser.Math.Distance.Between(u.x,u.y,town.x,town.y)<62){if(u.cargoKind)this.faction(u.owner)[u.cargoKind]+=u.cargo;u.cargo=0;u.cargoKind=undefined;u.returning=false;if(this.resources.includes(r))u.target={x:r.x,y:r.y};else{u.resource=undefined;u.target=undefined}}return}u.target={x:r.x,y:r.y};if(Phaser.Math.Distance.Between(u.x,u.y,r.x,r.y)<34){const qty=Math.min(r.amount,8*(1+this.faction(u.owner).gatherBonus)*dt,20-u.cargo);r.amount-=qty;u.cargo+=qty;u.cargoKind=r.kind;if(r.amount<=0){r.shape.destroy();r.label.destroy();this.resources=this.resources.filter(x=>x!==r)}if(u.cargo>=19.9||r.amount<=0)u.returning=true}}
 autoAcquire(){for(const u of this.units.filter(u=>u.type!=='villager'&&!u.attack&&!u.build)){let best:AttackTarget|undefined,dist=u.sight;for(const foe of this.units.filter(x=>x.owner!==u.owner)){const d=Phaser.Math.Distance.Between(u.x,u.y,foe.x,foe.y);if(d<dist){dist=d;best=foe}}if(!best)for(const b of this.buildings.filter(x=>x.owner!==u.owner&&x.progress>=1)){const d=Phaser.Math.Distance.Between(u.x,u.y,b.x,b.y)-this.targetRadius(b);if(d<dist){dist=d;best=b}}if(best){u.attack=best;u.target={x:best.x,y:best.y}}}}
 dealDamage(attacker:Unit,defender:AttackTarget){const counters:Record<UnitType,Partial<Record<UnitType,number>>>={villager:{},soldier:{cavalry:1.65},archer:{soldier:1.55},cavalry:{archer:1.75}},isUnit='type'in defender,mult=isUnit?(counters[attacker.type][defender.type]??1):attacker.type==='villager'?.65:1,raw=attacker.damage*(1+this.faction(attacker.owner).attackBonus)*mult;defender.hp-=raw*(1-this.faction(defender.owner).armorBonus);if(defender.hp<=0){if(isUnit)this.removeUnit(defender);else this.removeBuilding(defender);return}if(isUnit&&defender.type!=='villager'&&(!defender.attack||!this.targetAlive(defender.attack))){defender.attack=attacker;defender.resource=undefined;defender.target={x:attacker.x,y:attacker.y}}if(!isUnit)this.syncBuilding(defender)}
 removeUnit(u:Unit){u.shape.destroy();u.ring.destroy();u.hpBack.destroy();u.hpBar.destroy();u.label.destroy();this.units=this.units.filter(x=>x!==u);for(const x of this.units)if(x.attack===u){x.attack=undefined;x.target=undefined}}
 removeBuilding(b:Building){b.shape.destroy();b.label.destroy();b.hpBack.destroy();b.hpBar.destroy();this.buildings=this.buildings.filter(x=>x!==b);if(b.kind==='house'&&b.progress>=1)this.faction(b.owner).popCap=Math.max(10,this.faction(b.owner).popCap-5);for(const u of this.units){if(u.attack===b){u.attack=undefined;u.target=undefined}if(u.build===b){u.build=undefined;u.target=undefined}}if(b.owner==='player')this.say(`${b.kind==='town'?'町の中心':b.kind==='house'?'家':'兵舎'}が破壊されました`)}
 unitRadius(u:Unit){return u.type==='cavalry'?24:u.type==='villager'?14:17}
 separateUnits(){for(let pass=0;pass<3;pass++)for(let i=0;i<this.units.length;i++)for(let j=i+1;j<this.units.length;j++){const a=this.units[i],b=this.units[j],min=this.unitRadius(a)+this.unitRadius(b)+3,dx=b.x-a.x,dy=b.y-a.y,dist=Math.hypot(dx,dy);if(dist>=min)continue;const angle=dist>.01?Math.atan2(dy,dx):((a.id*37+b.id*17)%360)*Math.PI/180,push=(min-Math.max(dist,.01))/2+.15,px=Math.cos(angle)*push,py=Math.sin(angle)*push;a.x=Phaser.Math.Clamp(a.x-px,18,WORLD_W-18);a.y=Phaser.Math.Clamp(a.y-py,85,WORLD_H-18);b.x=Phaser.Math.Clamp(b.x+px,18,WORLD_W-18);b.y=Phaser.Math.Clamp(b.y+py,85,WORLD_H-18)}}
 enemyAi(time:number){const workers=this.units.filter(u=>u.owner==='enemy'&&u.type==='villager');for(const w of workers.filter(u=>!u.resource&&!u.build&&!u.attack)){const preferred=enemy.food<180?'food':enemy.wood<150?'wood':'gold',choices=this.resources.filter(r=>r.kind===preferred),r=choices.sort((a,b)=>Phaser.Math.Distance.Between(w.x,w.y,a.x,a.y)-Phaser.Math.Distance.Between(w.x,w.y,b.x,b.y))[0]??this.resources[0];if(r){w.resource=r;w.target={x:r.x,y:r.y}}}const count=this.units.filter(u=>u.owner==='enemy').length;if(enemy.popCap-count<=2&&enemy.wood>=80&&!this.buildings.some(b=>b.owner==='enemy'&&b.kind==='house'&&b.progress<1)){enemy.wood-=80;this.enemyBuild('house',2020+Math.random()*180,930+Math.random()*180)}if(!this.buildings.some(b=>b.owner==='enemy'&&b.kind==='barracks')&&enemy.wood>=140){enemy.wood-=140;this.enemyBuild('barracks',1850,1010)}if(enemy.age<4&&time>[0,65000,145000,235000][enemy.age]&&enemy.food>350&&enemy.gold>180){enemy.food-=300;enemy.gold-=150;enemy.age++}const military=this.units.filter(u=>u.owner==='enemy'&&u.type!=='villager');if(this.buildings.some(b=>b.owner==='enemy'&&b.kind==='barracks'&&b.progress>=1)&&military.length<10){const t=enemy.age>=3&&Math.random()>.55?'cavalry':enemy.age>=2&&Math.random()>.45?'archer':'soldier';this.train(t,'enemy')}if(time>45000&&military.length>=3)for(const u of military.filter(x=>!x.attack)){const unitTargets=this.units.filter(x=>x.owner==='player'),t:AttackTarget|undefined=unitTargets.sort((a,b)=>Phaser.Math.Distance.Between(u.x,u.y,a.x,a.y)-Phaser.Math.Distance.Between(u.x,u.y,b.x,b.y))[0]??this.buildings.filter(b=>b.owner==='player').sort((a,b)=>Phaser.Math.Distance.Between(u.x,u.y,a.x,a.y)-Phaser.Math.Distance.Between(u.x,u.y,b.x,b.y))[0];if(t){u.attack=t;u.target={x:t.x,y:t.y}}}}
 enemyBuild(kind:'house'|'barracks',x:number,y:number){const b=this.addBuilding(kind,'enemy',x,y,0),builder=this.units.find(u=>u.owner==='enemy'&&u.type==='villager'&&!u.build);if(builder){builder.resource=undefined;builder.build=b;builder.target={x,y:y+55}}}
 updateFog(){const visible=[...this.units.filter(u=>u.owner==='player'),...this.buildings.filter(b=>b.owner==='player'&&b.progress>=1)];for(const f of this.fog){let d=Infinity;for(const v of visible)d=Math.min(d,Phaser.Math.Distance.Between(f.x,f.y,v.x,v.y));f.setAlpha(d<235?0:d<340?.5:.91);f.setVisible(f.alpha>.02)}}
 syncBuilding(b:Building){const size=b.kind==='town'?124:b.kind==='barracks'?104:76,ratio=Phaser.Math.Clamp(b.hp/b.maxHp,0,1);b.hpBack.setPosition(b.x-size*.42,b.y-size*.55);b.hpBar.setPosition(b.x-size*.42,b.y-size*.55).setScale(ratio,1).setFillStyle(ratio>.55?(b.owner==='player'?0x69c56d:0xdc5a50):ratio>.25?0xe0ad45:0xd3463f)}
 syncUnit(u:Unit){u.shape.setPosition(u.x,u.y);u.ring.setPosition(u.x,u.y);u.hpBack.setPosition(u.x-16,u.y-31);u.hpBar.setPosition(u.x-16,u.y-31).setScale(Math.max(0,u.hp/u.maxHp),1);u.label.setPosition(u.x,u.y+20);u.label.setText(u.type==='villager'&&u.cargo>0?`${this.resourceName(u.cargoKind!)}${Math.floor(u.cargo)}`:{villager:'町',soldier:'槍',archer:'弓',cavalry:'騎'}[u.type])}
 refreshUi(){const set=(id:string,v:string)=>document.querySelector(id)!.textContent=v;set('#wood',Math.floor(player.wood)+'');set('#food',Math.floor(player.food)+'');set('#gold',Math.floor(player.gold)+'');set('#pop',`${this.units.filter(u=>u.owner==='player').length} / ${player.popCap}`);set('#age',ages[player.age-1]);const next=[[300,150],[500,300],[800,500]][player.age-1];set('#advanceCost',next?`食${next[0]}・金${next[1]}`:'進化完了');(document.querySelector('#advance') as HTMLButtonElement).disabled=player.age>=4;(document.querySelector('#archer') as HTMLButtonElement).disabled=player.age<2;(document.querySelector('#cavalry') as HTMLButtonElement).disabled=player.age<3;(['attack','economy','armor'] as Tech[]).forEach(t=>(document.querySelector(`#${t}Tech`) as HTMLButtonElement).disabled=player.researched.has(t))}
 say(message:string){const el=document.querySelector<HTMLElement>('#status')!;el.textContent=message;el.style.opacity='1';if(this.statusTimer)clearTimeout(this.statusTimer);this.statusTimer=window.setTimeout(()=>el.style.opacity='0',2200)}
 unitName(t:UnitType){return{villager:'町人',soldier:'槍兵',archer:'弓兵',cavalry:'騎兵'}[t]}
 resourceName(k:ResourceKind){return{wood:'木',food:'食料',gold:'金'}[k]}
 finish(winner:Owner){if(this.result)return;this.result=winner==='player'?'あなたの勝利':'敵軍の勝利';const elapsed=Math.max(0,Math.floor((this.time.now-this.startTime)/1000)),minutes=Math.floor(elapsed/60).toString().padStart(2,'0'),seconds=(elapsed%60).toString().padStart(2,'0');document.querySelector('#goal')!.textContent=this.result;document.querySelector('#resultTitle')!.textContent=winner==='player'?'勝利':'敗北';document.querySelector('#resultWinner')!.textContent=`勝者：${this.result}`;document.querySelector('#resultTime')!.textContent=`${minutes}:${seconds}`;document.querySelector('#resultAge')!.textContent=ages[player.age-1];const overlay=document.querySelector<HTMLElement>('#resultOverlay')!;overlay.classList.add('show');overlay.setAttribute('aria-hidden','false');for(const u of this.units){u.target=undefined;u.attack=undefined}}
}
new Phaser.Game({type:Phaser.AUTO,parent:'app',backgroundColor:'#111713',scale:{mode:Phaser.Scale.RESIZE,width:window.innerWidth,height:window.innerHeight},render:{antialias:true,pixelArt:false},scene:GameScene});
