import Phaser from 'phaser';
import './style.css';

type Owner='player'|'enemy';
type UnitType='villager'|'soldier'|'archer'|'cavalry';
type ResourceKind='wood'|'food'|'gold';
type BuildingKind='town'|'house'|'barracks';
type Tech='attack'|'economy'|'armor';
interface Faction{wood:number;food:number;gold:number;popCap:number;age:number;attackBonus:number;gatherBonus:number;armorBonus:number;researched:Set<Tech>}
interface Unit{id:number;owner:Owner;type:UnitType;x:number;y:number;hp:number;maxHp:number;speed:number;damage:number;range:number;sight:number;selected:boolean;target?:{x:number;y:number};resource?:ResourceNode;returning:boolean;cargoKind?:ResourceKind;cargo:number;attack?:Unit;build?:Building;nextAttack:number;shape:Phaser.GameObjects.Arc;ring:Phaser.GameObjects.Arc;hpBar:Phaser.GameObjects.Rectangle;label:Phaser.GameObjects.Text}
interface ResourceNode{id:number;kind:ResourceKind;x:number;y:number;amount:number;shape:Phaser.GameObjects.Shape;label:Phaser.GameObjects.Text}
interface Building{id:number;owner:Owner;kind:BuildingKind;x:number;y:number;hp:number;maxHp:number;progress:number;shape:Phaser.GameObjects.Rectangle;label:Phaser.GameObjects.Text}
const WORLD_W=2400,WORLD_H=1600,UI_TOP=58;
const ages=['暗黒の時代','領主の時代','城主の時代','帝王の時代'];
const player:Faction={wood:260,food:500,gold:260,popCap:10,age:1,attackBonus:0,gatherBonus:0,armorBonus:0,researched:new Set()};
const enemy:Faction={wood:240,food:420,gold:220,popCap:10,age:1,attackBonus:0,gatherBonus:0,armorBonus:0,researched:new Set()};

document.querySelector<HTMLDivElement>('#app')!.innerHTML=`
<div id="topbar"><div class="brand">FRONTIER COMMAND</div><div class="age"><span id="age">暗黒の時代</span></div><div class="res wood"><i></i>木 <span id="wood">0</span></div><div class="res food"><i></i>食 <span id="food">0</span></div><div class="res gold"><i></i>金 <span id="gold">0</span></div><div class="res pop"><i></i>人口 <span id="pop">0</span></div></div>
<div id="help"><span class="desktopHelp">左ドラッグ：範囲選択　右クリック：移動 / 採集 / 攻撃<br>WASD・画面端：カメラ移動　ホイール：拡大縮小</span><span class="mobileHelp">味方をタップして選択 → 地面・資源・敵をタップ<br>画面ドラッグ：移動　＋/－：拡大縮小</span></div>
<div id="objective"><strong>目標</strong><span id="goal">経済を育て、敵の軍を倒す</span></div><div id="status"></div>
<div id="zoom"><button id="zoomOut" aria-label="縮小">−</button><button id="zoomIn" aria-label="拡大">＋</button></div>
<div id="actions"><button id="villager">町人を生産<small>食料 50</small></button><button id="house">家を建てる<small>木材 80 / 人口 +5</small></button><button id="barracks">兵舎を建てる<small>木材 140</small></button><button id="soldier">槍兵を生産<small>食60・金30</small></button><button id="archer">弓兵を生産<small>領主 / 食45・金45</small></button><button id="cavalry">騎兵を生産<small>城主 / 食80・金70</small></button><button id="advance">時代進化<small id="advanceCost">食300・金150</small></button><button id="attackTech">武器研究<small>領主 / 木150・金100</small></button><button id="economyTech">採集研究<small>領主 / 木120・食100</small></button><button id="armorTech">防具研究<small>城主 / 木180・金140</small></button></div>`;

class GameScene extends Phaser.Scene{
 units:Unit[]=[];resources:ResourceNode[]=[];buildings:Building[]=[];fog:Phaser.GameObjects.Rectangle[]=[];nextId=1;selectStart?:Phaser.Math.Vector2;selectBox?:Phaser.GameObjects.Rectangle;placing?:BuildingKind;keys!:Record<string,Phaser.Input.Keyboard.Key>;lastFog=0;lastAi=0;lastAuto=0;result='';statusTimer?:number;touchStart?:{sx:number;sy:number;wx:number;wy:number;cx:number;cy:number;moved:boolean};
 create(){this.cameras.main.setBounds(0,0,WORLD_W,WORLD_H).setZoom(.85).centerOn(550,760);this.input.mouse?.disableContextMenu();this.input.addPointer(2);this.drawMap();this.addBuilding('town','player',420,760,1);[[500,700],[505,760],[500,820],[565,735],[565,795]].forEach(p=>this.addUnit('villager','player',p[0],p[1]));this.addBuilding('town','enemy',2000,760,1);[[1900,690],[1900,755],[1900,820],[1960,850]].forEach(p=>this.addUnit('villager','enemy',p[0],p[1]));for(let i=0;i<20;i++)this.addResource('wood',650+Math.random()*1100,150+Math.random()*430);for(let i=0;i<14;i++)this.addResource('food',620+Math.random()*1200,880+Math.random()*500);for(let i=0;i<12;i++)this.addResource('gold',950+Math.random()*900,560+Math.random()*760);this.keys=this.input.keyboard!.addKeys('W,A,S,D,UP,DOWN,LEFT,RIGHT') as Record<string,Phaser.Input.Keyboard.Key>;this.input.on('pointerdown',(p:Phaser.Input.Pointer)=>this.onDown(p));this.input.on('pointermove',(p:Phaser.Input.Pointer)=>this.onMove(p));this.input.on('pointerup',(p:Phaser.Input.Pointer)=>this.onUp(p));this.input.on('wheel',(_p:Phaser.Input.Pointer,_o:unknown,_dx:number,dy:number)=>this.setZoom(this.cameras.main.zoom-dy*.0005));const click=(id:string,fn:()=>void)=>document.querySelector(id)!.addEventListener('click',e=>{e.stopPropagation();fn()});click('#villager',()=>this.train('villager','player'));click('#house',()=>this.beginPlace('house'));click('#barracks',()=>this.beginPlace('barracks'));click('#soldier',()=>this.train('soldier','player'));click('#archer',()=>this.train('archer','player'));click('#cavalry',()=>this.train('cavalry','player'));click('#advance',()=>this.advanceAge());click('#attackTech',()=>this.research('attack'));click('#economyTech',()=>this.research('economy'));click('#armorTech',()=>this.research('armor'));click('#zoomIn',()=>this.setZoom(this.cameras.main.zoom+.12));click('#zoomOut',()=>this.setZoom(this.cameras.main.zoom-.12));this.createFog();this.refreshUi()}
 drawMap(){const g=this.add.graphics().setDepth(-20);g.fillStyle(0x75875d).fillRect(0,0,WORLD_W,WORLD_H);g.fillStyle(0x687b55,.7);for(let i=0;i<240;i++)g.fillCircle(Math.random()*WORLD_W,Math.random()*WORLD_H,2+Math.random()*7);g.fillStyle(0x365f66,.9);g.fillEllipse(1200,780,500,170);g.fillEllipse(1500,420,300,110);g.lineStyle(5,0xb69b68,.55);new Phaser.Curves.Path(0,1150).splineTo([new Phaser.Math.Vector2(400,1050),new Phaser.Math.Vector2(900,1120),new Phaser.Math.Vector2(1400,980),new Phaser.Math.Vector2(1900,1080),new Phaser.Math.Vector2(2400,900)]).draw(g,64)}
 faction(o:Owner){return o==='player'?player:enemy}
 addUnit(type:UnitType,owner:Owner,x:number,y:number){const stats={villager:[70,88,3,22,180],soldier:[120,100,18,38,235],archer:[78,94,14,155,280],cavalry:[165,138,23,42,260]}[type];const enemySide=owner==='enemy';const colors={villager:enemySide?0xad6755:0xd9b878,soldier:enemySide?0xa64038:0x4e78a6,archer:enemySide?0xc45d50:0x5e96b9,cavalry:enemySide?0x7f2e2b:0x385f95};const ring=this.add.circle(x,y,type==='cavalry'?21:18).setStrokeStyle(3,0xf2d66d).setVisible(false).setDepth(9);const shape=this.add.circle(x,y,type==='cavalry'?16:type==='villager'?11:13,colors[type]).setStrokeStyle(2,enemySide?0x54201e:0x263126).setDepth(10);const hpBar=this.add.rectangle(x,y-21,30,4,0x56c65e).setOrigin(0,.5).setDepth(11).setVisible(type!=='villager');const names={villager:'町',soldier:'槍',archer:'弓',cavalry:'騎'};const label=this.add.text(x,y+15,names[type],{fontSize:'9px',color:'#fff',stroke:'#111',strokeThickness:2}).setOrigin(.5,0).setDepth(11);this.units.push({id:this.nextId++,owner,type,x,y,hp:stats[0],maxHp:stats[0],speed:stats[1],damage:stats[2],range:stats[3],sight:stats[4],selected:false,returning:false,cargo:0,nextAttack:0,shape,ring,hpBar,label})}
 addResource(kind:ResourceKind,x:number,y:number){const color=kind==='wood'?0x315d35:kind==='food'?0xa9483d:0xc9a43d;const shape=kind==='wood'?this.add.star(x,y,7,12,25,color):this.add.circle(x,y,kind==='gold'?20:16,color);shape.setStrokeStyle(2,0x263425).setDepth(3);const label=this.add.text(x,y+24,kind==='wood'?'木':kind==='food'?'食':'金',{fontSize:'11px',color:'#f1e8cf',backgroundColor:'#1118',padding:{x:3,y:1}}).setOrigin(.5,0).setDepth(4);this.resources.push({id:this.nextId++,kind,x,y,amount:kind==='wood'?520:380,shape,label})}
 addBuilding(kind:BuildingKind,owner:Owner,x:number,y:number,progress=0){const size=kind==='town'?120:kind==='barracks'?100:74,friendly=owner==='player',color=kind==='town'?(friendly?0x8b7651:0x774a43):kind==='house'?(friendly?0xb18b5a:0x8c5546):(friendly?0x6f6658:0x70423d);const shape=this.add.rectangle(x,y,size,size*.72,color,progress<1?.38:1).setStrokeStyle(3,friendly?0x3c3023:0x57241f).setDepth(5);const names={town:'町の中心',house:'家',barracks:'兵舎'};const label=this.add.text(x,y,names[kind],{fontSize:'13px',fontStyle:'bold',color:'#fff4d3',stroke:'#201a13',strokeThickness:3}).setOrigin(.5).setDepth(6);const b={id:this.nextId++,owner,kind,x,y,hp:progress<1?1:500,maxHp:500,progress,shape,label};this.buildings.push(b);return b}
 createFog(){for(let y=60;y<WORLD_H;y+=100)for(let x=50;x<WORLD_W;x+=100)this.fog.push(this.add.rectangle(x,y,102,102,0x080c09,.91).setDepth(50))}
 setZoom(z:number){this.cameras.main.setZoom(Phaser.Math.Clamp(z,.55,1.25))}
 onDown(p:Phaser.Input.Pointer){if(p.y<UI_TOP)return;const w=new Phaser.Math.Vector2(p.worldX,p.worldY);if(p.wasTouch){const c=this.cameras.main;this.touchStart={sx:p.x,sy:p.y,wx:w.x,wy:w.y,cx:c.scrollX,cy:c.scrollY,moved:false};return}if(p.rightButtonDown()){this.command(w.x,w.y);return}if(this.placing){this.place(w.x,w.y);return}this.selectStart=w;this.selectBox=this.add.rectangle(w.x,w.y,1,1,0x8fb7d0,.18).setStrokeStyle(2,0xd3e9f5).setOrigin(0).setDepth(45)}
 onMove(p:Phaser.Input.Pointer){if(this.touchStart&&p.isDown){const t=this.touchStart,dx=p.x-t.sx,dy=p.y-t.sy;if(Math.hypot(dx,dy)>9)t.moved=true;if(t.moved){const c=this.cameras.main;c.scrollX=t.cx-dx/c.zoom;c.scrollY=t.cy-dy/c.zoom}return}if(!this.selectStart||!this.selectBox)return;const w=new Phaser.Math.Vector2(p.worldX,p.worldY),x=Math.min(w.x,this.selectStart.x),y=Math.min(w.y,this.selectStart.y);this.selectBox.setPosition(x,y).setSize(Math.abs(w.x-this.selectStart.x),Math.abs(w.y-this.selectStart.y))}
 onUp(p:Phaser.Input.Pointer){if(this.touchStart){const t=this.touchStart;this.touchStart=undefined;if(!t.moved)this.handleTap(t.wx,t.wy);return}if(!this.selectStart)return;const w=new Phaser.Math.Vector2(p.worldX,p.worldY),d=Phaser.Math.Distance.Between(w.x,w.y,this.selectStart.x,this.selectStart.y);this.units.filter(u=>u.owner==='player').forEach(u=>{u.selected=d<8?Phaser.Math.Distance.Between(u.x,u.y,w.x,w.y)<25:u.x>=Math.min(w.x,this.selectStart!.x)&&u.x<=Math.max(w.x,this.selectStart!.x)&&u.y>=Math.min(w.y,this.selectStart!.y)&&u.y<=Math.max(w.y,this.selectStart!.y);u.ring.setVisible(u.selected)});this.selectStart=undefined;this.selectBox?.destroy();this.selectBox=undefined}
 handleTap(x:number,y:number){if(this.placing){this.place(x,y);return}const own=this.units.find(u=>u.owner==='player'&&Phaser.Math.Distance.Between(u.x,u.y,x,y)<28);if(own){this.units.filter(u=>u.owner==='player').forEach(u=>{u.selected=u===own;u.ring.setVisible(u.selected)});this.say(`${this.unitName(own.type)}を選択`);return}if(this.units.some(u=>u.selected&&u.owner==='player'))this.command(x,y)}
 command(x:number,y:number){const selected=this.units.filter(u=>u.selected&&u.owner==='player');if(!selected.length)return;const foe=this.units.find(u=>u.owner==='enemy'&&Phaser.Math.Distance.Between(u.x,u.y,x,y)<32),res=this.resources.find(r=>Phaser.Math.Distance.Between(r.x,r.y,x,y)<38);selected.forEach((u,i)=>{u.build=undefined;u.attack=foe;u.resource=u.type==='villager'?res:undefined;u.returning=false;if(!res){u.cargo=0;u.cargoKind=undefined}const t=foe??res;u.target=t?{x:t.x,y:t.y}:{x:x+(i%3)*24,y:y+Math.floor(i/3)*24}});this.say(foe?'敵を攻撃します':res?`${this.resourceName(res.kind)}を採集して町へ運びます`:'移動します')}
 beginPlace(kind:BuildingKind){const cost=kind==='house'?80:140;if(player.wood<cost){this.say('木材が足りません');return}if(!this.units.some(u=>u.selected&&u.owner==='player'&&u.type==='villager')){this.say('建設する町人を選択してください');return}this.placing=kind;this.say('建設場所をタップしてください')}
 place(x:number,y:number){const kind=this.placing!,cost=kind==='house'?80:140;if(x<80||y<110||x>WORLD_W-80||y>WORLD_H-80)return;player.wood-=cost;const b=this.addBuilding(kind,'player',x,y,0);this.units.filter(u=>u.selected&&u.type==='villager'&&u.owner==='player').forEach((u,i)=>{u.attack=undefined;u.resource=undefined;u.build=b;u.target={x:x+((i%3)-1)*24,y:y+55+Math.floor(i/3)*22}});this.placing=undefined;this.refreshUi();this.say(`${kind==='house'?'家':'兵舎'}の建設を開始します`)}
 train(type:UnitType,owner:Owner){const f=this.faction(owner),town=this.buildings.find(b=>b.owner===owner&&b.kind==='town'&&b.progress>=1),barracks=this.buildings.find(b=>b.owner===owner&&b.kind==='barracks'&&b.progress>=1),costs={villager:[0,50,0],soldier:[0,60,30],archer:[0,45,45],cavalry:[0,80,70]}[type],required=type==='archer'?2:type==='cavalry'?3:1,source=type==='villager'?town:barracks;if(f.age<required){if(owner==='player')this.say(`${ages[required-1]}が必要です`);return}if(!source){if(owner==='player')this.say(type==='villager'?'町の中心が必要です':'完成した兵舎が必要です');return}if(f.wood<costs[0]||f.food<costs[1]||f.gold<costs[2]){if(owner==='player')this.say('資源が足りません');return}if(this.units.filter(u=>u.owner===owner).length>=f.popCap){if(owner==='player')this.say('人口上限です。家を建ててください');return}f.wood-=costs[0];f.food-=costs[1];f.gold-=costs[2];if(owner==='player')this.say(`${this.unitName(type)}を訓練中…`);this.time.delayedCall(type==='cavalry'?3300:2300,()=>{if(!this.buildings.includes(source))return;this.addUnit(type,owner,source.x+(owner==='player'?75:-75),source.y+45);this.refreshUi();if(owner==='player')this.say(`${this.unitName(type)}が完成しました`)})}
 advanceAge(){if(player.age>=4){this.say('すでに帝王の時代です');return}const costs=[[300,150],[500,300],[800,500]][player.age-1];if(player.food<costs[0]||player.gold<costs[1]){this.say('時代進化に必要な資源が足りません');return}player.food-=costs[0];player.gold-=costs[1];player.age++;this.refreshUi();this.say(`${ages[player.age-1]}へ進化しました`)}
 research(tech:Tech){if(player.researched.has(tech)){this.say('研究済みです');return}const req=tech==='armor'?3:2;if(player.age<req){this.say(`${ages[req-1]}が必要です`);return}const costs={attack:[150,0,100],economy:[120,100,0],armor:[180,0,140]}[tech];if(player.wood<costs[0]||player.food<costs[1]||player.gold<costs[2]){this.say('研究に必要な資源が足りません');return}player.wood-=costs[0];player.food-=costs[1];player.gold-=costs[2];player.researched.add(tech);if(tech==='attack')player.attackBonus=.2;if(tech==='economy')player.gatherBonus=.25;if(tech==='armor'){player.armorBonus=.18;for(const u of this.units.filter(u=>u.owner==='player')){u.maxHp*=1.2;u.hp*=1.2}}this.refreshUi();this.say(`${tech==='attack'?'武器':tech==='economy'?'採集':'防具'}研究が完了しました`)}
 update(time:number,delta:number){if(this.result)return;const dt=Math.min(delta/1000,.05);this.moveCamera(dt);this.updateBuildings(dt);this.updateUnits(time,dt);if(time-this.lastAuto>450){this.autoAcquire();this.lastAuto=time}if(time-this.lastFog>240){this.updateFog();this.lastFog=time}if(time-this.lastAi>1800){this.enemyAi(time);this.lastAi=time}if(!this.units.some(u=>u.owner==='enemy'))this.finish('勝利！ 敵の軍と町人をすべて倒しました');if(!this.units.some(u=>u.owner==='player'))this.finish('敗北 — 集落を守れませんでした');this.refreshUi()}
 moveCamera(dt:number){if(this.touchStart)return;const c=this.cameras.main,p=this.input.activePointer,s=520*dt/c.zoom;let dx=0,dy=0;if(this.keys.A.isDown||this.keys.LEFT.isDown||(!p.wasTouch&&p.x<8))dx=-s;if(this.keys.D.isDown||this.keys.RIGHT.isDown||(!p.wasTouch&&p.x>this.scale.width-8))dx=s;if(this.keys.W.isDown||this.keys.UP.isDown||(!p.wasTouch&&p.y<UI_TOP+4))dy=-s;if(this.keys.S.isDown||this.keys.DOWN.isDown||(!p.wasTouch&&p.y>this.scale.height-8))dy=s;c.scrollX+=dx;c.scrollY+=dy}
 updateBuildings(dt:number){for(const b of this.buildings){if(b.progress>=1)continue;const builders=this.units.filter(u=>u.owner===b.owner&&u.type==='villager'&&u.build===b&&Phaser.Math.Distance.Between(u.x,u.y,b.x,b.y)<88);if(!builders.length)continue;b.progress=Math.min(1,b.progress+dt*.18*Math.min(builders.length,3));b.hp=b.maxHp*b.progress;b.shape.setAlpha(.38+.62*b.progress);b.label.setText(`${b.kind==='house'?'家':'兵舎'} ${Math.floor(b.progress*100)}%`);if(b.progress>=1){b.label.setText(b.kind==='house'?'家':'兵舎');if(b.kind==='house')this.faction(b.owner).popCap+=5;for(const u of builders){u.build=undefined;u.target=undefined}if(b.owner==='player')this.say(`${b.kind==='house'?'家':'兵舎'}が完成しました${b.kind==='house'?'。人口上限 +5':''}`)}}}
 updateUnits(time:number,dt:number){for(const u of [...this.units]){if(!this.units.includes(u))continue;if(u.attack&&!this.units.includes(u.attack)){u.attack=undefined;u.target=undefined}if(u.resource&&!this.resources.includes(u.resource)&&!u.returning)u.resource=undefined;if(u.resource)this.updateGatherOrder(u,dt);if(u.attack)u.target={x:u.attack.x,y:u.attack.y};const action=u.attack??u.resource;if(u.target){const dist=Phaser.Math.Distance.Between(u.x,u.y,u.target.x,u.target.y),stop=u.attack?u.range:u.resource?(u.returning?58:32):u.build?58:4;if(dist>stop){const a=Phaser.Math.Angle.Between(u.x,u.y,u.target.x,u.target.y);u.x+=Math.cos(a)*u.speed*dt;u.y+=Math.sin(a)*u.speed*dt}else if(!action&&!u.build)u.target=undefined}if(u.attack&&Phaser.Math.Distance.Between(u.x,u.y,u.attack.x,u.attack.y)<=u.range&&time>=u.nextAttack){u.nextAttack=time+(u.type==='archer'?900:u.type==='villager'?1050:700);this.dealDamage(u,u.attack)}this.syncUnit(u)}}
 updateGatherOrder(u:Unit,dt:number){const r=u.resource!,town=this.buildings.find(b=>b.owner===u.owner&&b.kind==='town'&&b.progress>=1);if(!town){u.resource=undefined;return}if(u.returning){u.target={x:town.x,y:town.y};if(Phaser.Math.Distance.Between(u.x,u.y,town.x,town.y)<62){if(u.cargoKind)this.faction(u.owner)[u.cargoKind]+=u.cargo;u.cargo=0;u.cargoKind=undefined;u.returning=false;if(this.resources.includes(r))u.target={x:r.x,y:r.y};else{u.resource=undefined;u.target=undefined}}return}u.target={x:r.x,y:r.y};if(Phaser.Math.Distance.Between(u.x,u.y,r.x,r.y)<34){const qty=Math.min(r.amount,8*(1+this.faction(u.owner).gatherBonus)*dt,20-u.cargo);r.amount-=qty;u.cargo+=qty;u.cargoKind=r.kind;if(r.amount<=0){r.shape.destroy();r.label.destroy();this.resources=this.resources.filter(x=>x!==r)}if(u.cargo>=19.9||r.amount<=0)u.returning=true}}
 autoAcquire(){for(const u of this.units.filter(u=>u.type!=='villager'&&!u.attack&&!u.build)){let best:Unit|undefined,dist=u.sight;for(const foe of this.units.filter(x=>x.owner!==u.owner)){const d=Phaser.Math.Distance.Between(u.x,u.y,foe.x,foe.y);if(d<dist){dist=d;best=foe}}if(best){u.attack=best;u.target={x:best.x,y:best.y}}}}
 dealDamage(attacker:Unit,defender:Unit){const counters:Record<UnitType,Partial<Record<UnitType,number>>>={villager:{},soldier:{cavalry:1.65},archer:{soldier:1.55},cavalry:{archer:1.75}},mult=counters[attacker.type][defender.type]??1,raw=attacker.damage*(1+this.faction(attacker.owner).attackBonus)*mult;defender.hp-=raw*(1-this.faction(defender.owner).armorBonus);if(defender.hp<=0){this.removeUnit(defender);return}if(defender.type!=='villager'&&(!defender.attack||!this.units.includes(defender.attack))){defender.attack=attacker;defender.resource=undefined;defender.target={x:attacker.x,y:attacker.y}}}
 removeUnit(u:Unit){u.shape.destroy();u.ring.destroy();u.hpBar.destroy();u.label.destroy();this.units=this.units.filter(x=>x!==u);for(const x of this.units)if(x.attack===u){x.attack=undefined;x.target=undefined}}
 enemyAi(time:number){const workers=this.units.filter(u=>u.owner==='enemy'&&u.type==='villager');for(const w of workers.filter(u=>!u.resource&&!u.build&&!u.attack)){const preferred=enemy.food<180?'food':enemy.wood<150?'wood':'gold',choices=this.resources.filter(r=>r.kind===preferred),r=choices.sort((a,b)=>Phaser.Math.Distance.Between(w.x,w.y,a.x,a.y)-Phaser.Math.Distance.Between(w.x,w.y,b.x,b.y))[0]??this.resources[0];if(r){w.resource=r;w.target={x:r.x,y:r.y}}}const count=this.units.filter(u=>u.owner==='enemy').length;if(enemy.popCap-count<=2&&enemy.wood>=80&&!this.buildings.some(b=>b.owner==='enemy'&&b.kind==='house'&&b.progress<1)){enemy.wood-=80;this.enemyBuild('house',2020+Math.random()*180,930+Math.random()*180)}if(!this.buildings.some(b=>b.owner==='enemy'&&b.kind==='barracks')&&enemy.wood>=140){enemy.wood-=140;this.enemyBuild('barracks',1850,1010)}if(enemy.age<4&&time>[0,65000,145000,235000][enemy.age]&&enemy.food>350&&enemy.gold>180){enemy.food-=300;enemy.gold-=150;enemy.age++}const military=this.units.filter(u=>u.owner==='enemy'&&u.type!=='villager');if(this.buildings.some(b=>b.owner==='enemy'&&b.kind==='barracks'&&b.progress>=1)&&military.length<10){const t=enemy.age>=3&&Math.random()>.55?'cavalry':enemy.age>=2&&Math.random()>.45?'archer':'soldier';this.train(t,'enemy')}if(time>45000&&military.length>=3)for(const u of military.filter(x=>!x.attack)){const targets=this.units.filter(x=>x.owner==='player'),t=targets.sort((a,b)=>Phaser.Math.Distance.Between(u.x,u.y,a.x,a.y)-Phaser.Math.Distance.Between(u.x,u.y,b.x,b.y))[0];if(t){u.attack=t;u.target={x:t.x,y:t.y}}}}
 enemyBuild(kind:'house'|'barracks',x:number,y:number){const b=this.addBuilding(kind,'enemy',x,y,0),builder=this.units.find(u=>u.owner==='enemy'&&u.type==='villager'&&!u.build);if(builder){builder.resource=undefined;builder.build=b;builder.target={x,y:y+55}}}
 updateFog(){const visible=[...this.units.filter(u=>u.owner==='player'),...this.buildings.filter(b=>b.owner==='player'&&b.progress>=1)];for(const f of this.fog){let d=Infinity;for(const v of visible)d=Math.min(d,Phaser.Math.Distance.Between(f.x,f.y,v.x,v.y));f.setAlpha(d<235?0:d<340?.5:.91);f.setVisible(f.alpha>.02)}}
 syncUnit(u:Unit){u.shape.setPosition(u.x,u.y);u.ring.setPosition(u.x,u.y);u.hpBar.setPosition(u.x-15,u.y-21).setScale(Math.max(0,u.hp/u.maxHp),1);u.label.setPosition(u.x,u.y+15);u.label.setText(u.type==='villager'&&u.cargo>0?`${this.resourceName(u.cargoKind!)}${Math.floor(u.cargo)}`:{villager:'町',soldier:'槍',archer:'弓',cavalry:'騎'}[u.type])}
 refreshUi(){const set=(id:string,v:string)=>document.querySelector(id)!.textContent=v;set('#wood',Math.floor(player.wood)+'');set('#food',Math.floor(player.food)+'');set('#gold',Math.floor(player.gold)+'');set('#pop',`${this.units.filter(u=>u.owner==='player').length} / ${player.popCap}`);set('#age',ages[player.age-1]);const next=[[300,150],[500,300],[800,500]][player.age-1];set('#advanceCost',next?`食${next[0]}・金${next[1]}`:'進化完了');(document.querySelector('#advance') as HTMLButtonElement).disabled=player.age>=4;(document.querySelector('#archer') as HTMLButtonElement).disabled=player.age<2;(document.querySelector('#cavalry') as HTMLButtonElement).disabled=player.age<3;(['attack','economy','armor'] as Tech[]).forEach(t=>(document.querySelector(`#${t}Tech`) as HTMLButtonElement).disabled=player.researched.has(t))}
 say(message:string){const el=document.querySelector<HTMLElement>('#status')!;el.textContent=message;el.style.opacity='1';if(this.statusTimer)clearTimeout(this.statusTimer);this.statusTimer=window.setTimeout(()=>el.style.opacity='0',2200)}
 unitName(t:UnitType){return{villager:'町人',soldier:'槍兵',archer:'弓兵',cavalry:'騎兵'}[t]}
 resourceName(k:ResourceKind){return{wood:'木',food:'食料',gold:'金'}[k]}
 finish(text:string){this.result=text;document.querySelector('#goal')!.textContent=text;this.say(text);for(const u of this.units)u.target=undefined}
}
new Phaser.Game({type:Phaser.AUTO,parent:'app',backgroundColor:'#111713',scale:{mode:Phaser.Scale.RESIZE,width:window.innerWidth,height:window.innerHeight},render:{antialias:true,pixelArt:false},scene:GameScene});
