import Phaser from 'phaser';
import './style.css';
import {GridPathfinder,type Point} from './pathfinding';
import {attackReach as calculateAttackReach,combatSlotOffset,combatStandDistance,contactDistance,shouldRepathCombat,shouldTakeContactTarget} from './combat-rules';
import {canContinueConstruction,isBuilderUnit,shouldResumeConstructionOnTap} from './order-rules';
import {avoidanceTurns,separationOffsets} from './movement-rules';
import {initOnline} from './client/online-client';

type Owner='player'|'enemy';
type UnitType='villager'|'soldier'|'archer'|'cavalry';
type ResourceKind='wood'|'food'|'gold';
type BuildingKind='town'|'house'|'barracks';
type Tech='attack'|'economy'|'armor';
interface Faction{wood:number;food:number;gold:number;popCap:number;age:number;attackBonus:number;gatherBonus:number;armorBonus:number;researched:Set<Tech>}
interface Unit{id:number;owner:Owner;type:UnitType;x:number;y:number;hp:number;maxHp:number;speed:number;damage:number;range:number;sight:number;selected:boolean;target?:Point;path:Point[];pathIndex:number;repathAt:number;stall:number;lastX:number;lastY:number;lastPathIndex:number;lastWaypointDistance:number;combatTargetId?:number;combatAngle?:number;attackTrackX?:number;attackTrackY?:number;resource?:ResourceNode;returning:boolean;cargoKind?:ResourceKind;cargo:number;attack?:AttackTarget;build?:Building;nextAttack:number;attackAnimUntil:number;shape:Phaser.GameObjects.Container;ring:Phaser.GameObjects.Arc;hpBack:Phaser.GameObjects.Rectangle;hpBar:Phaser.GameObjects.Rectangle;label:Phaser.GameObjects.Text}
interface ResourceNode{id:number;kind:ResourceKind;x:number;y:number;amount:number;shape:Phaser.GameObjects.Container;label:Phaser.GameObjects.Text}
interface Building{id:number;owner:Owner;kind:BuildingKind;x:number;y:number;hp:number;maxHp:number;progress:number;shape:Phaser.GameObjects.Container;label:Phaser.GameObjects.Text;hpBack:Phaser.GameObjects.Rectangle;hpBar:Phaser.GameObjects.Rectangle;smoke:Phaser.GameObjects.Arc;fire:Phaser.GameObjects.Arc}
interface FogTile{shape:Phaser.GameObjects.Rectangle;explored:boolean;visible:boolean}
interface Projectile{shape:Phaser.GameObjects.Rectangle;x:number;y:number;target:AttackTarget;attacker:Unit;speed:number}
type AttackTarget=Unit|Building;
const WORLD_W=2400,WORLD_H=1600,UI_TOP=58;
const GAME_UI_SELECTOR='#actions,#selectionPanel,#zoom,#rangeSelect,#minimap,#cancelPlacement,#topbar,#resultOverlay';
const ages=['暗黒の時代','領主の時代','城主の時代','帝王の時代'];
const player:Faction={wood:260,food:500,gold:260,popCap:10,age:1,attackBonus:0,gatherBonus:0,armorBonus:0,researched:new Set()};
const enemy:Faction={wood:240,food:420,gold:220,popCap:10,age:1,attackBonus:0,gatherBonus:0,armorBonus:0,researched:new Set()};

document.querySelector<HTMLDivElement>('#app')!.innerHTML=`
<div id="titleScreen" role="dialog" aria-modal="true" aria-labelledby="gameTitle">
  <div class="titleSun"></div><div class="titleMountain mountainBack"></div><div class="titleMountain mountainFront"></div>
  <div class="titleFort" aria-hidden="true"><i></i><i></i><i></i><span></span></div>
  <div class="titleArmy" aria-hidden="true"><i></i><i></i><i></i><i></i><i></i></div>
  <section class="titleCard">
    <div class="titleKicker">文明を築き、時代を制せ</div>
    <h1 id="gameTitle"><small>AGE OF</small> TERU</h1>
    <div class="titleDivider"><i></i><span>◆</span><i></i></div>
    <p>資源を集め、町を育て、軍を率いる。<br>あなたの時代が、ここから始まる。</p>
    <button type="button" id="startGame"><span>ゲームをはじめる</span><small>START GAME</small></button>
    <div class="titleHint">スマートフォンは横画面でお楽しみください</div>
  </section>
</div>
<div id="topbar"><div class="brand">AGE OF TERU</div><div class="age"><span id="age">暗黒の時代</span></div><div class="res wood"><i></i>木 <span id="wood">0</span></div><div class="res food"><i></i>食 <span id="food">0</span></div><div class="res gold"><i></i>金 <span id="gold">0</span></div><div class="res pop"><i></i>人口 <span id="pop">0</span></div></div>
<div id="help"><span class="desktopHelp">左ドラッグ：範囲選択　右クリック：移動 / 採集 / 攻撃<br>WASD・画面端：カメラ移動　ホイール：拡大縮小</span><span class="mobileHelp">味方をタップして選択 → 地面・資源・敵をタップ<br>画面ドラッグ：移動　＋/－：拡大縮小</span></div>
<div id="objective"><strong>目標</strong><span id="goal">経済を育て、敵の軍を倒す</span></div><div id="status"></div>
<button type="button" id="rangeSelect" aria-pressed="false">範囲選択</button><div id="zoom"><button type="button" id="zoomOut" aria-label="縮小">−</button><output id="zoomValue">85%</output><button type="button" id="zoomIn" aria-label="拡大">＋</button></div>
<aside id="selectionPanel" aria-live="polite"><strong>未選択</strong><span>ユニットまたは建物を選択</span></aside>
<div id="actions"><div class="emptyActions">対象を選択すると命令が表示されます</div></div>
<button type="button" id="cancelPlacement">配置をキャンセル</button>
<canvas id="minimap" width="210" height="135" aria-label="ミニマップ"></canvas>
<div id="resultOverlay" aria-hidden="true"><section id="resultCard"><div id="resultBadge">戦闘終了</div><h1 id="resultTitle">勝利</h1><p id="resultWinner"></p><dl><div><dt>経過時間</dt><dd id="resultTime">00:00</dd></div><div><dt>到達時代</dt><dd id="resultAge">暗黒の時代</dd></div></dl><button type="button" id="restart">もう一度プレイする</button></section></div>`;

class GameScene extends Phaser.Scene{
 units:Unit[]=[];resources:ResourceNode[]=[];buildings:Building[]=[];fog:FogTile[]=[];projectiles:Projectile[]=[];nextId=1;selectStart?:Phaser.Math.Vector2;selectBox?:Phaser.GameObjects.Rectangle;selectedBuilding?:Building;placing?:BuildingKind;placementGhost?:Phaser.GameObjects.Rectangle;placementValid=false;keys!:Record<string,Phaser.Input.Keyboard.Key>;pathfinder!:GridPathfinder;lastFog=0;lastAi=0;lastAuto=0;lastMini=0;startTime=0;started=false;result='';statusTimer?:number;uiSignature='';touchStart?:{sx:number;sy:number;wx:number;wy:number;cx:number;cy:number;moved:boolean};pinch?:{distance:number;zoom:number;worldX:number;worldY:number};suppressTouch=false;rangeSelecting=false;pendingTraining:Record<Owner,number>={player:0,enemy:0};
 create(){
  this.startTime=this.time.now;this.cameras.main.setBounds(0,0,WORLD_W,WORLD_H).setZoom(.85);this.input.mouse?.disableContextMenu();this.input.addPointer(2);this.drawMap();
  this.addBuilding('town','player',420,760,1);[[500,700],[505,760],[500,820],[565,735],[565,795]].forEach(p=>this.addUnit('villager','player',p[0],p[1]));
  this.addBuilding('town','enemy',2000,760,1);[[1900,690],[1900,755],[1900,820],[1960,850]].forEach(p=>this.addUnit('villager','enemy',p[0],p[1]));
  for(let i=0;i<20;i++)this.addResource('wood',650+Math.random()*1100,350+Math.random()*300);for(let i=0;i<14;i++)this.addResource('food',620+Math.random()*1200,950+Math.random()*420);for(let i=0;i<12;i++)this.addResource('gold',950+Math.random()*900,560+Math.random()*760);
  this.pathfinder=new GridPathfinder(WORLD_W,WORLD_H,60,(x,y)=>this.isBlocked(x,y));
  this.keys=this.input.keyboard!.addKeys('W,A,S,D,UP,DOWN,LEFT,RIGHT,ESC') as Record<string,Phaser.Input.Keyboard.Key>;
  this.keys.ESC.on('down',()=>this.cancelPlacement());
  this.input.on('pointerdown',(p:Phaser.Input.Pointer)=>this.onDown(p));this.input.on('pointermove',(p:Phaser.Input.Pointer)=>this.onMove(p));this.input.on('pointerup',(p:Phaser.Input.Pointer)=>this.onUp(p));this.input.on('wheel',(_p:Phaser.Input.Pointer,_o:unknown,_dx:number,dy:number)=>this.setZoom(this.cameras.main.zoom-dy*.0005));
  document.querySelector('#actions')!.addEventListener('click',e=>{const button=(e.target as HTMLElement).closest<HTMLButtonElement>('button[data-action]');if(button)this.handleAction(button.dataset.action!)});
  document.querySelectorAll<HTMLElement>(GAME_UI_SELECTOR).forEach(element=>{
   for(const eventName of ['pointerdown','pointermove','pointerup','wheel'])element.addEventListener(eventName,event=>event.stopPropagation());
  });
  document.querySelector('#rangeSelect')!.addEventListener('click',()=>this.setRangeSelecting(!this.rangeSelecting));document.querySelector('#startGame')!.addEventListener('click',()=>this.startGame());document.querySelector('#restart')!.addEventListener('click',()=>window.location.reload());document.querySelector('#cancelPlacement')!.addEventListener('click',()=>this.cancelPlacement());
  const mini=document.querySelector<HTMLCanvasElement>('#minimap')!;mini.addEventListener('pointerdown',e=>{e.preventDefault();const r=mini.getBoundingClientRect();this.centerCamera((e.clientX-r.left)/r.width*WORLD_W,(e.clientY-r.top)/r.height*WORLD_H)});
  this.bindZoom('#zoomIn',.1);this.bindZoom('#zoomOut',-.1);this.createFog();this.updateFog();this.setZoom(.85);this.time.delayedCall(160,()=>this.centerCamera(550,720));this.refreshUi();this.refreshSelectionUi(true);this.updateMiniMap();
  if(['localhost','127.0.0.1'].includes(location.hostname)){const params=new URLSearchParams(location.search);if(params.size)this.startGame();if(params.has('showResult'))this.time.delayedCall(150,()=>this.finish('player'));if(params.has('testCombat')){for(let i=0;i<6;i++)this.addUnit('soldier','player',650,760);const town=this.buildings.find(b=>b.owner==='player'&&b.kind==='town')!;town.hp=town.maxHp*.42;this.syncBuilding(town)}if(params.has('testGather')){const worker=this.units.find(u=>u.owner==='player'&&u.type==='villager'),resource=worker?[...this.resources].sort((a,b)=>Phaser.Math.Distance.Between(worker.x,worker.y,a.x,a.y)-Phaser.Math.Distance.Between(worker.x,worker.y,b.x,b.y))[0]:undefined;if(worker&&resource){worker.selected=true;worker.ring.setVisible(true);worker.resource=resource;this.setPathNear(worker,resource,8)}}if(params.has('testSkirmish')){const fighters:Unit[]=[];for(let i=0;i<4;i++){this.addUnit('soldier','player',980,650+i*42);fighters.push(this.units[this.units.length-1]);this.addUnit('soldier','enemy',1025,650+i*42);fighters.push(this.units[this.units.length-1])}const initial=fighters.reduce((sum,u)=>sum+u.hp,0);this.time.delayedCall(1800,()=>{const remaining=fighters.filter(u=>this.units.includes(u)).reduce((sum,u)=>sum+u.hp,0);this.say(remaining<initial?'接触戦闘テスト成功':'接触戦闘テスト失敗')})}if(params.has('testTraffic')){const squad:Unit[]=[];for(let i=0;i<24;i++){this.addUnit(i%4===0?'cavalry':'soldier','player',620+(i%6)*4,760+Math.floor(i/6)*4);squad.push(this.units[this.units.length-1])}const slots=this.formationSlots(squad.length,1450,820,48);squad.forEach((u,i)=>this.setPath(u,slots[i].x,slots[i].y));this.time.delayedCall(8500,()=>{const stillMoving=squad.filter(u=>u.pathIndex<u.path.length).length;this.say(stillMoving>4?`密集移動テスト継続中 ${stillMoving}体`:'密集移動テスト成功')})}}
 }
 startGame(){if(this.started)return;this.started=true;this.startTime=this.time.now;document.querySelector('#titleScreen')?.classList.add('leaving');this.time.delayedCall(520,()=>document.querySelector('#titleScreen')?.remove());this.centerCamera(550,720)}
 drawMap(){const g=this.add.graphics().setDepth(-20);g.fillStyle(0x91a966).fillRect(0,0,WORLD_W,WORLD_H);g.fillStyle(0x839b5c,.75);for(let y=40;y<WORLD_H;y+=90)for(let x=40;x<WORLD_W;x+=90)if((x+y)%270)g.fillCircle(x+Math.random()*35,y+Math.random()*35,10+Math.random()*20);g.lineStyle(62,0xb99b68,.72);new Phaser.Curves.Path(120,1320).splineTo([new Phaser.Math.Vector2(430,760),new Phaser.Math.Vector2(900,780),new Phaser.Math.Vector2(1430,690),new Phaser.Math.Vector2(1970,760),new Phaser.Math.Vector2(2300,1180)]).draw(g,70);g.lineStyle(34,0xd1b57d,.7);new Phaser.Curves.Path(120,1320).splineTo([new Phaser.Math.Vector2(430,760),new Phaser.Math.Vector2(900,780),new Phaser.Math.Vector2(1430,690),new Phaser.Math.Vector2(1970,760),new Phaser.Math.Vector2(2300,1180)]).draw(g,70);g.fillStyle(0x6e8753,.6);for(let i=0;i<120;i++)g.fillCircle(Math.random()*WORLD_W,340+Math.random()*(WORLD_H-340),2+Math.random()*5)}
 faction(o:Owner){return o==='player'?player:enemy}
 makeUnitVisual(type:UnitType,owner:Owner,x:number,y:number){const faction=this.faction(owner),team=owner==='player'?0x3978bd:0xb8473f,trim=faction.attackBonus>0?0xf2c94c:owner==='player'?0xd7e9f5:0xf1c2aa,parts:Phaser.GameObjects.GameObject[]=[];parts.push(this.add.ellipse(0,13,type==='cavalry'?42:28,10,0x203022,.28));if(type==='cavalry'){parts.push(this.add.ellipse(-2,3,34,18,0x765037).setStrokeStyle(2,0x3e2c24),this.add.rectangle(-11,13,4,13,0x4b3528),this.add.rectangle(8,13,4,13,0x4b3528),this.add.circle(15,-1,7,0x765037));parts.push(this.add.rectangle(-4,-8,14,17,team).setStrokeStyle(2,0x26313a),this.add.circle(-4,-19,7,0xe2b88a),this.add.rectangle(6,-13,faction.attackBonus>0?5:3,30,trim).setRotation(-.45))}else{parts.push(this.add.rectangle(-5,8,5,12,0x3d332b),this.add.rectangle(5,8,5,12,0x3d332b),this.add.rectangle(0,-1,type==='villager'?16:19,22,team).setStrokeStyle(2,0x29362c),this.add.circle(0,-16,7,0xe4b98a));if(type==='villager')parts.push(this.add.ellipse(0,-20,20,6,faction.age>=3?0x8796a5:0xc69a52),this.add.rectangle(11,0,3,25,0x6f4b2d).setRotation(.55),this.add.rectangle(16,-9,11,6,faction.age>=2?0xc8d0d3:0x99a7a0).setRotation(.55));if(type==='soldier')parts.push(this.add.triangle(0,-21,-9,7,9,7,0,-7,faction.age>=3?0xd8e0df:0xaeb9b8),this.add.rectangle(11,-2,faction.attackBonus>0?5:3,38,trim).setRotation(-.25));if(type==='archer')parts.push(this.add.arc(8,-2,11,-78,78,false,0,0).setStrokeStyle(faction.attackBonus>0?5:3,faction.attackBonus>0?0xf2c94c:0xd4b16f),this.add.rectangle(7,-2,2,23,0xd9c59b).setRotation(-.05))}if(faction.age>=2)parts.push(this.add.rectangle(0,-19,type==='villager'?15:18,4,faction.age>=4?0xf2c94c:0x7f8c8d));if(type!=='villager'&&faction.age>=3)parts.push(this.add.rectangle(0,-2,15,10,0xb9c4c8,.78).setStrokeStyle(1,0x59656b));if(type!=='villager'&&faction.armorBonus>0)parts.push(this.add.circle(-11,-3,7,0x8fa4ad).setStrokeStyle(2,faction.age>=4?0xf2c94c:0x46545b));if(faction.age>=4)parts.push(this.add.circle(0,-25,3,0xf2c94c));return this.add.container(x,y,parts).setDepth(10)}
 refreshFactionVisuals(owner:Owner){const faction=this.faction(owner);for(const u of this.units.filter(u=>u.owner===owner)){const angle=u.shape.angle;u.shape.destroy();u.shape=this.makeUnitVisual(u.type,u.owner,u.x,u.y).setAngle(angle)}for(const b of this.buildings.filter(b=>b.owner===owner&&b.kind==='town')){const shown=Number(b.shape.getData('visualAge')??1);if(faction.age<=shown)continue;const size=124,team=owner==='player'?0x3978bd:0xb8473f;if(shown<2)b.shape.add([this.add.rectangle(-size*.38,-size*.42,16,46,0xb9aa82).setStrokeStyle(2,0x5b4a35),this.add.rectangle(size*.38,-size*.42,16,46,0xb9aa82).setStrokeStyle(2,0x5b4a35)]);if(shown<3)b.shape.add([this.add.triangle(-size*.38,-size*.7,-11,9,11,9,0,-10,team).setStrokeStyle(2,0x3e352e),this.add.triangle(size*.38,-size*.7,-11,9,11,9,0,-10,team).setStrokeStyle(2,0x3e352e),this.add.rectangle(0,-size*.62,5,38,team)]);if(shown<4)b.shape.add([this.add.circle(0,-size*.78,7,0xf2c94c).setStrokeStyle(2,0x7a5a18),this.add.rectangle(-size*.25,-size*.34,7,30,0xf2c94c),this.add.rectangle(size*.25,-size*.34,7,30,0xf2c94c)]);b.shape.setData('visualAge',faction.age)}} addUnit(type:UnitType,owner:Owner,x:number,y:number){const stats={villager:[140,70.4,3,22,180],soldier:[240,80,18,38,235],archer:[156,75.2,14,155,280],cavalry:[330,110.4,23,42,260]}[type];const ring=this.add.circle(x,y,type==='cavalry'?25:20).setStrokeStyle(3,0xffe27a).setVisible(false).setDepth(9);const shape=this.makeUnitVisual(type,owner,x,y),hpBack=this.add.rectangle(x,y-31,32,6,0x251d1b,.9).setOrigin(0,.5).setDepth(11).setVisible(type!=='villager'),hpBar=this.add.rectangle(x,y-31,32,4,owner==='player'?0x56c65e:0xe35d52).setOrigin(0,.5).setDepth(12).setVisible(type!=='villager');const names={villager:'町',soldier:'槍',archer:'弓',cavalry:'騎'};const label=this.add.text(x,y+20,names[type],{fontSize:'9px',color:'#fff',stroke:'#111',strokeThickness:2}).setOrigin(.5,0).setDepth(11);this.units.push({id:this.nextId++,owner,type,x,y,hp:stats[0],maxHp:stats[0],speed:stats[1],damage:stats[2],range:stats[3],sight:stats[4],selected:false,target:undefined,path:[],pathIndex:0,repathAt:0,stall:0,lastX:x,lastY:y,lastPathIndex:-1,lastWaypointDistance:Infinity,returning:false,cargo:0,nextAttack:0,attackAnimUntil:0,shape,ring,hpBack,hpBar,label})}
 addResource(kind:ResourceKind,x:number,y:number){const parts:Phaser.GameObjects.GameObject[]=[this.add.ellipse(0,15,42,13,0x203022,.22)];if(kind==='wood')parts.push(this.add.rectangle(0,8,10,31,0x704628),this.add.circle(-11,-7,16,0x376b3b).setStrokeStyle(2,0x294c2c),this.add.circle(10,-10,18,0x447c43).setStrokeStyle(2,0x294c2c),this.add.circle(0,-23,15,0x4d884b).setStrokeStyle(2,0x294c2c));if(kind==='food')parts.push(this.add.ellipse(0,5,37,25,0x507f3d).setStrokeStyle(2,0x34562d),this.add.circle(-9,0,4,0xd94e3e),this.add.circle(4,-5,4,0xe56a43),this.add.circle(11,5,4,0xd94e3e));if(kind==='gold')parts.push(this.add.triangle(-9,5,-14,13,0,-15,12,13,0xd9af42).setStrokeStyle(2,0x7d6329),this.add.triangle(10,7,-12,12,0,-12,12,12,0xf0c85c).setStrokeStyle(2,0x7d6329));const shape=this.add.container(x,y,parts).setDepth(3);const label=this.add.text(x,y+28,kind==='wood'?'木':kind==='food'?'食':'金',{fontSize:'10px',color:'#fff8df',backgroundColor:'#172018cc',padding:{x:4,y:2}}).setOrigin(.5,0).setDepth(4);this.resources.push({id:this.nextId++,kind,x,y,amount:kind==='wood'?520:380,shape,label})}
 addBuilding(kind:BuildingKind,owner:Owner,x:number,y:number,progress=0){const size=kind==='town'?124:kind==='barracks'?104:76,friendly=owner==='player',team=friendly?0x3978bd:0xb8473f,wall=kind==='town'?0xc4b58d:0xd0bd91,roof=friendly?0x35689d:0x8f4038,maxHp=kind==='town'?2400:kind==='barracks'?1400:900,parts:Phaser.GameObjects.GameObject[]=[];parts.push(this.add.ellipse(0,size*.28,size*1.1,size*.28,0x263126,.27),this.add.rectangle(0,5,size,size*.58,wall).setStrokeStyle(3,0x5b4a35),this.add.rectangle(0,-size*.24,size*1.08,size*.24,roof).setStrokeStyle(3,0x3e352e),this.add.rectangle(0,size*.13,size*.17,size*.3,0x533923),this.add.rectangle(-size*.28,4,size*.13,size*.16,0x83b7ce).setStrokeStyle(2,0xf0d991),this.add.rectangle(size*.3,4,size*.12,size*.16,0x83b7ce).setStrokeStyle(2,0xf0d991));if(kind==='town')parts.push(this.add.rectangle(0,-size*.27,size*.28,size*.46,wall).setStrokeStyle(3,0x5b4a35),this.add.rectangle(0,-size*.51,size*.34,size*.15,roof).setStrokeStyle(2,0x3e352e),this.add.rectangle(size*.18,-size*.28,8,34,team));if(kind==='barracks')parts.push(this.add.rectangle(size*.28,-5,8,42,team),this.add.circle(size*.28,-28,6,team));const shape=this.add.container(x,y,parts).setDepth(5).setAlpha(progress<1?.42:1).setData('visualAge',this.faction(owner).age);const names={town:'町の中心',house:'家',barracks:'兵舎'},label=this.add.text(x,y+size*.35,names[kind],{fontSize:'12px',fontStyle:'bold',color:'#fff4d3',backgroundColor:'#172018bb',padding:{x:5,y:2},stroke:'#201a13',strokeThickness:2}).setOrigin(.5).setDepth(6),hpBack=this.add.rectangle(x-size*.42,y-size*.55,size*.84,7,0x251d1b,.9).setOrigin(0,.5).setDepth(7),hpBar=this.add.rectangle(x-size*.42,y-size*.55,size*.84,5,friendly?0x69c56d:0xdc5a50).setOrigin(0,.5).setDepth(8),smoke=this.add.circle(x,y-size*.65,9,0x333a35,.55).setDepth(9).setVisible(false),fire=this.add.circle(x+12,y-size*.45,6,0xf27b32,.85).setDepth(10).setVisible(false);const b:Building={id:this.nextId++,owner,kind,x,y,hp:progress<1?1:maxHp,maxHp,progress,shape,label,hpBack,hpBar,smoke,fire};this.buildings.push(b);this.syncBuilding(b);return b}
 createFog(){for(let y=50;y<WORLD_H;y+=80)for(let x=40;x<WORLD_W;x+=80)this.fog.push({shape:this.add.rectangle(x,y,80,80,0x070b08,.95).setDepth(50),explored:false,visible:false})}
 bindZoom(selector:string,step:number){document.querySelector(selector)!.addEventListener('pointerdown',e=>{e.preventDefault();e.stopPropagation();this.setZoom(this.cameras.main.zoom+step)})}
 isUiPoint(x:number,y:number){return !!document.elementFromPoint(x,y)?.closest(GAME_UI_SELECTOR)}
 setZoom(z:number,snap=true){const zoom=Phaser.Math.Clamp(snap?Math.round(z*20)/20:z,.55,1.25);this.cameras.main.setZoom(zoom);const value=document.querySelector<HTMLOutputElement>('#zoomValue');if(value)value.value=`${Math.round(zoom*100)}%`}
 centerCamera(x:number,y:number){const c=this.cameras.main;c.scrollX=Phaser.Math.Clamp(x-this.scale.width/(2*c.zoom),0,Math.max(0,WORLD_W-this.scale.width/c.zoom));c.scrollY=Phaser.Math.Clamp(y-this.scale.height/(2*c.zoom),0,Math.max(0,WORLD_H-this.scale.height/c.zoom))}
 buildingRadius(b:Building){return b.kind==='town'?72:b.kind==='barracks'?60:46}
 resourceRadius(r:ResourceNode){return r.kind==='wood'?31:r.kind==='gold'?27:23}
 terrainBlocked(x:number,y:number){return x<24||y<70||x>WORLD_W-24||y>WORLD_H-24}
 isBlocked(x:number,y:number){if(this.terrainBlocked(x,y))return true;for(const b of this.buildings)if(Phaser.Math.Distance.Between(x,y,b.x,b.y)<this.buildingRadius(b)+20)return true;for(const r of this.resources)if((r.kind==='wood'||r.kind==='gold')&&Phaser.Math.Distance.Between(x,y,r.x,r.y)<this.resourceRadius(r)+16)return true;return false}
 canPlace(kind:BuildingKind,x:number,y:number){const radius=kind==='town'?76:kind==='barracks'?62:48;if(this.terrainBlocked(x,y)||x<radius+20||y<radius+80||x>WORLD_W-radius-20||y>WORLD_H-radius-20)return false;for(const b of this.buildings)if(Phaser.Math.Distance.Between(x,y,b.x,b.y)<radius+this.buildingRadius(b)+18)return false;for(const r of this.resources)if(Phaser.Math.Distance.Between(x,y,r.x,r.y)<radius+this.resourceRadius(r)+12)return false;let openSides=0;for(const [dx,dy] of [[radius+55,0],[-radius-55,0],[0,radius+55],[0,-radius-55]])if(!this.isBlocked(x+dx,y+dy))openSides++;return openSides>=2}
 setPath(u:Unit,x:number,y:number){const open=this.pathfinder.nearestOpen(x,y);u.target=open??{x,y};u.path=this.pathfinder.find(u.x,u.y,u.target.x,u.target.y);u.pathIndex=0;if(!u.path.length&&!this.isBlocked(x,y))u.path=[{x,y}]}
 setPathNear(u:Unit,t:AttackTarget|ResourceNode,extra=0){const radius=('kind'in t&&'maxHp'in t)?this.targetRadius(t):'amount'in t?this.resourceRadius(t):0,start=Phaser.Math.Angle.Between(t.x,t.y,u.x,u.y),distance=radius+this.unitRadius(u)+extra+18;let best:{point:Point;path:Point[];score:number}|undefined;for(let i=0;i<16;i++){const angle=start+i*Math.PI*2/16,candidate={x:t.x+Math.cos(angle)*distance,y:t.y+Math.sin(angle)*distance};if(this.isBlocked(candidate.x,candidate.y))continue;const path=this.pathfinder.find(u.x,u.y,candidate.x,candidate.y);if(!path.length&&Phaser.Math.Distance.Between(u.x,u.y,candidate.x,candidate.y)>12)continue;const occupied=this.units.some(other=>other!==u&&Phaser.Math.Distance.Between(candidate.x,candidate.y,other.x,other.y)<this.unitRadius(u)+this.unitRadius(other)+3),score=path.length*60+Phaser.Math.Distance.Between(u.x,u.y,candidate.x,candidate.y)+(occupied?140:0);if(!best||score<best.score)best={point:candidate,path,score}}if(best){u.target=best.point;u.path=best.path.length?best.path:[best.point];u.pathIndex=0}else this.setPath(u,t.x+Math.cos(start)*distance,t.y+Math.sin(start)*distance)}
 followPath(u:Unit,dt:number){if(!u.path.length||u.pathIndex>=u.path.length)return false;const p=u.path[u.pathIndex],d=Phaser.Math.Distance.Between(u.x,u.y,p.x,p.y);if(d<Math.max(5,u.speed*dt*1.3)){u.pathIndex++;if(u.pathIndex>=u.path.length)return false}const next=u.path[Math.min(u.pathIndex,u.path.length-1)],heading=Phaser.Math.Angle.Between(u.x,u.y,next.x,next.y),step=u.speed*dt,desired={x:u.x+Math.cos(heading)*step,y:u.y+Math.sin(heading)*step},blocker=this.units.find(other=>other!==u&&Phaser.Math.Distance.Between(desired.x,desired.y,other.x,other.y)<this.unitRadius(u)+this.unitRadius(other)+1);if(!blocker&&!this.isBlocked(desired.x,desired.y)){u.x=desired.x;u.y=desired.y;return true}if(blocker){let best:Point|undefined,bestScore=Infinity;for(const turn of avoidanceTurns(u.id,blocker.id)){const candidate={x:u.x+Math.cos(heading+turn)*step*.82,y:u.y+Math.sin(heading+turn)*step*.82};if(this.isBlocked(candidate.x,candidate.y))continue;const occupied=this.units.some(other=>other!==u&&Phaser.Math.Distance.Between(candidate.x,candidate.y,other.x,other.y)<this.unitRadius(u)+this.unitRadius(other));if(occupied)continue;const score=Phaser.Math.Distance.Between(candidate.x,candidate.y,next.x,next.y);if(score<bestScore){best=candidate;bestScore=score}}if(best){u.x=best.x;u.y=best.y;return true}}return false}
 formationSlots(count:number,x:number,y:number,spacing=42){const cols=Math.ceil(Math.sqrt(count)),rows=Math.ceil(count/cols),slots:Point[]=[];for(let i=0;i<count;i++){const col=i%cols,row=Math.floor(i/cols);slots.push({x:x+(col-(Math.min(cols,count)-1)/2)*spacing,y:y+(row-(rows-1)/2)*spacing})}return slots}
 activeTouches(){return this.input.manager.pointers.filter(pointer=>pointer.isDown&&pointer.wasTouch)}
 beginPinch(touches:Phaser.Input.Pointer[]){const [a,b]=touches,midX=(a.x+b.x)/2,midY=(a.y+b.y)/2,world=this.cameras.main.getWorldPoint(midX,midY);this.pinch={distance:Math.max(1,Phaser.Math.Distance.Between(a.x,a.y,b.x,b.y)),zoom:this.cameras.main.zoom,worldX:world.x,worldY:world.y};this.touchStart=undefined;this.suppressTouch=true}
 setRangeSelecting(on:boolean){this.rangeSelecting=on;const button=document.querySelector<HTMLButtonElement>('#rangeSelect')!;button.classList.toggle('active',on);button.setAttribute('aria-pressed',String(on));if(on)this.say('選択したい味方を指で囲んでください')}
 onDown(p:Phaser.Input.Pointer){if(p.y<UI_TOP||this.isUiPoint(p.x,p.y))return;const w=new Phaser.Math.Vector2(p.worldX,p.worldY);if(this.placing&&!p.wasTouch){if(p.rightButtonDown()){this.cancelPlacement();return}this.updatePlacementGhost(w.x,w.y);if(this.placementValid)this.place(w.x,w.y);return}if(p.wasTouch){if(this.rangeSelecting){this.selectStart=w;this.selectBox=this.add.rectangle(w.x,w.y,1,1,0x8fb7d0,.18).setStrokeStyle(2,0xd3e9f5).setOrigin(0).setDepth(45);return}const touches=this.activeTouches();if(touches.length>=2){this.beginPinch(touches);return}if(this.suppressTouch)return;const c=this.cameras.main;this.touchStart={sx:p.x,sy:p.y,wx:w.x,wy:w.y,cx:c.scrollX,cy:c.scrollY,moved:false};return}if(p.rightButtonDown()){this.command(w.x,w.y);return}this.selectStart=w;this.selectBox=this.add.rectangle(w.x,w.y,1,1,0x8fb7d0,.18).setStrokeStyle(2,0xd3e9f5).setOrigin(0).setDepth(45)}
 onMove(p:Phaser.Input.Pointer){if(this.placing){this.updatePlacementGhost(p.worldX,p.worldY);if(p.wasTouch&&!p.isDown)return}if(p.wasTouch){const touches=this.activeTouches();if(touches.length>=2){if(!this.pinch)this.beginPinch(touches);const [a,b]=touches,midX=(a.x+b.x)/2,midY=(a.y+b.y)/2,c=this.cameras.main;this.setZoom(this.pinch!.zoom*Phaser.Math.Distance.Between(a.x,a.y,b.x,b.y)/this.pinch!.distance,false);const world=c.getWorldPoint(midX,midY);c.scrollX+=this.pinch!.worldX-world.x;c.scrollY+=this.pinch!.worldY-world.y;return}if(this.suppressTouch)return}if(this.touchStart&&p.isDown){const t=this.touchStart,dx=p.x-t.sx,dy=p.y-t.sy;if(Math.hypot(dx,dy)>9)t.moved=true;if(t.moved){const c=this.cameras.main;c.scrollX=t.cx-dx/c.zoom;c.scrollY=t.cy-dy/c.zoom}return}if(!this.selectStart||!this.selectBox)return;const w=new Phaser.Math.Vector2(p.worldX,p.worldY),x=Math.min(w.x,this.selectStart.x),y=Math.min(w.y,this.selectStart.y);this.selectBox.setPosition(x,y).setSize(Math.abs(w.x-this.selectStart.x),Math.abs(w.y-this.selectStart.y))}
 onUp(p:Phaser.Input.Pointer){if(p.wasTouch&&(this.pinch||this.suppressTouch)){this.pinch=undefined;this.touchStart=undefined;if(this.activeTouches().length===0)this.suppressTouch=false;return}if(this.touchStart){const t=this.touchStart;this.touchStart=undefined;if(!t.moved)this.handleTap(t.wx,t.wy);return}if(!this.selectStart)return;const start=this.selectStart,w=new Phaser.Math.Vector2(p.worldX,p.worldY),d=Phaser.Math.Distance.Between(w.x,w.y,start.x,start.y);this.selectStart=undefined;this.selectBox?.destroy();this.selectBox=undefined;if(d<8){this.handleTap(w.x,w.y);return}this.selectedBuilding=undefined;this.units.filter(u=>u.owner==='player').forEach(u=>{u.selected=u.x>=Math.min(w.x,start.x)&&u.x<=Math.max(w.x,start.x)&&u.y>=Math.min(w.y,start.y)&&u.y<=Math.max(w.y,start.y);u.ring.setVisible(u.selected)});this.refreshSelectionUi(true);if(this.rangeSelecting)this.setRangeSelecting(false)}
 clearSelection(){for(const u of this.units){u.selected=false;u.ring.setVisible(false)}if(this.selectedBuilding)this.selectedBuilding.shape.setScale(1);this.selectedBuilding=undefined}
 selectBuilding(b:Building){this.clearSelection();this.selectedBuilding=b;b.shape.setScale(1.04);this.refreshSelectionUi(true);this.say(`${this.buildingName(b.kind)}を選択`)}
 handleTap(x:number,y:number){if(this.placing){this.updatePlacementGhost(x,y);if(this.placementValid)this.place(x,y);else this.say('ここには建設できません');return}const selectedUnits=this.units.some(u=>u.selected&&u.owner==='player'),nearEnemy=this.units.some(u=>u.owner==='enemy'&&this.isVisibleAt(u.x,u.y)&&Phaser.Math.Distance.Between(u.x,u.y,x,y)<40);if(selectedUnits&&nearEnemy){this.command(x,y);return}const own=this.units.find(u=>u.owner==='player'&&Phaser.Math.Distance.Between(u.x,u.y,x,y)<this.unitRadius(u)+12);if(own){this.clearSelection();own.selected=true;own.ring.setVisible(true);this.refreshSelectionUi(true);this.say(`${this.unitName(own.type)}を選択`);return}const ownBuilding=this.buildings.find(b=>b.owner==='player'&&Phaser.Math.Distance.Between(b.x,b.y,x,y)<this.buildingRadius(b));if(ownBuilding){const selectedTypes=this.units.filter(u=>u.selected&&u.owner==='player').map(u=>u.type);if(shouldResumeConstructionOnTap(ownBuilding.owner,ownBuilding.progress,selectedTypes)){this.command(ownBuilding.x,ownBuilding.y);return}this.selectBuilding(ownBuilding);return}if(this.units.some(u=>u.selected&&u.owner==='player'))this.command(x,y);else{this.clearSelection();this.refreshSelectionUi(true)}}
 command(x:number,y:number){const selected=this.units.filter(u=>u.selected&&u.owner==='player');if(!selected.length)return;const foe=this.units.find(u=>u.owner==='enemy'&&this.isVisibleAt(u.x,u.y)&&Phaser.Math.Distance.Between(u.x,u.y,x,y)<40),enemyBuilding=this.buildings.find(b=>b.owner==='enemy'&&this.isVisibleAt(b.x,b.y)&&Phaser.Math.Distance.Between(b.x,b.y,x,y)<this.buildingRadius(b)+18),unfinished=this.buildings.find(b=>canContinueConstruction(b.owner,b.progress,Phaser.Math.Distance.Between(b.x,b.y,x,y),this.buildingRadius(b))),res=this.resources.find(r=>Phaser.Math.Distance.Between(r.x,r.y,x,y)<38),attack=foe??enemyBuilding,builders=unfinished?selected.filter(u=>isBuilderUnit(u.type)):[],slots=this.formationSlots(selected.length,x,y,selected.some(u=>u.type!=='villager')?44:34);selected.forEach((u,i)=>{u.build=builders.includes(u)?unfinished:undefined;u.attack=attack;u.resource=!attack&&!unfinished&&u.type==='villager'?res:undefined;u.returning=false;if(!res){u.cargo=0;u.cargoKind=undefined}if(attack)this.setCombatPath(u,attack);else if(u.build)this.setPathNear(u,u.build,10+i*3);else if(res)this.setPathNear(u,res,4);else this.setPath(u,slots[i].x,slots[i].y)});this.say(attack?`${'kind'in attack?'敵の建物':'敵'}を攻撃します`:unfinished&&builders.length?`${builders.length}人で${this.buildingName(unfinished.kind)}の建設を続けます`:unfinished?'建設には町人を選択してください':res?`${this.resourceName(res.kind)}を採集して町へ運びます`:'隊列で移動します')}
 beginPlace(kind:BuildingKind){const woodCost=kind==='town'?450:kind==='house'?80:140,goldCost=kind==='town'?250:0;if(kind==='town'&&player.age<3){this.say('城主の時代が必要です');return}if(player.wood<woodCost||player.gold<goldCost){this.say('資源が足りません');return}if(!this.units.some(u=>u.selected&&u.owner==='player'&&u.type==='villager')){this.say('建設する町人を選択してください');return}this.cancelPlacement();this.placing=kind;const center=this.cameras.main.midPoint;this.placementGhost=this.add.rectangle(center.x,center.y,kind==='town'?142:kind==='house'?86:116,kind==='town'?110:kind==='house'?68:82,0x7dcf86,.42).setStrokeStyle(3,0xdff6d8).setDepth(44);document.querySelector('#cancelPlacement')!.classList.add('show');this.updatePlacementGhost(center.x,center.y);this.say('場所を選択してください。赤色の場所には建設できません')}
 updatePlacementGhost(x:number,y:number){if(!this.placing||!this.placementGhost)return;this.placementValid=this.canPlace(this.placing,x,y);this.placementGhost.setPosition(x,y).setFillStyle(this.placementValid?0x7dcf86:0xdc514c,.42).setStrokeStyle(3,this.placementValid?0xdff6d8:0xffb0a9)}
 cancelPlacement(){this.placing=undefined;this.placementValid=false;this.placementGhost?.destroy();this.placementGhost=undefined;document.querySelector('#cancelPlacement')?.classList.remove('show')}
 place(x:number,y:number){const kind=this.placing!;if(!kind||!this.canPlace(kind,x,y)){this.say('ここには建設できません');return}const woodCost=kind==='town'?450:kind==='house'?80:140,goldCost=kind==='town'?250:0;player.wood-=woodCost;player.gold-=goldCost;this.placementGhost?.destroy();this.placementGhost=undefined;document.querySelector('#cancelPlacement')!.classList.remove('show');const b=this.addBuilding(kind,'player',x,y,0);this.units.filter(u=>u.selected&&u.type==='villager'&&u.owner==='player').forEach((u,i)=>{u.attack=undefined;u.resource=undefined;u.build=b;this.setPathNear(u,b,12+i*3)});this.placing=undefined;this.refreshUi();this.say(`${this.buildingName(kind)}の建設を開始します`)}
 train(type:UnitType,owner:Owner){const f=this.faction(owner),town=this.buildings.find(b=>b.owner===owner&&b.kind==='town'&&b.progress>=1),barracks=this.buildings.find(b=>b.owner===owner&&b.kind==='barracks'&&b.progress>=1),costs={villager:[0,50,0],soldier:[0,60,30],archer:[0,45,45],cavalry:[0,80,70]}[type],required=type==='archer'?2:type==='cavalry'?3:1,source=type==='villager'?town:barracks;if(f.age<required){if(owner==='player')this.say(`${ages[required-1]}が必要です`);return}if(!source){if(owner==='player')this.say(type==='villager'?'町の中心が必要です':'完成した兵舎が必要です');return}if(f.wood<costs[0]||f.food<costs[1]||f.gold<costs[2]){if(owner==='player')this.say('資源が足りません');return}if(this.units.filter(u=>u.owner===owner).length+this.pendingTraining[owner]>=f.popCap){if(owner==='player')this.say('人口上限です。家を建ててください');return}f.wood-=costs[0];f.food-=costs[1];f.gold-=costs[2];this.pendingTraining[owner]++;this.refreshUi();if(owner==='player')this.say(`${this.unitName(type)}を訓練中…`);const duration={villager:4000,soldier:5000,archer:6000,cavalry:7000}[type];this.time.delayedCall(duration,()=>{this.pendingTraining[owner]=Math.max(0,this.pendingTraining[owner]-1);if(this.buildings.includes(source))this.addUnit(type,owner,source.x+(owner==='player'?75:-75),source.y+45);this.refreshUi();if(owner==='player'&&this.buildings.includes(source))this.say(`${this.unitName(type)}が完成しました`)})}
 advanceAge(){if(player.age>=4){this.say('すでに帝王の時代です');return}const costs=[[300,150],[500,300],[800,500]][player.age-1];if(player.food<costs[0]||player.gold<costs[1]){this.say('時代進化に必要な資源が足りません');return}player.food-=costs[0];player.gold-=costs[1];player.age++;this.refreshFactionVisuals('player');this.refreshUi();this.say(`${ages[player.age-1]}へ進化しました`)}
 research(tech:Tech){if(player.researched.has(tech)){this.say('研究済みです');return}const req=tech==='armor'?3:2;if(player.age<req){this.say(`${ages[req-1]}が必要です`);return}const costs={attack:[150,0,100],economy:[120,100,0],armor:[180,0,140]}[tech];if(player.wood<costs[0]||player.food<costs[1]||player.gold<costs[2]){this.say('研究に必要な資源が足りません');return}player.wood-=costs[0];player.food-=costs[1];player.gold-=costs[2];player.researched.add(tech);if(tech==='attack')player.attackBonus=.2;if(tech==='economy')player.gatherBonus=.25;if(tech==='armor'){player.armorBonus=.18;for(const u of this.units.filter(u=>u.owner==='player')){u.maxHp*=1.2;u.hp*=1.2}}this.refreshFactionVisuals('player');this.refreshUi();this.say(`${tech==='attack'?'武器':tech==='economy'?'採集':'防具'}研究が完了しました`)}
 update(time:number,delta:number){if(!this.started||this.result)return;const dt=Math.min(delta/1000,.05);this.moveCamera(dt);this.updateBuildings(dt);this.engageOnContact();this.updateUnits(time,dt);this.updateProjectiles(dt);if(time-this.lastAuto>250){this.autoAcquire();this.lastAuto=time}if(time-this.lastFog>240){this.updateFog();this.lastFog=time}if(time-this.lastMini>350){this.updateMiniMap();this.lastMini=time}if(time-this.lastAi>1800){this.enemyAi(time);this.lastAi=time}if(!this.buildings.some(b=>b.owner==='enemy'&&b.kind==='town'))this.finish('player');if(!this.buildings.some(b=>b.owner==='player'&&b.kind==='town'))this.finish('enemy');this.refreshUi();this.refreshSelectionUi()}
 moveCamera(dt:number){if(this.touchStart||this.pinch||this.suppressTouch)return;const c=this.cameras.main,p=this.input.activePointer,s=520*dt/c.zoom,edge=!p.wasTouch&&p.x>0&&p.y>0&&!this.isUiPoint(p.x,p.y);let dx=0,dy=0;if(this.keys.A.isDown||this.keys.LEFT.isDown||(edge&&p.x<8))dx=-s;if(this.keys.D.isDown||this.keys.RIGHT.isDown||(edge&&p.x>this.scale.width-8))dx=s;if(this.keys.W.isDown||this.keys.UP.isDown||(edge&&p.y<UI_TOP+4))dy=-s;if(this.keys.S.isDown||this.keys.DOWN.isDown||(edge&&p.y>this.scale.height-8))dy=s;c.scrollX+=dx;c.scrollY+=dy}
 updateBuildings(dt:number){for(const b of this.buildings){if(b.progress<1){const builders=this.units.filter(u=>u.owner===b.owner&&u.type==='villager'&&u.build===b&&Phaser.Math.Distance.Between(u.x,u.y,b.x,b.y)<this.buildingRadius(b)+this.unitRadius(u)+42);if(builders.length){b.progress=Math.min(1,b.progress+dt*.18*Math.min(builders.length,3));b.hp=Math.max(b.hp,b.maxHp*b.progress);b.shape.setAlpha(.38+.62*b.progress);b.label.setText(`${this.buildingName(b.kind)} ${Math.floor(b.progress*100)}%`);if(b.progress>=1){b.label.setText(this.buildingName(b.kind));if(b.kind==='house')this.faction(b.owner).popCap+=5;for(const u of builders){u.build=undefined;u.target=undefined;u.path=[]}if(b.owner==='player')this.say(`${this.buildingName(b.kind)}が完成しました${b.kind==='house'?'。人口上限 +5':''}`)}}}this.syncBuilding(b)}}
 targetAlive(t:AttackTarget){return'type'in t?this.units.includes(t):this.buildings.includes(t)}
 targetRadius(t:AttackTarget){return'type'in t?this.unitRadius(t):t.kind==='town'?55:t.kind==='barracks'?46:34}
 attackReach(u:Unit,t:AttackTarget){return calculateAttackReach(u.range,this.targetRadius(t))}
 setCombatPath(u:Unit,t:AttackTarget){const radius=this.targetRadius(t),reach=this.attackReach(u,t),desired=combatStandDistance(this.unitRadius(u),radius,reach),approach=Phaser.Math.Angle.Between(t.x,t.y,u.x,u.y);if(u.combatTargetId!==t.id){u.combatTargetId=t.id;u.combatAngle=approach+combatSlotOffset(u.id,t.id)}const preferred=u.combatAngle??approach,steps=[0,1,-1,2,-2,3,-3,4,-4,5,-5,6,-6,7,-7,8];let best:{point:Point;path:Point[];score:number}|undefined;for(const step of steps){const angle=preferred+step*Math.PI*2/16,candidate={x:t.x+Math.cos(angle)*desired,y:t.y+Math.sin(angle)*desired};if(this.isBlocked(candidate.x,candidate.y))continue;const path=this.pathfinder.find(u.x,u.y,candidate.x,candidate.y);if(!path.length&&Phaser.Math.Distance.Between(u.x,u.y,candidate.x,candidate.y)>12)continue;const occupied=this.units.some(other=>other!==u&&other.owner===u.owner&&Phaser.Math.Distance.Between(candidate.x,candidate.y,other.x,other.y)<this.unitRadius(u)+this.unitRadius(other)+4);const score=path.length*60+Phaser.Math.Distance.Between(u.x,u.y,candidate.x,candidate.y)+Math.abs(step)*22+(occupied?320:0);if(!best||score<best.score)best={point:candidate,path,score}}if(best){u.target=best.point;u.path=best.path.length?best.path:[best.point];u.pathIndex=0;u.lastPathIndex=-1}else this.setPath(u,t.x,t.y);u.attackTrackX=t.x;u.attackTrackY=t.y}
 engageOnContact(){for(const u of this.units){if(u.type==='villager')continue;let closest:Unit|undefined,nearest=Infinity;for(const foe of this.units){if(foe.owner===u.owner)continue;const d=Phaser.Math.Distance.Between(u.x,u.y,foe.x,foe.y);if(d<=contactDistance(this.unitRadius(u),this.unitRadius(foe))&&d<nearest){closest=foe;nearest=d}}if(!closest)continue;const currentAlive=!!u.attack&&this.targetAlive(u.attack),currentDistance=currentAlive?Phaser.Math.Distance.Between(u.x,u.y,u.attack!.x,u.attack!.y):Infinity,currentReach=currentAlive?this.attackReach(u,u.attack!):0;if(!shouldTakeContactTarget(currentAlive,currentDistance,currentReach,u.attack===closest))continue;u.attack=closest;u.resource=undefined;u.build=undefined;u.path=[];u.target={x:closest.x,y:closest.y};if(closest.type!=='villager'&&closest.attack!==u){const defenderAlive=!!closest.attack&&this.targetAlive(closest.attack),defenderDistance=defenderAlive?Phaser.Math.Distance.Between(closest.x,closest.y,closest.attack!.x,closest.attack!.y):Infinity,defenderReach=defenderAlive?this.attackReach(closest,closest.attack!):0;if(shouldTakeContactTarget(defenderAlive,defenderDistance,defenderReach,false)){closest.attack=u;closest.resource=undefined;closest.build=undefined;closest.path=[];closest.target={x:u.x,y:u.y}}}}}
 updateUnits(time:number,dt:number){for(const u of [...this.units]){if(!this.units.includes(u))continue;if(u.attack&&!this.targetAlive(u.attack)){u.attack=undefined;u.target=undefined;u.path=[];u.combatTargetId=undefined}if(u.resource&&!this.resources.includes(u.resource)&&!u.returning){u.resource=undefined;u.path=[]}if(u.resource)this.updateGatherOrder(u,dt,time);if(u.attack){const distance=Phaser.Math.Distance.Between(u.x,u.y,u.attack.x,u.attack.y),range=this.attackReach(u,u.attack);if(distance>range){const targetMoved=Phaser.Math.Distance.Between(u.attackTrackX??u.attack.x,u.attackTrackY??u.attack.y,u.attack.x,u.attack.y);if(shouldRepathCombat(u.pathIndex<u.path.length,targetMoved))this.setCombatPath(u,u.attack);this.followPath(u,dt)}else{u.path=[];u.pathIndex=0;u.stall=0;if(time>=u.nextAttack){u.nextAttack=time+(u.type==='archer'?900:u.type==='villager'?1050:700);u.attackAnimUntil=time+260;if(u.type==='archer')this.shootArrow(u,u.attack);else this.dealDamage(u,u.attack)}}}else if(!u.resource)this.followPath(u,dt)}this.separateUnits();this.resolveStalls(dt);for(const u of this.units)this.syncUnit(u,time)}
 updateGatherOrder(u:Unit,dt:number,time:number){const r=u.resource!,town=this.buildings.find(b=>b.owner===u.owner&&b.kind==='town'&&b.progress>=1);if(!town){u.resource=undefined;u.path=[];return}const target=u.returning?town:r,stop=u.returning?this.targetRadius(town)+this.unitRadius(u)+70:this.resourceRadius(r)+this.unitRadius(u)+70,distance=Phaser.Math.Distance.Between(u.x,u.y,target.x,target.y);if(distance>stop){if(time>=u.repathAt||!u.path.length){this.setPathNear(u,target,8);u.repathAt=time+900}this.followPath(u,dt);return}u.path=[];if(u.returning){if(u.cargoKind)this.faction(u.owner)[u.cargoKind]+=u.cargo;u.cargo=0;u.cargoKind=undefined;u.returning=false;if(this.resources.includes(r))this.setPathNear(u,r,8);else{u.resource=undefined;u.target=undefined}return}const qty=Math.min(r.amount,8*(1+this.faction(u.owner).gatherBonus)*dt,20-u.cargo);r.amount-=qty;u.cargo+=qty;u.cargoKind=r.kind;if(r.amount<=0){r.shape.destroy();r.label.destroy();this.resources=this.resources.filter(x=>x!==r)}if(u.cargo>=19.9||r.amount<=0){u.returning=true;u.path=[];this.setPathNear(u,town,8)}}
 autoAcquire(){for(const u of this.units.filter(u=>u.type!=='villager'&&!u.attack&&!u.build)){let best:AttackTarget|undefined,dist=u.sight;for(const foe of this.units.filter(x=>x.owner!==u.owner)){if(u.owner==='player'&&!this.isVisibleAt(foe.x,foe.y))continue;const d=Phaser.Math.Distance.Between(u.x,u.y,foe.x,foe.y);if(d<dist){dist=d;best=foe}}if(!best)for(const b of this.buildings.filter(x=>x.owner!==u.owner&&x.progress>=1)){if(u.owner==='player'&&!this.isVisibleAt(b.x,b.y))continue;const d=Phaser.Math.Distance.Between(u.x,u.y,b.x,b.y)-this.targetRadius(b);if(d<dist){dist=d;best=b}}if(best){u.attack=best;this.setCombatPath(u,best)}}}
 dealDamage(attacker:Unit,defender:AttackTarget){const counters:Record<UnitType,Partial<Record<UnitType,number>>>={villager:{},soldier:{cavalry:1.65},archer:{soldier:1.55},cavalry:{archer:1.75}},isUnit='type'in defender,mult=isUnit?(counters[attacker.type][defender.type]??1):attacker.type==='villager'?.65:1,raw=attacker.damage*(1+this.faction(attacker.owner).attackBonus)*mult;defender.hp-=raw*(1-this.faction(defender.owner).armorBonus);if(defender.hp<=0){if(isUnit)this.removeUnit(defender);else this.removeBuilding(defender);return}if(isUnit&&defender.type!=='villager'&&(!defender.attack||!this.targetAlive(defender.attack))){defender.attack=attacker;defender.resource=undefined;defender.target={x:attacker.x,y:attacker.y}}if(!isUnit)this.syncBuilding(defender)}
 shootArrow(attacker:Unit,target:AttackTarget){if(this.projectiles.length>=60)return;const angle=Phaser.Math.Angle.Between(attacker.x,attacker.y,target.x,target.y),shape=this.add.rectangle(attacker.x,attacker.y-8,18,3,0xe7d1a0).setRotation(angle).setDepth(22);this.projectiles.push({shape,x:attacker.x,y:attacker.y-8,target,attacker,speed:430})}
 updateProjectiles(dt:number){for(const p of [...this.projectiles]){if(!this.targetAlive(p.target)){p.shape.destroy();this.projectiles=this.projectiles.filter(x=>x!==p);continue}const tx=p.target.x,ty=p.target.y-5,d=Phaser.Math.Distance.Between(p.x,p.y,tx,ty);if(d<p.speed*dt+8){this.dealDamage(p.attacker,p.target);p.shape.destroy();this.projectiles=this.projectiles.filter(x=>x!==p);continue}const a=Phaser.Math.Angle.Between(p.x,p.y,tx,ty);p.x+=Math.cos(a)*p.speed*dt;p.y+=Math.sin(a)*p.speed*dt;p.shape.setPosition(p.x,p.y).setRotation(a)}}
 removeUnit(u:Unit){u.shape.destroy();u.ring.destroy();u.hpBack.destroy();u.hpBar.destroy();u.label.destroy();this.units=this.units.filter(x=>x!==u);for(const x of this.units)if(x.attack===u){x.attack=undefined;x.target=undefined}}
 removeBuilding(b:Building){const rubble=[this.add.rectangle(b.x,b.y+18,this.buildingRadius(b)*1.4,22,0x665846,.8).setDepth(4),this.add.circle(b.x-18,b.y+8,11,0x4b4338,.85).setDepth(5),this.add.circle(b.x+16,b.y+13,9,0x55483a,.85).setDepth(5)];this.tweens.add({targets:rubble,alpha:0,duration:4200,onComplete:()=>rubble.forEach(x=>x.destroy())});b.shape.destroy();b.label.destroy();b.hpBack.destroy();b.hpBar.destroy();b.smoke.destroy();b.fire.destroy();this.buildings=this.buildings.filter(x=>x!==b);if(this.selectedBuilding===b){this.selectedBuilding=undefined;this.refreshSelectionUi(true)}if(b.kind==='house'&&b.progress>=1)this.faction(b.owner).popCap=Math.max(10,this.faction(b.owner).popCap-5);for(const u of this.units){if(u.attack===b){u.attack=undefined;u.target=undefined;u.path=[]}if(u.build===b){u.build=undefined;u.target=undefined;u.path=[]}}if(b.owner==='player')this.say(`${this.buildingName(b.kind)}が破壊されました`)}
 unitRadius(u:Unit){return u.type==='cavalry'?24:u.type==='villager'?14:17}
 separateUnits(){for(let pass=0;pass<2;pass++)for(let i=0;i<this.units.length;i++)for(let j=i+1;j<this.units.length;j++){const a=this.units[i],b=this.units[j],min=this.unitRadius(a)+this.unitRadius(b)+2,dx=b.x-a.x,dy=b.y-a.y,dist=Math.hypot(dx,dy);if(dist>=min)continue;const angle=dist>.01?Math.atan2(dy,dx):((a.id*37+b.id*17)%360)*Math.PI/180,safeDx=dist>.01?dx:Math.cos(angle),safeDy=dist>.01?dy:Math.sin(angle),push=(min-Math.max(dist,.01))/2+.15,aMoving=a.pathIndex<a.path.length,bMoving=b.pathIndex<b.path.length,offset=separationOffsets(safeDx,safeDy,push,aMoving,bMoving,a.owner===b.owner,a.id,b.id),ax=Phaser.Math.Clamp(a.x+offset.ax,18,WORLD_W-18),ay=Phaser.Math.Clamp(a.y+offset.ay,85,WORLD_H-18),bx=Phaser.Math.Clamp(b.x+offset.bx,18,WORLD_W-18),by=Phaser.Math.Clamp(b.y+offset.by,85,WORLD_H-18);if(!this.isBlocked(ax,ay)){a.x=ax;a.y=ay}if(!this.isBlocked(bx,by)){b.x=bx;b.y=by}}}
 resolveStalls(dt:number){for(const u of this.units){const moving=u.pathIndex<u.path.length;if(!moving){u.stall=0;u.lastPathIndex=-1;u.lastWaypointDistance=Infinity;continue}const waypoint=u.path[u.pathIndex],remaining=Phaser.Math.Distance.Between(u.x,u.y,waypoint.x,waypoint.y),sameWaypoint=u.lastPathIndex===u.pathIndex,progress=sameWaypoint?u.lastWaypointDistance-remaining:Infinity;u.stall=sameWaypoint&&progress<.04?u.stall+dt:0;u.lastX=u.x;u.lastY=u.y;u.lastPathIndex=u.pathIndex;u.lastWaypointDistance=remaining;if(u.stall<.45)continue;const heading=Phaser.Math.Angle.Between(u.x,u.y,waypoint.x,waypoint.y),side=u.id%2?1:-1;let detour:Point|undefined,best=Infinity;for(const distance of [48,68,88])for(const turn of [side*Math.PI/3,-side*Math.PI/3,side*Math.PI/2,-side*Math.PI/2]){const open=this.pathfinder.nearestOpen(u.x+Math.cos(heading+turn)*distance,u.y+Math.sin(heading+turn)*distance,2);if(!open)continue;const occupied=this.units.some(other=>other!==u&&other.owner===u.owner&&Phaser.Math.Distance.Between(open.x,open.y,other.x,other.y)<this.unitRadius(u)+this.unitRadius(other)+5);if(occupied)continue;const score=Phaser.Math.Distance.Between(open.x,open.y,waypoint.x,waypoint.y);if(score<best){best=score;detour=open}}if(detour)u.path.splice(u.pathIndex,0,detour);else if(u.target)this.setPath(u,u.target.x,u.target.y);u.stall=0;u.lastPathIndex=-1;u.lastWaypointDistance=Infinity}}
 enemyAi(time:number){const workers=this.units.filter(u=>u.owner==='enemy'&&u.type==='villager');for(const w of workers.filter(u=>!u.resource&&!u.build&&!u.attack)){const preferred=enemy.food<180?'food':enemy.wood<150?'wood':'gold',choices=this.resources.filter(r=>r.kind===preferred),r=choices.sort((a,b)=>Phaser.Math.Distance.Between(w.x,w.y,a.x,a.y)-Phaser.Math.Distance.Between(w.x,w.y,b.x,b.y))[0]??this.resources[0];if(r){w.resource=r;this.setPathNear(w,r,5)}}const count=this.units.filter(u=>u.owner==='enemy').length;if(enemy.popCap-count<=2&&enemy.wood>=80&&!this.buildings.some(b=>b.owner==='enemy'&&b.kind==='house'&&b.progress<1)){const pos=this.findBuildSite('enemy','house');if(pos){enemy.wood-=80;this.enemyBuild('house',pos.x,pos.y)}}if(!this.buildings.some(b=>b.owner==='enemy'&&b.kind==='barracks')&&enemy.wood>=140){const pos=this.findBuildSite('enemy','barracks');if(pos){enemy.wood-=140;this.enemyBuild('barracks',pos.x,pos.y)}}if(enemy.age<4&&time>[0,65000,145000,235000][enemy.age]&&enemy.food>350&&enemy.gold>180){enemy.food-=300;enemy.gold-=150;enemy.age++}const military=this.units.filter(u=>u.owner==='enemy'&&u.type!=='villager');if(this.buildings.some(b=>b.owner==='enemy'&&b.kind==='barracks'&&b.progress>=1)&&military.length<10){const t=enemy.age>=3&&Math.random()>.55?'cavalry':enemy.age>=2&&Math.random()>.45?'archer':'soldier';this.train(t,'enemy')}if(time>45000&&military.length>=3)for(const u of military.filter(x=>!x.attack)){const unitTargets=this.units.filter(x=>x.owner==='player'),t:AttackTarget|undefined=unitTargets.sort((a,b)=>Phaser.Math.Distance.Between(u.x,u.y,a.x,a.y)-Phaser.Math.Distance.Between(u.x,u.y,b.x,b.y))[0]??this.buildings.filter(b=>b.owner==='player').sort((a,b)=>Phaser.Math.Distance.Between(u.x,u.y,a.x,a.y)-Phaser.Math.Distance.Between(u.x,u.y,b.x,b.y))[0];if(t){u.attack=t;this.setCombatPath(u,t)}}}
 findBuildSite(owner:Owner,kind:'house'|'barracks'){const town=this.buildings.find(b=>b.owner===owner&&b.kind==='town');if(!town)return;for(let ring=1;ring<5;ring++)for(let i=0;i<12;i++){const a=i/12*Math.PI*2,x=town.x+Math.cos(a)*(150+ring*65),y=town.y+Math.sin(a)*(150+ring*65);if(this.canPlace(kind,x,y))return{x,y}}}
 enemyBuild(kind:'house'|'barracks',x:number,y:number){if(!this.canPlace(kind,x,y))return;const b=this.addBuilding(kind,'enemy',x,y,0),builder=this.units.find(u=>u.owner==='enemy'&&u.type==='villager'&&!u.build);if(builder){builder.resource=undefined;builder.build=b;this.setPath(builder,x,y+this.buildingRadius(b)+24)}}
 fogAt(x:number,y:number){let best:FogTile|undefined,dist=Infinity;for(const f of this.fog){const d=Math.abs(f.shape.x-x)+Math.abs(f.shape.y-y);if(d<dist){dist=d;best=f}}return best}
 isVisibleAt(x:number,y:number){return this.fogAt(x,y)?.visible??false}
 updateFog(){const scouts=[...this.units.filter(u=>u.owner==='player'),...this.buildings.filter(b=>b.owner==='player'&&b.progress>=1)];for(const f of this.fog){f.visible=false;for(const scout of scouts){const sight='sight'in scout?scout.sight:300;if(Phaser.Math.Distance.Between(f.shape.x,f.shape.y,scout.x,scout.y)<sight){f.visible=true;f.explored=true;break}}f.shape.setVisible(!f.visible).setAlpha(f.explored?.52:.96)}for(const r of this.resources){const fog=this.fogAt(r.x,r.y),shown=!!fog?.explored;r.shape.setVisible(shown).setAlpha(fog?.visible?1:.48);r.label.setVisible(shown).setAlpha(fog?.visible?1:.55)}for(const u of this.units.filter(x=>x.owner==='enemy'))this.setUnitVisibility(u,this.isVisibleAt(u.x,u.y));for(const b of this.buildings.filter(x=>x.owner==='enemy'))this.setBuildingVisibility(b,this.isVisibleAt(b.x,b.y))}
 setUnitVisibility(u:Unit,visible:boolean){u.shape.setVisible(visible);u.ring.setVisible(visible&&u.selected);u.hpBack.setVisible(visible&&u.type!=='villager');u.hpBar.setVisible(visible&&u.type!=='villager');u.label.setVisible(visible)}
 setBuildingVisibility(b:Building,visible:boolean){b.shape.setVisible(visible);b.label.setVisible(visible);b.hpBack.setVisible(visible);b.hpBar.setVisible(visible);b.smoke.setVisible(visible&&b.hp/b.maxHp<.55);b.fire.setVisible(visible&&b.hp/b.maxHp<.28)}
 syncBuilding(b:Building){const size=b.kind==='town'?124:b.kind==='barracks'?104:76,ratio=Phaser.Math.Clamp(b.hp/b.maxHp,0,1),visible=b.owner==='player'||this.isVisibleAt(b.x,b.y);b.hpBack.setPosition(b.x-size*.42,b.y-size*.55);b.hpBar.setPosition(b.x-size*.42,b.y-size*.55).setScale(ratio,1).setFillStyle(ratio>.55?(b.owner==='player'?0x69c56d:0xdc5a50):ratio>.25?0xe0ad45:0xd3463f);const parts=b.shape.list as unknown as Phaser.GameObjects.Components.Visible[];parts.forEach((part,i)=>part.setVisible(i===0||b.progress>=.2+(i-1)*.1));b.shape.setAlpha(.36+.64*b.progress);b.smoke.setPosition(b.x+Math.sin(this.time.now*.003)*7,b.y-size*.68-Math.sin(this.time.now*.004)*5).setScale(.8+Math.sin(this.time.now*.006)*.18);b.fire.setPosition(b.x+12,b.y-size*.4).setScale(.8+Math.sin(this.time.now*.012)*.28);this.setBuildingVisibility(b,visible)}
 syncUnit(u:Unit,time:number){const moving=u.pathIndex<u.path.length,busy=!!u.resource||!!u.build||time<u.attackAnimUntil,bob=(moving||busy)?Math.sin(time*.012+u.id)*2:0,attack=time<u.attackAnimUntil?1.13:1,base=u.type==='villager'?.84:u.type==='cavalry'?1.12:1;u.shape.setPosition(u.x,u.y+bob).setScale(base*attack,base/attack);u.ring.setPosition(u.x,u.y);u.hpBack.setPosition(u.x-16,u.y-31);u.hpBar.setPosition(u.x-16,u.y-31).setScale(Math.max(0,u.hp/u.maxHp),1);u.label.setPosition(u.x,u.y+20);u.label.setText(u.type==='villager'&&u.cargo>0?`${u.cargoKind==='wood'?'🪵':u.cargoKind==='food'?'●':'◆'} ${Math.floor(u.cargo)}`:{villager:'町',soldier:'槍',archer:'弓',cavalry:'騎'}[u.type])}
 action(id:string,icon:string,label:string,cost:string,disabled=false){return`<button type="button" data-action="${id}" ${disabled?'disabled':''}><span class="actionIcon">${icon}</span>${label}<small>${cost}</small></button>`}
 handleAction(action:string){if(action==='town'||action==='house'||action==='barracks')this.beginPlace(action);else if(action==='villager'||action==='soldier'||action==='archer'||action==='cavalry')this.train(action,'player');else if(action==='advance')this.advanceAge();else if(action==='attackTech'||action==='economyTech'||action==='armorTech')this.research(action.replace('Tech','') as Tech);else if(action==='stop'){for(const u of this.units.filter(x=>x.selected)){u.path=[];u.attack=undefined;u.resource=undefined;u.build=undefined}}this.refreshSelectionUi(true)}
 refreshSelectionUi(force=false){const chosen=this.units.filter(u=>u.selected&&u.owner==='player'),b=this.selectedBuilding&&this.buildings.includes(this.selectedBuilding)?this.selectedBuilding:undefined,signature=`${chosen.map(u=>`${u.id}:${Math.floor(u.hp)}:${u.cargo}`).join(',')}|${b?.id}:${Math.floor(b?.hp??0)}:${Math.floor((b?.progress??0)*100)}|${player.age}|${[...player.researched].join(',')}`;if(!force&&signature===this.uiSignature)return;this.uiSignature=signature;const panel=document.querySelector<HTMLElement>('#selectionPanel')!,actions=document.querySelector<HTMLElement>('#actions')!;if(b){panel.innerHTML=`<strong>${this.buildingName(b.kind)}</strong><span>耐久 ${Math.ceil(b.hp)} / ${b.maxHp}${b.progress<1?` ・ 建設 ${Math.floor(b.progress*100)}%`:''}</span>`;if(b.progress<1)actions.innerHTML='<div class="emptyActions">建設中です</div>';else if(b.kind==='town'){const next=[[300,150],[500,300],[800,500]][player.age-1];actions.innerHTML=this.action('villager','町','町人','食 50')+this.action('advance','代','時代進化',next?`食 ${next[0]} / 金 ${next[1]}`:'進化完了',player.age>=4)+this.action('economyTech','採','採集研究','木 120 / 食 100',player.researched.has('economy')||player.age<2)}else if(b.kind==='barracks')actions.innerHTML=this.action('soldier','槍','槍兵','食 60 / 金 30')+this.action('archer','弓','弓兵','食 45 / 金 45',player.age<2)+this.action('cavalry','騎','騎兵','食 80 / 金 70',player.age<3)+this.action('attackTech','剣','武器研究','木 150 / 金 100',player.researched.has('attack')||player.age<2)+this.action('armorTech','盾','防具研究','木 180 / 金 140',player.researched.has('armor')||player.age<3);else actions.innerHTML='<div class="emptyActions">人口上限を5増やします</div>';return}if(chosen.length){const first=chosen[0],mixed=new Set(chosen.map(u=>u.type)).size>1;panel.innerHTML=`<strong>${chosen.length>1?`${chosen.length}体を選択`:this.unitName(first.type)}</strong><span>${chosen.length===1?`体力 ${Math.ceil(first.hp)} / ${first.maxHp} ・ 攻撃 ${first.damage} ・ ${first.resource?'採集中':first.build?'建設中':first.attack?'戦闘中':'待機'}`:mixed?'混成部隊':'同種部隊'}</span>`;actions.innerHTML=(chosen.some(u=>u.type==='villager')?this.action('house','家','家を建設','木 80')+this.action('barracks','兵','兵舎を建設','木 140')+(player.age>=3?this.action('town','町','町の中心を建設','木 450 / 金 250'):''):'')+this.action('stop','■','停止','現在の命令を解除');return}panel.innerHTML='<strong>未選択</strong><span>ユニットまたは建物を選択</span>';actions.innerHTML='<div class="emptyActions">対象を選択すると命令が表示されます</div>'}
 refreshUi(){const set=(id:string,v:string)=>{const e=document.querySelector(id);if(e)e.textContent=v};set('#wood',Math.floor(player.wood)+'');set('#food',Math.floor(player.food)+'');set('#gold',Math.floor(player.gold)+'');set('#pop',`${this.units.filter(u=>u.owner==='player').length}${this.pendingTraining.player?` (+${this.pendingTraining.player})`:''} / ${player.popCap}`);set('#age',ages[player.age-1])}
 updateMiniMap(){const canvas=document.querySelector<HTMLCanvasElement>('#minimap'),ctx=canvas?.getContext('2d');if(!canvas||!ctx)return;const sx=canvas.width/WORLD_W,sy=canvas.height/WORLD_H;ctx.fillStyle='#172318';ctx.fillRect(0,0,canvas.width,canvas.height);for(const f of this.fog){if(!f.explored)continue;ctx.fillStyle=f.visible?'#728a57':'#3d4b39';ctx.fillRect((f.shape.x-40)*sx,(f.shape.y-40)*sy,80*sx+1,80*sy+1)}for(const r of this.resources){if(!this.fogAt(r.x,r.y)?.explored)continue;ctx.fillStyle=r.kind==='wood'?'#285b34':r.kind==='gold'?'#d8ae3d':'#a44f3f';ctx.fillRect(r.x*sx-1,r.y*sy-1,3,3)}for(const b of this.buildings){if(b.owner==='enemy'&&!this.isVisibleAt(b.x,b.y))continue;ctx.fillStyle=b.owner==='player'?'#67a9e0':'#e16b61';ctx.fillRect(b.x*sx-3,b.y*sy-3,7,7)}for(const u of this.units){if(u.owner==='enemy'&&!this.isVisibleAt(u.x,u.y))continue;ctx.fillStyle=u.owner==='player'?'#9acdf0':'#f38b7d';ctx.fillRect(u.x*sx-1,u.y*sy-1,3,3)}const c=this.cameras.main;ctx.strokeStyle='#fff4bf';ctx.lineWidth=1.5;ctx.strokeRect(c.scrollX*sx,c.scrollY*sy,this.scale.width/c.zoom*sx,this.scale.height/c.zoom*sy)}
 say(message:string){const el=document.querySelector<HTMLElement>('#status')!;el.textContent=message;el.style.opacity='1';if(this.statusTimer)clearTimeout(this.statusTimer);this.statusTimer=window.setTimeout(()=>el.style.opacity='0',2200)}
 unitName(t:UnitType){return{villager:'町人',soldier:'槍兵',archer:'弓兵',cavalry:'騎兵'}[t]}
 buildingName(k:BuildingKind){return{town:'町の中心',house:'家',barracks:'兵舎'}[k]}
 resourceName(k:ResourceKind){return{wood:'木',food:'食料',gold:'金'}[k]}
 finish(winner:Owner){if(this.result)return;this.result=winner==='player'?'あなたの勝利':'敵軍の勝利';const elapsed=Math.max(0,Math.floor((this.time.now-this.startTime)/1000)),minutes=Math.floor(elapsed/60).toString().padStart(2,'0'),seconds=(elapsed%60).toString().padStart(2,'0');document.querySelector('#goal')!.textContent=this.result;document.querySelector('#resultTitle')!.textContent=winner==='player'?'勝利':'敗北';document.querySelector('#resultWinner')!.textContent=`勝者：${this.result}`;document.querySelector('#resultTime')!.textContent=`${minutes}:${seconds}`;document.querySelector('#resultAge')!.textContent=ages[player.age-1];const overlay=document.querySelector<HTMLElement>('#resultOverlay')!;overlay.classList.add('show');overlay.setAttribute('aria-hidden','false');for(const u of this.units){u.target=undefined;u.attack=undefined}}
}
new Phaser.Game({type:Phaser.AUTO,parent:'app',backgroundColor:'#111713',scale:{mode:Phaser.Scale.RESIZE,width:window.innerWidth,height:window.innerHeight},render:{antialias:true,pixelArt:false},scene:GameScene});
initOnline();
