import {FACTION_COLORS,PROTOCOL_VERSION,type FactionId,type GameState,type LobbyState,type ServerMessage} from '../shared/protocol';

const SERVER=(import.meta.env.VITE_GAME_SERVER_URL as string|undefined)||'https://frontier-command-server.yesweareborn2die.workers.dev';
const qs=<T extends HTMLElement>(s:string)=>document.querySelector<T>(s)!;
let ws:WebSocket|undefined,roomId='',playerId='',sessionToken='',sequence=1,you:FactionId=0,lobby:LobbyState|undefined,state:GameState|undefined,previousState:GameState|undefined,stateReceivedAt=0,rendering=false,viewCentered=false,selected:number[]=[];
let reconnectTimer=0,placing:''| 'house'|'barracks'='';
const view={x:1200,y:800,zoom:1};
const pointers=new Map<number,{x:number;y:number}>();
let gestureStart:undefined|{distance:number;zoom:number;midX:number;midY:number;worldX:number;worldY:number},dragStart:undefined|{x:number;y:number},dragCurrent:undefined|{x:number;y:number},pinched=false;

export function initOnline(){const start=qs<HTMLButtonElement>('#startGame');start.innerHTML='<span>ひとりで遊ぶ</span><small>SINGLE PLAYER</small>';start.insertAdjacentHTML('afterend','<button type="button" id="onlineGame" class="onlineStart"><span>オンライン対戦</span><small>ONLINE BATTLE</small></button>');document.body.insertAdjacentHTML('beforeend',`<div id="onlineOverlay" aria-hidden="true"><section id="onlineCard"><button id="onlineBack" class="closeOnline">×</button><h2>オンライン対戦</h2><div id="onlineHome"><label>プレイヤー名<input id="onlineName" maxlength="16" autocomplete="nickname" placeholder="TERU"></label><button id="createRoom">部屋を作る</button><label>ルームコード<input id="roomCode" maxlength="6" inputmode="text"></label><button id="joinRoom">部屋に参加</button><p id="onlineError"></p></div><div id="lobbyView" hidden><h3 id="roomTitle"></h3><div id="slots"></div><button id="copyInvite">招待リンクをコピー</button><button id="readyButton">READY</button><button id="startOnline">ゲーム開始</button><p id="lobbyMessage"></p></div></section></div><div id="networkGame" hidden><canvas id="networkCanvas"></canvas><div id="networkHud"><strong id="youFaction"></strong><span id="networkResources"></span><span id="networkStatus"></span></div><div id="networkActions"><button data-online="house">家</button><button data-online="barracks">兵舎</button><button data-online="villager">町人</button><button data-online="soldier">槍兵</button><button data-online="archer">弓兵</button><button data-online="cavalry">騎兵</button><button data-online="age">時代進化</button><button data-online="attack">攻撃研究</button><button data-online="economy">経済研究</button><button data-online="armor">防御研究</button></div><section id="networkEnd" hidden><h2 id="networkResult"></h2><p id="networkElapsed"></p><button id="networkReplay">もう一度プレイ</button><button id="networkHome">タイトルへ戻る</button></section></div>`);
 qs('#onlineGame').onclick=()=>openOnline();qs('#onlineBack').onclick=()=>closeOnline();qs('#createRoom').onclick=()=>void createRoom();qs('#joinRoom').onclick=()=>joinRoom();qs('#copyInvite').onclick=()=>void copyInvite();qs('#readyButton').onclick=()=>send({type:'READY',ready:!lobby?.slots[you].ready});qs('#startOnline').onclick=()=>send({type:'START'});qs('#networkReplay').onclick=()=>location.reload();qs('#networkHome').onclick=()=>{history.replaceState(null,'',location.pathname);location.reload()};qs('#roomCode').addEventListener('input',e=>(e.target as HTMLInputElement).value=(e.target as HTMLInputElement).value.toUpperCase().replace(/[^A-Z2-9]/g,''));document.querySelectorAll<HTMLButtonElement>('[data-online]').forEach(b=>b.onclick=()=>onlineAction(b.dataset.online!));const room=new URLSearchParams(location.search).get('room');if(room){qs<HTMLInputElement>('#roomCode').value=room.toUpperCase();openOnline()}}
function openOnline(){qs('#onlineOverlay').classList.add('show');qs('#onlineOverlay').setAttribute('aria-hidden','false')}
function closeOnline(){qs('#onlineOverlay').classList.remove('show');qs('#onlineOverlay').setAttribute('aria-hidden','true')}
async function createRoom(){const name=validName();if(!name)return;try{const response=await fetch(`${SERVER}/rooms`,{method:'POST'});if(!response.ok)throw new Error();const data=await response.json() as {roomId:string};qs<HTMLInputElement>('#roomCode').value=data.roomId;connect(data.roomId,name)}catch{error('サーバーに接続できません。')}}
function joinRoom(){const name=validName(),code=qs<HTMLInputElement>('#roomCode').value.trim().toUpperCase();if(name&&/^[A-Z2-9]{6}$/.test(code))connect(code,name);else if(!code)error('ルームコードを入力してください。')}
function validName(){const name=qs<HTMLInputElement>('#onlineName').value.replace(/[<>]/g,'').trim().slice(0,16);if(!name){error('名前を入力してください。');return''}return name}
function connect(code:string,name:string){roomId=code;sessionToken=sessionStorage.getItem(`aot:${code}:token`)??'';const url=SERVER.replace(/^http/,'ws')+`/rooms/${code}`;ws?.close();ws=new WebSocket(url);status('接続しています…');ws.onopen=()=>sendRaw({version:PROTOCOL_VERSION,type:'HELLO',roomId,sequence:sequence++,name,sessionToken:sessionToken||undefined});ws.onmessage=e=>receive(JSON.parse(e.data));ws.onclose=()=>{if(state?.phase==='playing'){status('再接続しています…');window.clearTimeout(reconnectTimer);reconnectTimer=window.setTimeout(()=>connect(code,name),1500)}};ws.onerror=()=>error('サーバーに接続できません。')}
function receive(msg:ServerMessage){if(msg.type==='ERROR'){error(msg.message);status(msg.message);return}if(msg.type==='KICKED'){status(msg.message);ws?.close();return}if(msg.type==='WELCOME'){playerId=msg.playerId;sessionToken=msg.sessionToken;you=msg.factionId;lobby=msg.lobby;sessionStorage.setItem(`aot:${roomId}:token`,sessionToken);renderLobby();status('接続しました');return}if(msg.type==='LOBBY'){lobby=msg.lobby;renderLobby();if(msg.lobby.phase!=='lobby')startNetworkGame();return}if(msg.type==='SNAPSHOT'||msg.type==='STATE'){previousState=state;state=msg.state;stateReceivedAt=performance.now();you=msg.you;startNetworkGame();draw()}}
function send(data:Record<string,unknown>){sendRaw({version:PROTOCOL_VERSION,roomId,playerId,sequence:sequence++,...data})}
function sendRaw(data:unknown){if(ws?.readyState===WebSocket.OPEN)ws.send(JSON.stringify(data))}
function renderLobby(){if(!lobby)return;qs<HTMLElement>('#onlineHome').hidden=true;qs<HTMLElement>('#lobbyView').hidden=false;qs('#roomTitle').textContent=`ROOM ${lobby.roomId}`;qs('#slots').innerHTML=lobby.slots.map(s=>`<article class="slot" style="--faction:${FACTION_COLORS[s.index]}"><strong>${['BLUE','RED','GREEN','YELLOW'][s.index]}</strong><span>${s.name??(s.kind==='OPEN'?'参加待ち':s.kind)}</span><small>${s.host?'HOST':s.kind==='CPU'?'READY':s.ready?'READY':s.connected?'WAITING':''}</small>${lobby!.slots[you]?.host&&s.kind!=='HUMAN'?`<select data-slot="${s.index}"><option ${s.kind==='OPEN'?'selected':''}>OPEN</option><option ${s.kind==='CPU'?'selected':''}>CPU</option><option ${s.kind==='CLOSED'?'selected':''}>CLOSED</option></select>`:''}</article>`).join('');document.querySelectorAll<HTMLSelectElement>('[data-slot]').forEach(x=>x.onchange=()=>send({type:'SET_SLOT',slot:Number(x.dataset.slot),kind:x.value}));const mine=lobby.slots[you];qs<HTMLElement>('#readyButton').hidden=!!mine?.host;qs<HTMLElement>('#startOnline').hidden=!mine?.host}
async function copyInvite(){await navigator.clipboard.writeText(`${location.origin}${location.pathname}?room=${roomId}`);qs('#lobbyMessage').textContent='招待リンクをコピーしました。'}
function startNetworkGame(){closeOnline();qs<HTMLElement>('#networkGame').hidden=false;qs<HTMLElement>('#app').style.display='none';qs('#youFaction').textContent=`YOU ${['BLUE','RED','GREEN','YELLOW'][you]}`;qs<HTMLElement>('#youFaction').style.color=FACTION_COLORS[you];const canvas=qs<HTMLCanvasElement>('#networkCanvas');if(state&&!viewCentered){const home=state.buildings.find(b=>b.factionId===you&&b.kind==='town');if(home){view.x=home.x;view.y=home.y;viewCentered=true}}if(!rendering){canvas.addEventListener('pointerdown',pointerDown);canvas.addEventListener('pointermove',pointerMove);canvas.addEventListener('pointerup',pointerUp);canvas.addEventListener('pointercancel',pointerUp);canvas.addEventListener('contextmenu',e=>{e.preventDefault();issueAt(e.clientX,e.clientY)});canvas.addEventListener('wheel',e=>{e.preventDefault();zoomAt(e.clientX,e.clientY,Math.exp(-e.deltaY*.001))},{passive:false});window.addEventListener('resize',resize,{passive:true});rendering=true;requestAnimationFrame(drawLoop)}resize();draw()}
function drawLoop(){if(!rendering)return;draw();requestAnimationFrame(drawLoop)}
function resize(){const c=qs<HTMLCanvasElement>('#networkCanvas');c.width=innerWidth*devicePixelRatio;c.height=innerHeight*devicePixelRatio;view.zoom=Math.max(view.zoom,fitZoom());clampView();draw()}
function fitZoom(){return Math.min(innerWidth/2400,innerHeight/1600)}
function scale(){return view.zoom*devicePixelRatio}
function worldPointAt(clientX:number,clientY:number){const c=qs<HTMLCanvasElement>('#networkCanvas'),r=c.getBoundingClientRect(),s=view.zoom;return{x:view.x+(clientX-r.left-r.width/2)/s,y:view.y+(clientY-r.top-r.height/2)/s}}
function screenPointAt(x:number,y:number){const c=qs<HTMLCanvasElement>('#networkCanvas'),r=c.getBoundingClientRect();return{x:r.width/2+(x-view.x)*view.zoom,y:r.height/2+(y-view.y)*view.zoom}}
function clampView(){const halfW=innerWidth/(2*view.zoom),halfH=innerHeight/(2*view.zoom);view.x=Math.max(Math.min(halfW,1200),Math.min(2400-halfW,view.x));view.y=Math.max(Math.min(halfH,800),Math.min(1600-halfH,view.y))}
function zoomAt(clientX:number,clientY:number,factor:number){const before=worldPointAt(clientX,clientY);view.zoom=Math.max(fitZoom(),Math.min(2.2,view.zoom*factor));const after=worldPointAt(clientX,clientY);view.x+=before.x-after.x;view.y+=before.y-after.y;clampView()}
function pointerDown(e:PointerEvent){const c=e.currentTarget as HTMLCanvasElement;c.setPointerCapture(e.pointerId);pointers.set(e.pointerId,{x:e.clientX,y:e.clientY});if(pointers.size===1){dragStart={x:e.clientX,y:e.clientY};dragCurrent={...dragStart};pinched=false}else if(pointers.size===2){const[a,b]=[...pointers.values()],midX=(a.x+b.x)/2,midY=(a.y+b.y)/2,world=worldPointAt(midX,midY);gestureStart={distance:Math.hypot(a.x-b.x,a.y-b.y),zoom:view.zoom,midX,midY,worldX:world.x,worldY:world.y};dragStart=undefined;dragCurrent=undefined;pinched=true}}
function pointerMove(e:PointerEvent){if(!pointers.has(e.pointerId))return;pointers.set(e.pointerId,{x:e.clientX,y:e.clientY});if(pointers.size===2&&gestureStart){const[a,b]=[...pointers.values()],midX=(a.x+b.x)/2,midY=(a.y+b.y)/2,d=Math.max(10,Math.hypot(a.x-b.x,a.y-b.y));view.zoom=Math.max(fitZoom(),Math.min(2.2,gestureStart.zoom*d/gestureStart.distance));view.x=gestureStart.worldX-(midX-innerWidth/2)/view.zoom;view.y=gestureStart.worldY-(midY-innerHeight/2)/view.zoom;clampView()}else if(pointers.size===1&&dragStart)dragCurrent={x:e.clientX,y:e.clientY}}
function pointerUp(e:PointerEvent){const wasLast=pointers.size===1,start=dragStart,current=dragCurrent;pointers.delete(e.pointerId);if(pointers.size<2)gestureStart=undefined;if(!wasLast||pinched){if(!pointers.size){dragStart=undefined;dragCurrent=undefined;pinched=false}return}dragStart=undefined;dragCurrent=undefined;if(!start||!current)return;const distance=Math.hypot(current.x-start.x,current.y-start.y);if(distance>12)selectBox(start,current);else issueAt(e.clientX,e.clientY)}
function selectBox(a:{x:number;y:number},b:{x:number;y:number}){if(!state)return;const minX=Math.min(a.x,b.x),maxX=Math.max(a.x,b.x),minY=Math.min(a.y,b.y),maxY=Math.max(a.y,b.y);selected=state.units.filter(u=>{if(u.factionId!==you)return false;const p=screenPointAt(u.x,u.y);return p.x>=minX&&p.x<=maxX&&p.y>=minY&&p.y<=maxY}).map(u=>u.id)}
function issueAt(clientX:number,clientY:number){if(!state)return;const p=worldPointAt(clientX,clientY),near=[...state.units,...state.buildings].sort((a,b)=>Math.hypot(a.x-p.x,a.y-p.y)-Math.hypot(b.x-p.x,b.y-p.y))[0];if(placing){const builders=state.units.filter(u=>selected.includes(u.id)&&u.factionId===you&&u.kind==='villager').map(u=>u.id);send({type:'COMMAND',command:{type:'BUILD',builderIds:builders,building:placing,x:p.x,y:p.y}});placing='';return}if(near&&Math.hypot(near.x-p.x,near.y-p.y)<55/view.zoom){if(near.factionId===you){const builders=state.units.filter(u=>selected.includes(u.id)&&u.factionId===you&&u.kind==='villager').map(u=>u.id);if('progress'in near&&near.progress<1&&builders.length){send({type:'COMMAND',command:{type:'CONTINUE_BUILD',builderIds:builders,buildingId:near.id}});return}selected=[near.id];return}if(selected.length)send({type:'COMMAND',command:{type:'ATTACK',unitIds:selected,targetId:near.id}});return}const resource=[...state.map.resources].sort((a,b)=>Math.hypot(a.x-p.x,a.y-p.y)-Math.hypot(b.x-p.x,b.y-p.y))[0];if(resource&&Math.hypot(resource.x-p.x,resource.y-p.y)<45/view.zoom&&selected.length)send({type:'COMMAND',command:{type:'GATHER',unitIds:selected,targetId:resource.id}});else if(selected.length)send({type:'COMMAND',command:{type:'MOVE',unitIds:selected,target:p}})}
function onlineAction(action:string){if(!state)return;if(action==='house'||action==='barracks'){placing=action;status('建設場所をタップしてください。');return}const b=state.buildings.find(x=>selected.includes(x.id)&&x.factionId===you);if(!b){status('対応する建物を選択してください。');return}if(action==='age')send({type:'COMMAND',command:{type:'ADVANCE_AGE',buildingId:b.id}});else if(action==='attack'||action==='economy'||action==='armor')send({type:'COMMAND',command:{type:'RESEARCH',buildingId:b.id,tech:action}});else if(action==='villager'||action==='soldier'||action==='archer'||action==='cavalry')send({type:'COMMAND',command:{type:'TRAIN',buildingId:b.id,unit:action}})}
function draw(){if(!state)return;const c=qs<HTMLCanvasElement>('#networkCanvas'),g=c.getContext('2d')!,s=scale(),alpha=Math.min(1,(performance.now()-stateReceivedAt)/200),oldUnits=new Map(previousState?.units.map(u=>[u.id,u])??[]);g.setTransform(1,0,0,1,0,0);g.fillStyle='#111';g.fillRect(0,0,c.width,c.height);g.setTransform(s,0,0,s,c.width/2-view.x*s,c.height/2-view.y*s);g.fillStyle='#718b54';g.fillRect(0,0,2400,1600);for(const r of state.map.resources){g.fillStyle=r.kind==='wood'?'#285b34':r.kind==='gold'?'#d8ae3d':'#a44f3f';g.beginPath();g.arc(r.x,r.y,10,0,Math.PI*2);g.fill()}for(const b of state.buildings){g.fillStyle=FACTION_COLORS[b.factionId];g.fillRect(b.x-35,b.y-28,70,56);health(g,b.x,b.y-40,b.hp/b.maxHp)}for(const u of state.units){const old=oldUnits.get(u.id),x=old?old.x+(u.x-old.x)*alpha:u.x,y=old?old.y+(u.y-old.y)*alpha:u.y;g.fillStyle=FACTION_COLORS[u.factionId];g.beginPath();g.arc(x,y,selected.includes(u.id)?13:9,0,Math.PI*2);g.fill();if(selected.includes(u.id)){g.strokeStyle='#fff';g.lineWidth=3/view.zoom;g.stroke()}health(g,x,y-18,u.hp/u.maxHp)}const explored=new Set(state.fog[you]??[]),ownUnits=state.units.filter(u=>u.factionId===you),ownBuildings=state.buildings.filter(b=>b.factionId===you);for(let y=0;y<14;y++)for(let x=0;x<20;x++){const wx=x*120+60,wy=y*120+60,visible=ownUnits.some(u=>Math.hypot(u.x-wx,u.y-wy)<290)||ownBuildings.some(b=>Math.hypot(b.x-wx,b.y-wy)<300);if(!visible){g.fillStyle=explored.has(`${x}:${y}`)?'#10181080':'#050807ed';g.fillRect(x*120,y*120,121,121)}}if(dragStart&&dragCurrent&&pointers.size===1){g.setTransform(devicePixelRatio,0,0,devicePixelRatio,0,0);g.strokeStyle='#fff';g.fillStyle='#7db8ff33';g.lineWidth=1.5;const x=Math.min(dragStart.x,dragCurrent.x),y=Math.min(dragStart.y,dragCurrent.y),w=Math.abs(dragCurrent.x-dragStart.x),h=Math.abs(dragCurrent.y-dragStart.y);g.fillRect(x,y,w,h);g.strokeRect(x,y,w,h)}const f=state.factions.find(x=>x.id===you)!;qs('#networkResources').textContent=`木 ${Math.floor(f.wood)}　食 ${Math.floor(f.food)}　金 ${Math.floor(f.gold)}　人口 ${state.units.filter(u=>u.factionId===you).length}/${f.popCap}`;if(state.phase==='countdown')status(`${Math.max(1,Math.ceil((state.startAt-Date.now())/1000))}`);if(state.phase==='ended')showEnd()}
function showEnd(){if(!state)return;const panel=qs<HTMLElement>('#networkEnd');if(!panel.hidden)return;panel.hidden=false;qs('#networkResult').textContent=state.winner===you?'勝利！':'敗北';const seconds=Math.floor(state.timeMs/1000),minutes=Math.floor(seconds/60);qs('#networkElapsed').textContent=`経過時間 ${minutes}:${String(seconds%60).padStart(2,'0')}`}
function health(g:CanvasRenderingContext2D,x:number,y:number,ratio:number){g.fillStyle='#321';g.fillRect(x-16,y,32,4);g.fillStyle=ratio>.5?'#5d6':'#e55';g.fillRect(x-16,y,32*ratio,4)}
function error(message:string){qs('#onlineError').textContent=message}
function status(message:string){qs('#networkStatus').textContent=message}
