import Phaser from 'phaser';
import {FACTION_COLORS,type BuildingState,type FactionId,type GameState,type ResourceState,type UnitState} from '../shared/protocol';

type UnitVisual={shape:Phaser.GameObjects.Container;ring:Phaser.GameObjects.Arc;hpBack:Phaser.GameObjects.Rectangle;hpBar:Phaser.GameObjects.Rectangle;label:Phaser.GameObjects.Text};
type BuildingVisual={shape:Phaser.GameObjects.Container;ring:Phaser.GameObjects.Rectangle;label:Phaser.GameObjects.Text;hpBack:Phaser.GameObjects.Rectangle;hpBar:Phaser.GameObjects.Rectangle;smoke:Phaser.GameObjects.Arc;fire:Phaser.GameObjects.Arc};
type ResourceVisual={shape:Phaser.GameObjects.Container;label:Phaser.GameObjects.Text};

export class OnlinePhaserRenderer{
 private game:Phaser.Game;private scene?:Phaser.Scene;private terrain?:Phaser.GameObjects.Graphics;private fog?:Phaser.GameObjects.Graphics;private state?:GameState;private previous?:GameState;private receivedAt=0;private you:FactionId=0;private selected:number[]=[];private seed=-1;private units=new Map<number,UnitVisual>();private buildings=new Map<number,BuildingVisual>();private resources=new Map<number,ResourceVisual>();
 constructor(parent:string,private view:{x:number;y:number;zoom:number},private ready:(canvas:HTMLCanvasElement)=>void){
  const owner=this;class Scene extends Phaser.Scene{create(){owner.scene=this;this.cameras.main.setBackgroundColor('#111713');owner.ready(this.game.canvas);owner.rebuild()}update(){owner.renderFrame()}}
  this.game=new Phaser.Game({type:Phaser.AUTO,parent,backgroundColor:'#111713',scale:{mode:Phaser.Scale.RESIZE,width:window.innerWidth,height:window.innerHeight},render:{antialias:true,pixelArt:false},scene:Scene});
 }
 setState(state:GameState,previous:GameState|undefined,receivedAt:number,you:FactionId,selected:number[]){this.state=state;this.previous=previous;this.receivedAt=receivedAt;this.you=you;this.selected=selected;if(this.scene)this.rebuild()}
 resize(){this.game.scale.resize(window.innerWidth,window.innerHeight)}
 destroy(){this.game.destroy(true)}
 private rebuild(){const scene=this.scene,state=this.state;if(!scene||!state)return;if(this.seed!==state.seed){this.seed=state.seed;this.clearAll();this.drawMap(state);for(const r of state.map.resources)this.resources.set(r.id,this.makeResource(r))}this.syncEntities()}
 private clearAll(){this.terrain?.destroy();this.fog?.destroy();for(const v of this.units.values())this.destroyUnit(v);for(const v of this.buildings.values())this.destroyBuilding(v);for(const v of this.resources.values()){v.shape.destroy();v.label.destroy()}this.units.clear();this.buildings.clear();this.resources.clear()}
 private drawMap(state:GameState){const s=this.scene!,w=state.map.width,h=state.map.height,g=this.terrain=s.add.graphics().setDepth(-20);g.fillStyle(0x91a966).fillRect(0,0,w,h);const random=new Phaser.Math.RandomDataGenerator([String(state.seed)]);g.fillStyle(0x839b5c,.75);for(let y=40;y<h;y+=90)for(let x=40;x<w;x+=90)if((x+y)%270)g.fillCircle(x+random.between(0,35),y+random.between(0,35),10+random.between(0,20));const sx=w/2400,sy=h/1600;g.lineStyle(170,0x4e91ad,1);new Phaser.Curves.Path(-100,215*sy).splineTo([new Phaser.Math.Vector2(420*sx,265*sy),new Phaser.Math.Vector2(910*sx,185*sy),new Phaser.Math.Vector2(1460*sx,260*sy),new Phaser.Math.Vector2(1960*sx,165*sy),new Phaser.Math.Vector2(w+100,235*sy)]).draw(g,80);g.lineStyle(116,0x69acc2,.8);new Phaser.Curves.Path(-100,215*sy).splineTo([new Phaser.Math.Vector2(420*sx,265*sy),new Phaser.Math.Vector2(910*sx,185*sy),new Phaser.Math.Vector2(1460*sx,260*sy),new Phaser.Math.Vector2(1960*sx,165*sy),new Phaser.Math.Vector2(w+100,235*sy)]).draw(g,80);g.lineStyle(62,0xb99b68,.72);new Phaser.Curves.Path(120*sx,h-280*sy).splineTo([new Phaser.Math.Vector2(430*sx,760*sy),new Phaser.Math.Vector2(900*sx,780*sy),new Phaser.Math.Vector2(1430*sx,690*sy),new Phaser.Math.Vector2(1970*sx,760*sy),new Phaser.Math.Vector2(w-100,h-420*sy)]).draw(g,70);g.lineStyle(34,0xd1b57d,.7);new Phaser.Curves.Path(120*sx,h-280*sy).splineTo([new Phaser.Math.Vector2(430*sx,760*sy),new Phaser.Math.Vector2(900*sx,780*sy),new Phaser.Math.Vector2(1430*sx,690*sy),new Phaser.Math.Vector2(1970*sx,760*sy),new Phaser.Math.Vector2(w-100,h-420*sy)]).draw(g,70);g.fillStyle(0x6e8753,.6);for(let i=0;i<Math.floor(120*sx*sy);i++)g.fillCircle(random.between(0,w),random.between(Math.floor(340*sy),h),random.between(2,7))}
 private makeUnit(u:UnitState){const s=this.scene!,team=Phaser.Display.Color.HexStringToColor(FACTION_COLORS[u.factionId]).color,trim=u.factionId===0?0xd7e9f5:0xf1c2aa,parts:Phaser.GameObjects.GameObject[]=[];parts.push(s.add.ellipse(0,13,u.kind==='cavalry'?42:28,10,0x203022,.28));if(u.kind==='cavalry'){parts.push(s.add.ellipse(-2,3,34,18,0x765037).setStrokeStyle(2,0x3e2c24),s.add.rectangle(-11,13,4,13,0x4b3528),s.add.rectangle(8,13,4,13,0x4b3528),s.add.circle(15,-1,7,0x765037),s.add.rectangle(-4,-8,14,17,team).setStrokeStyle(2,0x26313a),s.add.circle(-4,-19,7,0xe2b88a),s.add.rectangle(6,-13,3,30,trim).setRotation(-.45))}else{parts.push(s.add.rectangle(-5,8,5,12,0x3d332b),s.add.rectangle(5,8,5,12,0x3d332b),s.add.rectangle(0,-1,u.kind==='villager'?16:19,22,team).setStrokeStyle(2,0x29362c),s.add.circle(0,-16,7,0xe4b98a));if(u.kind==='villager')parts.push(s.add.ellipse(0,-20,20,6,0xc69a52),s.add.rectangle(11,0,3,25,0x6f4b2d).setRotation(.55),s.add.rectangle(16,-9,11,6,0x99a7a0).setRotation(.55));if(u.kind==='soldier')parts.push(s.add.triangle(0,-21,-9,7,9,7,0,-7,0xaeb9b8),s.add.rectangle(11,-2,3,38,trim).setRotation(-.25));if(u.kind==='archer')parts.push(s.add.arc(8,-2,11,-78,78,false,0,0).setStrokeStyle(3,0xd4b16f),s.add.rectangle(7,-2,2,23,0xd9c59b).setRotation(-.05))}const shape=s.add.container(u.x,u.y,parts).setDepth(10),ring=s.add.circle(u.x,u.y,u.kind==='cavalry'?25:20).setStrokeStyle(3,0xffe27a).setDepth(9),hpBack=s.add.rectangle(u.x,u.y-31,32,6,0x251d1b,.9).setOrigin(0,.5).setDepth(11),hpBar=s.add.rectangle(u.x,u.y-31,32,4,u.factionId===this.you?0x56c65e:0xe35d52).setOrigin(0,.5).setDepth(12),label=s.add.text(u.x,u.y+20,{villager:'町',soldier:'槍',archer:'弓',cavalry:'騎'}[u.kind],{fontSize:'9px',color:'#fff',stroke:'#111',strokeThickness:2}).setOrigin(.5,0).setDepth(11);return{shape,ring,hpBack,hpBar,label}}
 private makeResource(r:ResourceState){const s=this.scene!,parts:Phaser.GameObjects.GameObject[]=[s.add.ellipse(0,15,42,13,0x203022,.22)];if(r.kind==='wood')parts.push(s.add.rectangle(0,8,10,31,0x704628),s.add.circle(-11,-7,16,0x376b3b).setStrokeStyle(2,0x294c2c),s.add.circle(10,-10,18,0x447c43).setStrokeStyle(2,0x294c2c),s.add.circle(0,-23,15,0x4d884b).setStrokeStyle(2,0x294c2c));if(r.kind==='food')parts.push(s.add.ellipse(0,5,37,25,0x507f3d).setStrokeStyle(2,0x34562d),s.add.circle(-9,0,4,0xd94e3e),s.add.circle(4,-5,4,0xe56a43),s.add.circle(11,5,4,0xd94e3e));if(r.kind==='gold')parts.push(s.add.triangle(-9,5,-14,13,0,-15,12,13,0xd9af42).setStrokeStyle(2,0x7d6329),s.add.triangle(10,7,-12,12,0,-12,12,12,0xf0c85c).setStrokeStyle(2,0x7d6329));return{shape:s.add.container(r.x,r.y,parts).setDepth(3),label:s.add.text(r.x,r.y+28,r.kind==='wood'?'木':r.kind==='food'?'食':'金',{fontSize:'10px',color:'#fff8df',backgroundColor:'#172018cc',padding:{x:4,y:2}}).setOrigin(.5,0).setDepth(4)}}
 private makeBuilding(b:BuildingState){const s=this.scene!,size=b.kind==='town'?124:b.kind==='barracks'?104:76,team=Phaser.Display.Color.HexStringToColor(FACTION_COLORS[b.factionId]).color,wall=b.kind==='town'?0xc4b58d:0xd0bd91,parts:Phaser.GameObjects.GameObject[]=[];parts.push(s.add.ellipse(0,size*.28,size*1.1,size*.28,0x263126,.27),s.add.rectangle(0,5,size,size*.58,wall).setStrokeStyle(3,0x5b4a35),s.add.rectangle(0,-size*.24,size*1.08,size*.24,team).setStrokeStyle(3,0x3e352e),s.add.rectangle(0,size*.13,size*.17,size*.3,0x533923),s.add.rectangle(-size*.28,4,size*.13,size*.16,0x83b7ce).setStrokeStyle(2,0xf0d991),s.add.rectangle(size*.3,4,size*.12,size*.16,0x83b7ce).setStrokeStyle(2,0xf0d991));if(b.kind==='town')parts.push(s.add.rectangle(0,-size*.27,size*.28,size*.46,wall).setStrokeStyle(3,0x5b4a35),s.add.rectangle(0,-size*.51,size*.34,size*.15,team).setStrokeStyle(2,0x3e352e),s.add.rectangle(size*.18,-size*.28,8,34,team));if(b.kind==='barracks')parts.push(s.add.rectangle(size*.28,-5,8,42,team),s.add.circle(size*.28,-28,6,team));const shape=s.add.container(b.x,b.y,parts).setDepth(5),ring=s.add.rectangle(b.x,b.y,size*1.12,size*.9).setStrokeStyle(3,0xffe27a).setDepth(4),label=s.add.text(b.x,b.y+size*.35,b.kind==='town'?'町の中心':b.kind==='house'?'家':'兵舎',{fontSize:'12px',fontStyle:'bold',color:'#fff4d3',backgroundColor:'#172018bb',padding:{x:5,y:2},stroke:'#201a13',strokeThickness:2}).setOrigin(.5).setDepth(6),hpBack=s.add.rectangle(b.x-size*.42,b.y-size*.55,size*.84,7,0x251d1b,.9).setOrigin(0,.5).setDepth(7),hpBar=s.add.rectangle(b.x-size*.42,b.y-size*.55,size*.84,5,b.factionId===this.you?0x69c56d:0xdc5a50).setOrigin(0,.5).setDepth(8),smoke=s.add.circle(b.x,b.y-size*.65,9,0x333a35,.55).setDepth(9),fire=s.add.circle(b.x+12,b.y-size*.45,6,0xf27b32,.85).setDepth(10);return{shape,ring,label,hpBack,hpBar,smoke,fire}}
 private syncEntities(){const state=this.state!;for(const [id,v] of this.resources)if(!state.map.resources.some(r=>r.id===id)){v.shape.destroy();v.label.destroy();this.resources.delete(id)}for(const r of state.map.resources)if(!this.resources.has(r.id))this.resources.set(r.id,this.makeResource(r));for(const [id,v] of this.units)if(!state.units.some(u=>u.id===id)){this.destroyUnit(v);this.units.delete(id)}for(const u of state.units)if(!this.units.has(u.id))this.units.set(u.id,this.makeUnit(u));for(const [id,v] of this.buildings)if(!state.buildings.some(b=>b.id===id)){this.destroyBuilding(v);this.buildings.delete(id)}for(const b of state.buildings)if(!this.buildings.has(b.id))this.buildings.set(b.id,this.makeBuilding(b))}
 private renderFrame(){const s=this.scene,state=this.state;if(!s||!state)return;const alpha=Math.min(1,(performance.now()-this.receivedAt)/200),old=new Map(this.previous?.units.map(u=>[u.id,u])??[]);s.cameras.main.setBounds(0,0,state.map.width,state.map.height).setZoom(this.view.zoom).centerOn(this.view.x,this.view.y);for(const u of state.units){const v=this.units.get(u.id);if(!v)continue;const p=old.get(u.id),x=p?p.x+(u.x-p.x)*alpha:u.x,y=p?p.y+(u.y-p.y)*alpha:u.y;v.shape.setPosition(x,y);v.ring.setPosition(x,y).setVisible(this.selected.includes(u.id));v.hpBack.setPosition(x,y-31).setVisible(u.kind!=='villager'||u.hp<u.maxHp);v.hpBar.setPosition(x,y-31).setDisplaySize(32*Math.max(0,u.hp/u.maxHp),4).setVisible(u.kind!=='villager'||u.hp<u.maxHp);v.label.setPosition(x,y+20);if(u.state==='attacking')v.shape.setAngle(Math.sin(performance.now()/55)*5)}for(const b of state.buildings){const v=this.buildings.get(b.id);if(!v)continue;const size=b.kind==='town'?124:b.kind==='barracks'?104:76;v.shape.setAlpha(.38+.62*b.progress);v.ring.setVisible(this.selected.includes(b.id));v.hpBar.setDisplaySize(size*.84*Math.max(0,b.hp/b.maxHp),5);v.label.setText(b.progress<1?`${b.kind==='house'?'家':'兵舎'} ${Math.floor(b.progress*100)}%`:b.kind==='town'?'町の中心':b.kind==='house'?'家':'兵舎');v.smoke.setVisible(b.hp/b.maxHp<.55);v.fire.setVisible(b.hp/b.maxHp<.28)}this.drawFog()}
 private drawFog(){const s=this.scene!,state=this.state!;this.fog?.destroy();const g=this.fog=s.add.graphics().setDepth(50),explored=new Set(state.fog[this.you]??[]),ownUnits=state.units.filter(u=>u.factionId===this.you),ownBuildings=state.buildings.filter(b=>b.factionId===this.you);for(let y=40;y<state.map.height;y+=80)for(let x=40;x<state.map.width;x+=80){const visible=ownUnits.some(u=>Phaser.Math.Distance.Between(u.x,u.y,x,y)<(u.kind==='villager'?210:270))||ownBuildings.some(b=>Phaser.Math.Distance.Between(b.x,b.y,x,y)<300);if(!visible){const key=`${Math.floor(x/120)}:${Math.floor(y/120)}`;g.fillStyle(0x070b08,explored.has(key)?.55:.95).fillRect(x-40,y-40,80,80)}}}
 private destroyUnit(v:UnitVisual){v.shape.destroy();v.ring.destroy();v.hpBack.destroy();v.hpBar.destroy();v.label.destroy()}
 private destroyBuilding(v:BuildingVisual){v.shape.destroy();v.ring.destroy();v.label.destroy();v.hpBack.destroy();v.hpBar.destroy();v.smoke.destroy();v.fire.destroy()}
}
