import {FACTION_COLORS,PROTOCOL_VERSION,type FactionId,type GameState,type LobbyState,type ServerMessage} from '../shared/protocol';

const SERVER=(import.meta.env.VITE_GAME_SERVER_URL as string|undefined)||'https://frontier-command-server.yesweareborn2die.workers.dev';
const qs=<T extends HTMLElement>(s:string)=>document.querySelector<T>(s)!;
let ws:WebSocket|undefined,roomId='',playerId='',sessionToken='',sequence=1,you:FactionId=0,lobby:LobbyState|undefined,state:GameState|undefined,selected:number[]=[];
let reconnectTimer=0,placing:''| 'house'|'barracks'='';

export function initOnline(){const start=qs<HTMLButtonElement>('#startGame');start.innerHTML='<span>ひとりで遊ぶ</span><small>SINGLE PLAYER</small>';start.insertAdjacentHTML('afterend','<button type="button" id="onlineGame" class="onlineStart"><span>オンライン対戦</span><small>ONLINE BATTLE</small></button>');document.body.insertAdjacentHTML('beforeend',`<div id="onlineOverlay" aria-hidden="true"><section id="onlineCard"><button id="onlineBack" class="closeOnline">×</button><h2>オンライン対戦</h2><div id="onlineHome"><label>プレイヤー名<input id="onlineName" maxlength="16" autocomplete="nickname" placeholder="TERU"></label><button id="createRoom">部屋を作る</button><label>ルームコード<input id="roomCode" maxlength="6" inputmode="text"></label><button id="joinRoom">部屋に参加</button><p id="onlineError"></p></div><div id="lobbyView" hidden><h3 id="roomTitle"></h3><div id="slots"></div><button id="copyInvite">招待リンクをコピー</button><button id="readyButton">READY</button><button id="startOnline">ゲーム開始</button><p id="lobbyMessage"></p></div></section></div><div id="networkGame" hidden><canvas id="networkCanvas"></canvas><div id="networkHud"><strong id="youFaction"></strong><span id="networkResources"></span><span id="networkStatus"></span></div><div id="networkActions"><button data-online="house">家</button><button data-online="barracks">兵舎</button><button data-online="villager">町人</button><button data-online="soldier">槍兵</button><button data-online="archer">弓兵</button></div></div>`);
 qs('#onlineGame').onclick=()=>openOnline();qs('#onlineBack').onclick=()=>closeOnline();qs('#createRoom').onclick=()=>void createRoom();qs('#joinRoom').onclick=()=>joinRoom();qs('#copyInvite').onclick=()=>void copyInvite();qs('#readyButton').onclick=()=>send({type:'READY',ready:!lobby?.slots[you].ready});qs('#startOnline').onclick=()=>send({type:'START'});qs('#roomCode').addEventListener('input',e=>(e.target as HTMLInputElement).value=(e.target as HTMLInputElement).value.toUpperCase().replace(/[^A-Z2-9]/g,''));document.querySelectorAll<HTMLButtonElement>('[data-online]').forEach(b=>b.onclick=()=>onlineAction(b.dataset.online!));const room=new URLSearchParams(location.search).get('room');if(room){qs<HTMLInputElement>('#roomCode').value=room.toUpperCase();openOnline()}}
function openOnline(){qs('#onlineOverlay').classList.add('show');qs('#onlineOverlay').setAttribute('aria-hidden','false')}
function closeOnline(){qs('#onlineOverlay').classList.remove('show');qs('#onlineOverlay').setAttribute('aria-hidden','true')}
async function createRoom(){const name=validName();if(!name)return;try{const response=await fetch(`${SERVER}/rooms`,{method:'POST'});if(!response.ok)throw new Error();const data=await response.json() as {roomId:string};qs<HTMLInputElement>('#roomCode').value=data.roomId;connect(data.roomId,name)}catch{error('サーバーに接続できません。')}}
function joinRoom(){const name=validName(),code=qs<HTMLInputElement>('#roomCode').value.trim().toUpperCase();if(name&&/^[A-Z2-9]{6}$/.test(code))connect(code,name);else if(!code)error('ルームコードを入力してください。')}
function validName(){const name=qs<HTMLInputElement>('#onlineName').value.replace(/[<>]/g,'').trim().slice(0,16);if(!name){error('名前を入力してください。');return''}return name}
function connect(code:string,name:string){roomId=code;sessionToken=sessionStorage.getItem(`aot:${code}:token`)??'';const url=SERVER.replace(/^http/,'ws')+`/rooms/${code}`;ws?.close();ws=new WebSocket(url);status('接続しています…');ws.onopen=()=>sendRaw({version:PROTOCOL_VERSION,type:'HELLO',roomId,sequence:sequence++,name,sessionToken:sessionToken||undefined});ws.onmessage=e=>receive(JSON.parse(e.data));ws.onclose=()=>{if(state?.phase==='playing'){status('再接続しています…');window.clearTimeout(reconnectTimer);reconnectTimer=window.setTimeout(()=>connect(code,name),1500)}};ws.onerror=()=>error('サーバーに接続できません。')}
function receive(msg:ServerMessage){if(msg.type==='ERROR'){error(msg.message);status(msg.message);return}if(msg.type==='KICKED'){status(msg.message);ws?.close();return}if(msg.type==='WELCOME'){playerId=msg.playerId;sessionToken=msg.sessionToken;you=msg.factionId;lobby=msg.lobby;sessionStorage.setItem(`aot:${roomId}:token`,sessionToken);renderLobby();status('接続しました');return}if(msg.type==='LOBBY'){lobby=msg.lobby;renderLobby();if(msg.lobby.phase!=='lobby')startNetworkGame();return}if(msg.type==='SNAPSHOT'||msg.type==='STATE'){state=msg.state;you=msg.you;startNetworkGame();draw()}}
function send(data:Record<string,unknown>){sendRaw({version:PROTOCOL_VERSION,roomId,playerId,sequence:sequence++,...data})}
function sendRaw(data:unknown){if(ws?.readyState===WebSocket.OPEN)ws.send(JSON.stringify(data))}
function renderLobby(){if(!lobby)return;qs<HTMLElement>('#onlineHome').hidden=true;qs<HTMLElement>('#lobbyView').hidden=false;qs('#roomTitle').textContent=`ROOM ${lobby.roomId}`;qs('#slots').innerHTML=lobby.slots.map(s=>`<article class="slot" style="--faction:${FACTION_COLORS[s.index]}"><strong>${['BLUE','RED','GREEN','YELLOW'][s.index]}</strong><span>${s.name??(s.kind==='OPEN'?'参加待ち':s.kind)}</span><small>${s.host?'HOST':s.kind==='CPU'?'READY':s.ready?'READY':s.connected?'WAITING':''}</small>${lobby!.slots[you]?.host&&s.kind!=='HUMAN'?`<select data-slot="${s.index}"><option ${s.kind==='OPEN'?'selected':''}>OPEN</option><option ${s.kind==='CPU'?'selected':''}>CPU</option><option ${s.kind==='CLOSED'?'selected':''}>CLOSED</option></select>`:''}</article>`).join('');document.querySelectorAll<HTMLSelectElement>('[data-slot]').forEach(x=>x.onchange=()=>send({type:'SET_SLOT',slot:Number(x.dataset.slot),kind:x.value}));const mine=lobby.slots[you];qs<HTMLElement>('#readyButton').hidden=!!mine?.host;qs<HTMLElement>('#startOnline').hidden=!mine?.host}
async function copyInvite(){await navigator.clipboard.writeText(`${location.origin}${location.pathname}?room=${roomId}`);qs('#lobbyMessage').textContent='招待リンクをコピーしました。'}
function startNetworkGame(){closeOnline();qs<HTMLElement>('#networkGame').hidden=false;qs<HTMLElement>('#app').style.display='none';qs('#youFaction').textContent=`YOU ${['BLUE','RED','GREEN','YELLOW'][you]}`;qs<HTMLElement>('#youFaction').style.color=FACTION_COLORS[you];const canvas=qs<HTMLCanvasElement>('#networkCanvas');resize();window.addEventListener('resize',resize,{passive:true});canvas.onclick=canvasTap;draw()}
function resize(){const c=qs<HTMLCanvasElement>('#networkCanvas');c.width=innerWidth*devicePixelRatio;c.height=innerHeight*devicePixelRatio;draw()}
function worldPoint(e:MouseEvent){const c=qs<HTMLCanvasElement>('#networkCanvas'),r=c.getBoundingClientRect();return{x:(e.clientX-r.left)/r.width*2400,y:(e.clientY-r.top)/r.height*1600}}
function canvasTap(e:MouseEvent){if(!state)return;const p=worldPoint(e),near=[...state.units,...state.buildings].sort((a,b)=>Math.hypot(a.x-p.x,a.y-p.y)-Math.hypot(b.x-p.x,b.y-p.y))[0];if(placing){const builders=state.units.filter(u=>selected.includes(u.id)&&u.factionId===you&&u.kind==='villager').map(u=>u.id);send({type:'COMMAND',command:{type:'BUILD',builderIds:builders,building:placing,x:p.x,y:p.y}});placing='';return}if(near&&Math.hypot(near.x-p.x,near.y-p.y)<55){if(near.factionId===you){const builders=state.units.filter(u=>selected.includes(u.id)&&u.factionId===you&&u.kind==='villager').map(u=>u.id);if('progress'in near&&near.progress<1&&builders.length){send({type:'COMMAND',command:{type:'CONTINUE_BUILD',builderIds:builders,buildingId:near.id}});return}selected=[near.id];draw();return}if(selected.length)send({type:'COMMAND',command:{type:'ATTACK',unitIds:selected,targetId:near.id}});return}const resource=[...state.map.resources].sort((a,b)=>Math.hypot(a.x-p.x,a.y-p.y)-Math.hypot(b.x-p.x,b.y-p.y))[0];if(resource&&Math.hypot(resource.x-p.x,resource.y-p.y)<45&&selected.length)send({type:'COMMAND',command:{type:'GATHER',unitIds:selected,targetId:resource.id}});else if(selected.length)send({type:'COMMAND',command:{type:'MOVE',unitIds:selected,target:p}})}
function onlineAction(action:string){if(!state)return;if(action==='house'||action==='barracks'){placing=action;status('建設場所をタップしてください。');return}const b=state.buildings.find(x=>selected.includes(x.id)&&x.factionId===you);if(b)send({type:'COMMAND',command:{type:'TRAIN',buildingId:b.id,unit:action}})}
function draw(){if(!state)return;const c=qs<HTMLCanvasElement>('#networkCanvas'),g=c.getContext('2d')!,sx=c.width/2400,sy=c.height/1600;g.fillStyle='#718b54';g.fillRect(0,0,c.width,c.height);for(const r of state.map.resources){g.fillStyle=r.kind==='wood'?'#285b34':r.kind==='gold'?'#d8ae3d':'#a44f3f';g.beginPath();g.arc(r.x*sx,r.y*sy,10*devicePixelRatio,0,Math.PI*2);g.fill()}for(const b of state.buildings){g.fillStyle=FACTION_COLORS[b.factionId];g.fillRect((b.x-35)*sx,(b.y-28)*sy,70*sx,56*sy);health(g,b.x*sx,(b.y-40)*sy,b.hp/b.maxHp)}for(const u of state.units){g.fillStyle=FACTION_COLORS[u.factionId];g.beginPath();g.arc(u.x*sx,u.y*sy,selected.includes(u.id)?13*devicePixelRatio:9*devicePixelRatio,0,Math.PI*2);g.fill();if(selected.includes(u.id)){g.strokeStyle='#fff';g.lineWidth=3;g.stroke()}health(g,u.x*sx,(u.y-18)*sy,u.hp/u.maxHp)}const explored=new Set(state.fog[you]??[]),ownUnits=state.units.filter(u=>u.factionId===you),ownBuildings=state.buildings.filter(b=>b.factionId===you);for(let y=0;y<14;y++)for(let x=0;x<20;x++){const wx=x*120+60,wy=y*120+60,visible=ownUnits.some(u=>Math.hypot(u.x-wx,u.y-wy)<290)||ownBuildings.some(b=>Math.hypot(b.x-wx,b.y-wy)<300);if(!visible){g.fillStyle=explored.has(`${x}:${y}`)?'#10181080':'#050807ed';g.fillRect(x*120*sx,y*120*sy,121*sx,121*sy)}}const f=state.factions.find(x=>x.id===you)!;qs('#networkResources').textContent=`木 ${Math.floor(f.wood)}　食 ${Math.floor(f.food)}　金 ${Math.floor(f.gold)}　人口 ${state.units.filter(u=>u.factionId===you).length}/${f.popCap}`;if(state.phase==='countdown')status(`${Math.max(1,Math.ceil((state.startAt-Date.now())/1000))}`);if(state.phase==='ended')status(state.winner===you?'勝利！':'敗北')}
function health(g:CanvasRenderingContext2D,x:number,y:number,ratio:number){g.fillStyle='#321';g.fillRect(x-16*devicePixelRatio,y,32*devicePixelRatio,4*devicePixelRatio);g.fillStyle=ratio>.5?'#5d6':'#e55';g.fillRect(x-16*devicePixelRatio,y,32*devicePixelRatio*ratio,4*devicePixelRatio)}
function error(message:string){qs('#onlineError').textContent=message}
function status(message:string){qs('#networkStatus').textContent=message}
